import React, { createContext, useContext, useState, useEffect, useCallback, useMemo, ReactNode } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.firm': 'The Firm',
    'nav.about': 'About',
    'nav.expertise': 'Expertise',
    'nav.realEstate': 'Real Estate',
    'nav.taxation': 'Tax and Compliance',
    'nav.estate': 'Family and Legacy',
    'nav.olim': 'Olim Hadashim and Returning Residents',
    'nav.commercial': 'Commercial and Civil',
    'nav.insights': 'Insights',
    'nav.globalClients': 'Global Clients',
    'nav.contact': 'Contact',
    'nav.schedule': 'Schedule Consultation',

    // Hero
    'hero.tagline': 'The Future Favors the Prepared',
    'hero.title': 'Attorney & Notary in Tel Aviv',
    'hero.subtitle1': 'Guiding Every Client with Clarity, Insight, and Strategic Confidence',
    'hero.subtitle2': 'Real estate, taxation, and estate planning delivered with clarity, structure, and financial foresight.',
    'hero.cta': 'Schedule a Consultation',

    // Conflict Section
    'conflict.title': 'Clarity Where Details Decide Outcomes',
    'conflict.body': 'For our clients in Israel and overseas, we bring an international perspective shaped by financial training abroad and legal practice in Israel, anchored in clear local insight. This allows us to offer bilingual counsel on domestic and cross border matters that stay close to client needs, builds strong relationships and turns complex situations into focused, confident decisions.',
    'conflict.body2': 'We begin with verification and documentation so decisions are made with facts, not assumptions. Our role is to turn complex requirements into clear, structured decisions that protect your assets.',

    // Guide Section
    'guide.title': 'About the Firm',
    'guide.bio': 'Maya Ziv Law is built on a combined legal and financial perspective, bringing analytical discipline into every matter. The practice serves clients in Israel and overseas with bilingual counsel on domestic and cross border issues, focused on clear structure and long term security for their business, assets, and personal plans.',
    'guide.punchline': 'We think ahead for our clients, using insight and inventive judgment to guide their decisions and anticipate their needs.',
    'guide.cta': 'More About the Firm',
    'parallax.quote': 'We align legal execution with financial consequences, from day one.',

    // Methodology
    'method.title': 'A Structured Process From Verification to Execution',
    'method.subtitle': 'Clients receive a defined process, clear timelines, and rigorous due diligence with confidentiality and precision at every stage.',
    'method.step1.title': 'Verifying Ownership Before You Sign',
    'method.step1.desc': 'Early verification of ownership, liens, planning status, and zoning under Israeli law protects clients purchasing property in Israel or abroad and prevents exposure during real estate due diligence.',
    'method.step2.title': 'The Role of Legal Counsel in Cross Border Transactions',
    'method.step2.desc': 'Accurate drafting, regulatory oversight, and coordinated execution ensure secure cross border property transfers and financial transactions for clients residing in Israel or overseas.',
    'method.step3.title': 'Coordinated Wills for Cross Border Estates',
    'method.step3.desc': 'Harmonizing Israeli and foreign wills prevents probate conflicts, ensures enforceability across jurisdictions, and protects families managing assets in multiple countries.',
    'method.step4.title': 'Prenuptial Agreements as Strategic Instruments',
    'method.step4.desc': 'Bilingual marital agreements approved by an Israeli court preserve financial clarity, protect property rights, and prevent future disputes for domestic and international couples.',
    'method.step5.title': 'Early Tax Planning Prevents Unnecessary Exposure',
    'method.step5.desc': 'Structured preparation for purchase tax, capital gains, and reporting duties aligns Israeli obligations with foreign tax regimes, minimizing liability for residents and foreign investors.',
    'method.step6.title': 'Legal Structure Determines Long Term Outcomes',
    'method.step6.desc': 'Ownership form, personal, joint, or corporate, directly shapes taxation, inheritance, privacy, and asset transfer, making early structuring essential for clients managing Israeli or cross border assets.',

    // Practice Areas
    'practice.title': 'Areas of Practice',
    'practice.realEstate.title': 'Real Estate & Investment',
    'practice.realEstate.desc': 'Secure acquisition and tax planning.',
    'practice.taxation.title': 'International Tax & Compliance',
    'practice.taxation.desc': 'Cross border reporting and banking regulation.',
    'practice.estate.title': 'Family & Legacy Planning',
    'practice.estate.desc': 'Wills, inheritance, and intergenerational transfer.',
    'practice.learnMore': 'Learn More',
    'practice.additional.olim': 'Olim Hadashim and Returning Residents',
    'practice.additional.commercial': 'Commercial and Civil',

    // Insights
    'insights.title': 'Insights',
    'insights.readMore': 'Continue Reading',
    'insights.viewAll': 'View All Insights',
    'insights.article1.title': 'Buying Property in Israel as a Foreign Resident Legal and Tax Essentials',
    'insights.article1.snippet': 'Foreign residents must address unique legal tax and registration requirements when purchasing property in Israel. Clear due diligence and structured planning ensure a compliant and secure transaction.',
    'insights.article2.title': 'Wills and Inheritance in Israel Ensuring Cross Border Validity',
    'insights.article2.snippet': 'Cross border families must align Israeli inheritance procedures with foreign wills and overseas probate rules. Coordinated planning ensures enforceability and prevents unnecessary legal conflicts.',
    'insights.article3.title': 'Buying Property in Israel Essential Legal Checks for Domestic Buyers',
    'insights.article3.snippet': 'Domestic buyers must verify ownership rights planning status and contractual protections before committing to a property purchase. Structured legal checks reduce exposure and support a transparent and compliant transaction.',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'When should I start tax planning?',
    'faq.a1': 'Tax assessment should begin at the preliminary stage, before signing any binding document. Identifying residency status and tax benefits (for new immigrants or returning residents) during negotiations enables tax liability optimization and prevents financial surprises.',
    'faq.q2': 'How are buyer funds protected during the transaction?',
    'faq.a2': 'Funds are typically held in an escrow account and released to the seller only upon meeting legal milestones pre-established in the purchase contract, such as registering a warning note (Hearat Azhara) in your favor at the Land Registry.',
    'faq.q3': 'Can I purchase property before making Aliyah?',
    'faq.a3': 'Absolutely. The firm guides new immigrants in planning the legal and tax structure of the purchase even before the physical move to Israel, while examining transaction timing to maximize applicable tax benefits.',
    'faq.q4': 'Can I pay Israeli purchase tax in foreign currency?',
    'faq.a4': 'No. Payment to Israeli tax authorities is made in Shekels (ILS). The firm assists with coordinating currency conversion and transferring payment from international accounts in the most accurate manner per legal requirements.',
    'faq.q5': 'Will the Israeli bank automatically accept my transfer?',
    'faq.a5': 'No. The banking system in Israel operates under strict compliance rules. Without advance preparation of a source of funds file and prior bank approval, international transfers may be blocked. We prepare the documentation file in advance to prevent delays.',
    'faq.q6': 'When do I become a tax resident of Israel?',
    'faq.a6': 'Tax residency is determined by the center of life test (presence exceeding 183 days per year), not just citizenship. We advise on legal criteria and examine how your presence in Israel affects your status.',
    'faq.q7': 'Is a foreign will valid in Israel?',
    'faq.a7': 'Executing a foreign will requires a probate process under foreign law involving expert opinions. Drafting a separate Israeli will for assets in the country significantly simplifies the process and saves costs.',
    'faq.q8': 'Can I appoint an estate administrator residing outside Israel?',
    'faq.a8': 'Yes, though additional procedural steps may be required, such as providing guarantees to ensure estate management. The firm guides clients in selecting executors according to their circumstances.',
    'faq.q9': 'What is the difference between an inheritance order and a probate order?',
    'faq.a9': 'A probate order is issued when the deceased left a valid will governing asset distribution. An inheritance order is issued in the absence of a will, with estate distribution then following Israeli Inheritance Law provisions.',

    // CTA
    'cta.title': 'Your Interests Deserve Personal Attention',
    'cta.subtitle': 'Each client, each decision, and each detail receives dedicated care and thoughtful attention.',
    'cta.button': 'Schedule a Consultation',
    'cta.buttonSecondary': 'Initial Fit Assessment',

    // Footer
    'footer.brand': 'Attorney & Notary in Tel Aviv',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.disclaimer': 'Disclaimer',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.disclaimerText': 'This website is for informational purposes only and does not constitute legal advice. No attorney-client relationship is formed by use of this site.',
    'footer.copyright': '© 2024 Maya Ziv Law. All rights reserved.',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Begin your journey to legal clarity',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.inquiry': 'Nature of Inquiry',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Thank you for your message. We will respond within 24 48 hours.',
    'contact.inquiry.realEstate': 'Real Estate Transaction',
    'contact.inquiry.taxation': 'International Taxation',
    'contact.inquiry.estate': 'Estate Planning',
    'contact.inquiry.other': 'Other Legal Matter',

    // About Page
    'about.hero.title': 'Legal Counsel Built Through a Financial Lens',
    'about.hero.subtitle': 'A boutique practice bridging the gap between legal strategy and financial discipline for international clients in Israel.',
    'about.philosophy.title': 'A Different Approach to Legal Practice',
    'about.philosophy.body': 'Maya Ziv Law was founded on a simple realization: for international investors and families, a legal contract is never just a document. It is a financial instrument. Operating in Israel requires more than just legal knowledge; it demands the ability to synchronize local bureaucracy with global standards.',
    'about.philosophy.body2': 'The firm was founded to serve both domestic and international clients who require bilingual legal counsel grounded in legal structure, financial insight, and clear communication. With an international academic background and early professional experience in finance and accounting, the practice brings analytical discipline and global professionalism into the Israeli legal environment. Clients benefit from structured, transparent guidance in matters that shape property, family planning, and long term personal decisions.',
    'about.attorney.title': 'Our Values',
    'about.attorney.body': 'Maya Ziv brings a unique perspective to the legal field. With international training and professional experience in finance and accounting, she approaches every case with financial rigor and a strategic view of the outcome.',
    'about.attorney.body2': 'We prioritize prevention and structure. Our work is designed to reduce friction, protect positions early, and prevent disputes before they arise. By anticipating regulatory hurdles and structuring transactions correctly from the outset, the goal is to create stability-ensuring that your legal arrangements serve your financial and personal legacy for the long term.',
    'about.serve.title': 'Who We Serve',
    'about.serve.body': 'Our practice suits clients who prioritize clarity, diligence and lasting results over quick fixes. We partner with international investors, returning residents, and families who require a high level of involvement and a "zero surprise" policy. We seize opportunities to innovate and grow.',
    'about.serve.body2': 'Whether the matter is commercial or personal, local or cross border, we provide clear legal guidance focused on practical and reliable outcomes.',
    'about.expect.title': 'Why Clients Choose Us',
    'about.expect.intro': 'Engagement with the firm follows a defined, transparent path. We believe that clarity is the antidote to stress, especially when managing affairs remotely.',
    'about.expect.doc.title': 'Documentation First Approach',
    'about.expect.doc.desc': 'We begin with verification. Decisions are made based on facts and official records, not assumptions.',
    'about.expect.intl.title': 'International Transaction Expertise',
    'about.expect.intl.desc': 'A combination of international education, financial training, and Israeli legal practice enables precise bridging between cultures, regulations, and legal systems.',
    'about.expect.timeline.title': 'Domestic and International Perspective',
    'about.expect.timeline.desc': 'With roots in international education, financial training, and Israeli legal practice, the firm bridges cultural and regulatory differences with precision and foresight.',
    'about.expect.comm.title': 'Clarity and Transparency',
    'about.expect.comm.desc': 'Every engagement begins with defined expectations, structured timelines, and full visibility on costs, creating a stable and predictable client experience.',
    'about.expect.foresight.title': 'Strategic Foresight',
    'about.expect.foresight.desc': 'Matters are evaluated with legal precision, financial reasoning, and long term planning to ensure thoughtful and durable outcomes.',
    'about.cta.title': 'Start a Conversation',
    'about.cta.body': 'A clear plan is the first step to protecting assets and legacy.',
    'about.cta.button': 'Schedule a Consultation',

    // Service Pages - General
    'service.faq': 'Common Questions',

    // Estate Planning Page
    'estate.hero.title': 'Families with Assets in Israel and Ties Abroad',
    'estate.hero.subtitle': 'Legal strategies for cross border wealth transfer, bilingual wills, and Enduring Power of Attorney (Israel).',
    'estate.challenge.title': 'Managing Family Wealth Across Jurisdictions',
    'estate.challenge.body': 'Families with assets in Israel and ties abroad face a unique legal landscape. Israeli inheritance procedures often interact with foreign laws, creating potential conflicts regarding jurisdiction and tax liability. A standard Israeli will is rarely sufficient for a multinational estate.\n\nThe firm develops structured estate plans for Israeli and international clients to prevent disputes, avoid probate delays, and reduce exposure to double taxation. The process integrates Israeli inheritance law with relevant foreign legal frameworks, supporting clients residing in Israel or abroad who hold assets or family ties across multiple jurisdictions. This coordinated approach ensures that each inheritance is transferred efficiently and in line with the client\'s intent.',
    'estate.challenge.body2': '',
    'estate.wills.title': 'Families with Assets in Israel and Ties Abroad',
    'estate.wills.body': 'The firm develops structured estate plans for Israeli and international clients to prevent disputes, avoid probate delays, and reduce exposure to double taxation. The process integrates Israeli inheritance law with relevant foreign legal frameworks, supporting clients residing in Israel or abroad who hold assets or family ties across multiple jurisdictions. This coordinated approach ensures that each inheritance is transferred efficiently and in line with the client\'s intent.',
    'estate.wills.compliance.title': 'Drafting for Compliance',
    'estate.wills.compliance.desc': 'Preparing documents to meet Israeli formal requirements and evidentiary standards.',
    'estate.wills.probate.title': 'Probate Management',
    'estate.wills.probate.desc': 'Representing heirs in obtaining Succession Orders (Yerusha) or Probate Orders (Kiyum Tzava\'a) efficiently.',
    'estate.wills.conflict.title': 'Conflict Reduction',
    'estate.wills.conflict.desc': 'Clear, unambiguous drafting intended to minimize interpretation disputes among beneficiaries.',
    'estate.epa.title': 'Enduring Power of Attorney',
    'estate.epa.body': "An Enduring Power of Attorney (EPA) is a forward looking instrument for retaining control over your future. It allows you to appoint trusted representatives to manage your personal and financial affairs in Israel, should the need arise. Unlike court appointed guardianship, an EPA enables you to define the scope of authority in advance. The firm prepares comprehensive, court compliant documents that preserve your autonomy, intent, and family stability.",
    'estate.epa.body2': '',
    'estate.process.title': 'How We Work: The Planning Process',
    'estate.process.step1.title': 'Discovery & Mapping',
    'estate.process.step1.desc': 'We map your assets, jurisdictions, and family dynamics to understand the full legal picture.',
    'estate.process.step2.title': 'Strategy & Structure',
    'estate.process.step2.desc': 'We propose a structure (documents and coordination steps) aligned with your goals and jurisdictions.',
    'estate.process.step3.title': 'Drafting & Execution',
    'estate.process.step3.desc': 'If needed, documents are drafted bilingually and signed in the appropriate form in Israel or abroad to meet evidentiary requirements.',
    'estate.process.step4.title': 'Safe Keeping & Guidance',
    'estate.process.step4.desc': 'We provide instructions for storage and guidance for your executors on future activation.',
    'estate.process.note': 'Clear scope, defined next steps, and documentation requirements are established from the outset.',
    'estate.tax.title': 'Tax Considerations for Cross Border Estates',
    'estate.tax.body': "Israel's tax regime regarding inheritance and transfers differs from many western jurisdictions. Transferring assets whether during ones lifetime or after requires careful timing to avoid unnecessary tax events.",
    'estate.tax.body2': 'We flag potential tax touchpoints in Israel and coordinate with relevant advisors where needed. Our goal is to assess the structure of your estate to reduce avoidable exposure and protect the value of the legacy passing to the next generation.',
    'estate.financial.title': 'Prenuptial and Postnuptial Agreements',
    'estate.financial.body': 'Bilingual agreements in English and Hebrew ensure clarity and enforceability for international couples. Each agreement is drafted with precision and approved by a court or notary, safeguarding property ownership and financial arrangements across borders.',
    'estate.faq.q1': 'Do I need a separate will for my Israeli assets?',
    'estate.faq.a1': 'In many cross border situations, an Israel focused will can reduce procedural friction for assets in Israel. While foreign wills can often be validated here, the process is procedurally complex and slower.',
    'estate.faq.q2': 'Can I appoint a foreign resident as my executor?',
    'estate.faq.a2': 'Yes, though it requires specific procedural steps. We guide clients on the practical implications of appointing executors who reside outside Israel.',
    'estate.faq.q3': 'What is the difference between a Succession Order and a Probate Order?',
    'estate.faq.a3': 'A Probate Order is issued when the deceased left a valid will. A Succession Order is issued when no valid will exists, in which case assets are distributed according to Israeli inheritance law.',
    'estate.faq.q4': 'Can probate proceedings be managed remotely?',
    'estate.faq.a4': 'Yes. We handle the process with the Registrar and banks through a power of attorney, so you are not required to be present in Israel to obtain the order.',
    'estate.cta.title': 'Plan for the Future',
    'estate.cta.body': 'Clear legal planning that supports your interests today and over time.',
    'estate.cta.button': 'Schedule a Consultation',
    'estate.cta.note': 'Response within 1 2 business days',

    // Real Estate Page
    'realestate.hero.title': 'Real Estate',
    'realestate.hero.subtitle': 'Comprehensive counsel for international buyers: Due diligence, tax strategy, and secure registration.',
    'realestate.approach.title': 'More Than a Transaction: A Strategic Investment',
    'realestate.approach.body': 'For many clients, acquiring property in Israel represents more than an investment. It is a personal milestone and a strategic decision with long term financial implications. The firm provides seamless legal guidance throughout the entire acquisition process, including due diligence, contract review, and registration with the Israel Land Registry. Each stage is handled with clarity, discipline, and foresight, ensuring a smooth and secure transaction.',
    'realestate.approach.body2': 'We provide structured legal guidance designed to secure the asset. From preliminary checks to registration with the Israel Land Registry (Tabu), each stage is handled with clarity, discipline, and foresight to ensure a compliant transfer of ownership.',
    'realestate.risk.title': 'Reducing Exposure in a Complex Market',
    'realestate.risk.intro': 'Israeli real estate law places the burden of verification on the buyer. Our due diligence is designed to detect and neutralize risks before you sign:',
    'realestate.risk.liabilities.title': 'Hidden Liabilities',
    'realestate.risk.liabilities.desc': 'Detecting existing liens, debts, or mortgages attached to the title.',
    'realestate.risk.planning.title': 'Planning & Zoning',
    'realestate.risk.planning.desc': 'Verifying that the property is built legally and matches municipal permits to prevent future devaluation or fines.',
    'realestate.risk.tax.title': 'Tax Exposure',
    'realestate.risk.tax.desc': 'Identifying timing issues or residency classifications that could trigger unnecessary tax liabilities.',
    'realestate.tax.title': 'Regulatory and Tax Considerations',
    'realestate.tax.body': 'Purchase tax in Israel is dynamic. Foreign residents are generally subject to different tax brackets compared to new immigrants (Olim) or returning residents.',
    'realestate.tax.body2': 'Purchase tax in Israel applies differently depending on the client profile. Foreign buyers are generally subject to higher tax brackets, while new immigrants and returning residents may be eligible for reduced rates under Israeli law. Drawing on deep familiarity with Israeli regulation and tax requirements, the firm prepares and submits every filing accurately and on time, ensuring that clients benefit from all lawful exemptions and move through the process without administrative setbacks or regulatory delays.',
    'realestate.diligence.title': 'Rigorous Due Diligence',
    'realestate.diligence.body': 'A secure transaction begins with verification. Before any commitment is made, we conduct a comprehensive legal audit of the property. This includes verifying title ownership, checking for encumbrances, and reviewing the planning status.',
    'realestate.diligence.body2': 'This structured analysis allows you to make an informed decision based on documented facts, ensuring the asset you view is the asset you legally acquire.',
    'realestate.remote.title': 'Representation for Clients Abroad',
    'realestate.remote.body': 'Clients residing outside Israel can complete the entire purchase process remotely. Representation is executed through an irrevocable power of attorney signed at an Israeli consulate or before a notary with apostille, enabling secure, compliant, and efficient completion of the transaction.',
    'realestate.remote.body2': 'This enables us to manage the transaction on your behalf, from negotiation to final registration, allowing you to complete the acquisition securely while remaining overseas.',
    'realestate.faq.q1': 'When should tax planning begin?',
    'realestate.faq.a1': 'Tax liability should be assessed before signing any memorandum or contract. Early structuring allows us to apply for relevant exemptions (such as Olim benefits) and prevent overpayment.',
    'realestate.faq.q2': 'How are funds protected during the transaction?',
    'realestate.faq.a2': "Funds are typically held in escrow (trust) and released according to a strict schedule linked to legal milestones, such as the registration of a \"Warning Note\" (He'arat Azhara) in your favor.",
    'realestate.faq.q3': 'Can I buy property before making Aliyah?',
    'realestate.faq.a3': 'Yes. Non residents can purchase property. We advise on how the timing of the purchase relative to your Aliyah date affects your purchase tax benefits.',
    'realestate.cta.title': 'Secure Your Investment',
    'realestate.cta.body': 'Start your acquisition with a clear legal and financial strategy.',
    'realestate.cta.button': 'Schedule a Consultation',

    // Taxation Page
    'tax.hero.title': 'Tax and Compliance',
    'tax.hero.subtitle': '',
    'tax.context.title': 'A Financial Lens on Legal Strategy',
    'tax.context.body': 'Tax and compliance shape whether transactions are approved, funded, and completed. Whether purchasing property or transferring funds, every transaction carries implications in Israel and potentially abroad.',
    'tax.context.body2': 'We approach every case with financial discipline. By integrating tax planning into the legal process, we minimize regulatory friction, support full compliance, and support your standing with financial institutions.',
    'tax.realEstate.title': 'Real Estate Tax Planning',
    'tax.realEstate.body': "Tax assessment is the first step of any property transaction. Israel's tax brackets for Purchase Tax (Mas Rechisha) and Capital Gains Tax (Mas Shevach) vary based on residency and status.",
    'tax.realEstate.assessment.title': 'Pre Contract Assessment',
    'tax.realEstate.assessment.desc': 'Calculating projected liabilities and checking eligibility for relevant exemptions where applicable before you sign.',
    'tax.realEstate.ownership.title': 'Ownership Planning',
    'tax.realEstate.ownership.desc': 'Evaluate ownership and registration options early, aligned with your status and long term goals.',
    'tax.realEstate.filing.title': 'Filing & Reporting',
    'tax.realEstate.filing.desc': 'Managing submissions to the Israel Tax Authority with careful documentation to reduce errors and delays.',
    'tax.banking.title': 'Banking Regulation & Source of Funds',
    'tax.banking.body': 'Transferring funds to or from Israel requires strict adherence to banking regulations and anti money laundering standards. Every transaction is managed in coordination with Israeli financial institutions to ensure compliance with FATCA, AML requirements, and local banking guidelines.',
    'tax.banking.body2': 'The firm also assists in preparing and submitting ongoing tax declarations, aligning Israeli reporting with international obligations and relevant treaties, reducing the risk of double taxation and supporting long term financial and legal stability across jurisdiction.',
    'tax.serve.title': 'Is This Service Right for You?',
    'tax.serve.body': 'This service is designed for clients who prioritize a documented, transparent process. We partner with international investors and private clients who understand that compliance is the key to asset safety.',
    'tax.serve.compliance': 'Compliance First',
    'tax.serve.compliance.desc': 'We give our clients a clear legal focused point of view based on a solid understanding of their needs.',
    'tax.serve.firstStep': 'First Step',
    'tax.serve.firstStep.desc': 'Engagement begins with a clear and focused point of view based on a solid understanding of data needs.',
    'tax.crossBorder.title': 'Coordination with International Obligations',
    'tax.crossBorder.body': "Israel's treaty network may affect how certain income and reporting obligations are treated, depending on your jurisdiction.",
    'tax.crossBorder.body2': 'We flag potential treaty related considerations and coordinate with your foreign tax advisors. While we do not file foreign tax returns, we ensure that your Israeli legal actions are communicated clearly to your global team to maintain a consistent tax position.',
    'tax.olim.title': 'Planning for Olim Hadashim and Returning Residents',
    'tax.olim.body': 'New immigrants and returning residents may be eligible for certain reliefs, including the 10 year reporting relief in certain cases, subject to eligibility rules. We help structure timing and documentation to support a compliant transition into the Israeli tax system.',
    'tax.faq.q1': 'Can I pay Israeli purchase tax in foreign currency?',
    'tax.faq.a1': 'Taxes are generally paid in Shekels (NIS). We guide clients on timing, conversion logistics, and payment vouchers so funds arrive on time and in the required form.',
    'tax.faq.q2': 'Will the Israeli bank automatically accept my transfer?',
    'tax.faq.a2': 'Compliance is never automatic. Large transfers trigger checks. We prepare the "Source of Funds" file in advance to reduce the risk of funds being frozen or rejected.',
    'tax.faq.q3': 'When do I become a tax resident of Israel?',
    'tax.faq.a3': 'Residency is determined by a "Center of Life" test, not just citizenship. We advise on the legal criteria and how your presence in Israel affects your status.',
    'tax.cta.title': 'Strategic Compliance',
    'tax.cta.body': 'Start with clarity, a plan that turns uncertainty into realty.',
    'tax.cta.button': 'Schedule a Consultation',

    // Olim & Returning Residents Page
    'olim.hero.title': 'Legal Counsel for Olim Hadashim and Returning Residents',
    'olim.hero.subtitle': 'A structured legal framework for your transition to Israel: Tax positioning, property acquisition, and asset integration.',
    'olim.context.title': 'A New Chapter Structured from Day One',
    'olim.context.body': 'Beginning a new chapter in Israel brings opportunity, complexity, and important legal choices. The firm provides patient, personal, and structured legal guidance for Olim Hadashim and returning residents, ensuring that each client feels supported, informed, and secure from the first step onward.',
    'olim.context.body2': '',
    'olim.framework.title': 'The Soft Landing Framework',
    'olim.framework.planning.title': 'Pre Arrival Planning',
    'olim.framework.planning.desc': 'Timing, documentation, and positioning steps aligned with your residency status to prevent unnecessary tax events.',
    'olim.framework.property.title': 'Property Acquisition Coordination',
    'olim.framework.property.desc': 'Due diligence and purchase planning aligned with specific eligibility considerations and long term goals.',
    'olim.framework.banking.title': 'Banking & Transfers',
    'olim.framework.banking.desc': "Organizing source of funds documentation and supporting the bank's compliance review process and documentation requirements.",
    'olim.framework.peace.title': 'Complete Peace of Mind',
    'olim.framework.peace.desc': 'The firm translates complex legal processes into clear and practical steps, offering complete peace of mind during one of life\'s most meaningful transitions. Clients benefit from bilingual communication, cross border coordination, and a disciplined legal approach that protects their interests in Israel and abroad.',
    'olim.tax.title': 'Tax Positioning for Olim Hadashim and Returning Residents',
    'olim.tax.body': 'Olim (new immigrants) and Returning Residents (Toshav Hozer Vatik) may be eligible for specific tax and reporting reliefs, subject to eligibility rules and classification. Correct timing and documentation are critical to securing these benefits.',
    'olim.tax.body2': 'We help clients map their status, flag relevant considerations, and coordinate with tax professionals where needed to support a compliant transition and reduce avoidable exposure.',
    'olim.clients.title': 'Our Clients Trust Us',
    'olim.clients.body': 'This page is designed for individuals and families relocating to Israel who value a structured, compliance first process especially where significant assets, foreign income, or cross border beneficiaries are involved.',
    'olim.expect.title': 'What to Expect',
    'olim.expect.body': 'Engagement begins with a documentation checklist, status mapping (residency and tax profile), and a coordinated roadmap with defined next steps.',
    'olim.expect.item1': 'Documentation checklist tailored to your situation',
    'olim.expect.item2': 'Residency and tax status mapping',
    'olim.expect.item3': 'Coordinated roadmap with defined next steps',
    'olim.cta.title': 'Start Your Transition on Solid Ground',
    'olim.cta.body': 'Begin with a structured roadmap and a documentation checklist.',
    'olim.cta.button': 'Schedule a Consultation',

    // Commercial & Civil Page
    'commercial.hero.title': 'Commercial and Civil',
    'commercial.hero.subtitle': 'Protecting business interests through disciplined contracts and Israel based representation for cross border matters.',
    'commercial.philosophy.title': 'Precision Before Disputes',
    'commercial.philosophy.body': 'In commercial engagements, the strength of your position depends on the precision of your contracts. Whether drafting a partnership agreement or negotiating an exit, we evaluate each matter through three lenses: contractual rights, financial exposure, and future enforcement.',
    'commercial.philosophy.body2': 'The firm provides disciplined legal analysis in contractual and business disputes. Each matter is evaluated through contractual rights, financial exposure, and available remedies. Clients receive structured guidance that supports negotiation, dispute resolution, or formal legal proceedings when required.',
    'commercial.services.title': 'Core Services',
    'commercial.services.contracts.title': 'Contract Drafting & Review',
    'commercial.services.contracts.desc': "Structuring shareholders' agreements, partnerships, commercial leases, and service agreements with precise definitions.",
    'commercial.services.negotiation.title': 'Negotiation & Risk Positioning',
    'commercial.services.negotiation.desc': 'Strategic legal counsel before signature or during escalation to improve your leverage.',
    'commercial.services.dispute.title': 'Dispute Strategy & Resolution',
    'commercial.services.dispute.desc': 'Pre litigation steps, settlement frameworks, and litigation management where required.',
    'commercial.services.crossborder.title': 'Cross Border Documentation',
    'commercial.services.crossborder.desc': 'Coordination with overseas counsel and localization of documents for enforcement in Israel.',
    'commercial.crossborder.title': 'Business Interests Across Borders',
    'commercial.crossborder.body': 'We manage commercial matters with international components, acting as the local legal arm for our clients investors and businesses. This structured approach supports clients who reside abroad but maintain active interests in Israel.',
    'commercial.crossborder.body2': 'Whether enforcing a foreign contract in Israel or protecting a local shareholder interests while overseas, we provide practical on the ground representation for civil matters with international dimensions. The practice coordinates Israeli legal requirements with foreign counsel and cross border strategy, supporting clients who reside abroad or maintain legal and financial ties across multiple jurisdictions.',
    'commercial.clients.title': 'Who We Typically Work With',
    'commercial.clients.body': 'Our commercial practice focuses on contracts, asset protection, and complex disputes, and serves both businesses and private individuals. We work with business owners, investors, executives, and private clients who require ongoing legal counsel or strategic resolution for significant commercial and civil matters.',
    'commercial.cta.title': 'Protect Your Commercial Interests',
    'commercial.cta.body': 'Start with a contract review or a dispute strategy assessment. Confidential and documented.',
    'commercial.cta.button': 'Schedule a Consultation',
  },
  he: {
    // Navigation
    'nav.firm': 'אודות',
    'nav.about': 'אודות',
    'nav.expertise': 'תחומי מומחיות',
    'nav.realEstate': 'נדל״ן',
    'nav.taxation': 'מיסוי',
    'nav.estate': 'תכנון עזבונות, ירושות וצוואות',
    'nav.olim': 'עולים חדשים ותושבים חוזרים',
    'nav.commercial': 'דיני מסחר ואזרחי',
    'nav.insights': 'מאמרים',
    'nav.globalClients': 'לקוחות בינלאומיים',
    'nav.contact': 'צור קשר',
    'nav.schedule': 'תיאום פגישת ייעוץ',

    // Hero
    'hero.tagline': 'העתיד מעדיף את המוכנים',
    'hero.title': 'מאיה זיו | עורכת דין ונוטריון בתל אביב',
    'hero.subtitle1': 'מלווים כל לקוח בבהירות, בבטחון ובמצוינות',
    'hero.subtitle2': 'החלטות אסטרטגיות בעולם גלובאלי',
    'hero.cta': 'בקשת ייעוץ חסוי',
    'hero.ctaSecondary': 'איך עובד התהליך?',

    // Conflict Section
    'conflict.title': 'בהירות במקום שהפרטים קובעים את התוצאה',
    'conflict.body': 'עבור לקוחותינו בישראל ומעבר לים, אנו מביאים פרספקטיבה בינלאומית המשלבת הכשרה פיננסית גלובלית עם פרקטיקה משפטית בישראל, המעוגנת בהבנה עמוקה של הדין המקומי. שילוב זה מאפשר לנו להעניק ייעוץ דו-לשוני בסוגיות מקומיות וחוצות גבולות, תוך מחשבה מתמדת בצורכי הלקוח ובניית מערכות יחסים ארוכות טווח. אנו מתרגמים מצבים מורכבים להחלטות ממוקדות ובטוחות.',
    'conflict.body2': 'אנו מתחילים באימות ותיעוד כדי שהחלטות יתקבלו על בסיס עובדות, לא הנחות. התפקיד שלנו הוא להפוך דרישות מורכבות להחלטות ברורות ומובנות שמגנות על הנכסים שלכם.',

    // Guide Section
    'guide.title': 'אודות המשרד',
    'guide.bio': 'המשרד הוקם כדי להעניק ללקוחות ליווי משפטי מקומי ובינלאומי, המבוסס על רקע אקדמי בהיר. המשרד מביא ניסיון מקצועי ותקשורת פיננסית קפדנית, על מנת לתכנן משפטית וגלובלית בהתאם לסטנדרטים אנליטיים. לקוחות המשרד נהנים מליווי שקוף ומובנה בסוגיות תכנון נכסיהם, לטווח הארוך, תוך שמירה על ההחלטות האישיות והמשפחתיות שלהם.',
    'guide.punchline': 'אנו חושבים צעד אחד קדימה עבור לקוחותינו ומקבלים החלטות אסטרטגיות לחזות את אתגרי המחר.',
    'guide.cta': 'קראו עוד על המשרד',
    'parallax.quote': 'תכנון משפטי המעוגן בהשלכות כלכליות ארוכות טווח, מהיום הראשון.',

    // Methodology
    'method.title': 'תובנות משפטיות במבט מהיר',
    'method.subtitle': '',
    'method.step1.title': 'חשיבות בדק על הנכס',
    'method.step1.desc': 'בדיקה מוקדמת של זכויות בעלות, שעבודים, סטטוס תכנוני וייעוד מגנה על רוכשים ומונעת סיכונים משפטיים בעת רכישת נכס.',
    'method.step2.title': 'תפקיד הייעוץ המשפטי בעסקאות בין לאומיות',
    'method.step2.desc': 'בדיקת נאותות, פיקוח וליווי משפטי מקיימים העברת זכויות וניהול כספים בטוח בעסקאות חוצות גבולות.',
    'method.step3.title': 'תיאום צוואות למשפחות בינלאומיות',
    'method.step3.desc': 'תיאום בין צוואות שנערכו בישראל ומעבר לים מונע סכסוכי ירושה, מבטיח אכיפה משפטית, והגנה מיטבית על הרכוש והמשפחה.',
    'method.step4.title': 'הסכם ממון ככלי אסטרטגי',
    'method.step4.desc': 'הסכמים המאושרים על ידי ערכאה מוסמכת שומרים על בהירות פיננסית, מגנים על זכויות רכוש ומונעים מחלוקות עתידיות.',
    'method.step5.title': 'תכנון מס מוקדם ככלי לחסכון כלכלי',
    'method.step5.desc': 'תכנון מקדים והערכות מוקדמת לתשלומי מס רכישה, מס שבח ודיווחים שוטפים בישראל או במדינות מעבר לים מפחית את החשיפה למס ומונע כפל תשלומים.',
    'method.step6.title': 'המבנה המשפטי קובע את התוצאה',
    'method.step6.desc': 'האם הבעלות תהיה אישית, משותפת או תאגידית? הבחירה משפיעה על מיסוי, ירושה, פרטיות והעברת נכסים, לכן חשוב להחליט נכון מההתחלה.',

    // Practice Areas
    'practice.title': 'תחומי עסוק',
    'practice.realEstate.title': 'נדל"ן והשקעות',
    'practice.realEstate.desc': 'ליווי רכישה ומכירה, בדיקות נאותות ורישום זכויות.',
    'practice.taxation.title': 'מיסוי',
    'practice.taxation.desc': 'תכנון מס מקרקעין, ייעוץ תושבות ו-Compliance בנקאי.',
    'practice.estate.title': 'תכנון עזבונות, ירושות וצוואות',
    'practice.estate.desc': 'עריכת צוואות, ייפוי כוח מתמשך וניהול עיזבונות.',
    'practice.learnMore': 'למידע נוסף',
    'practice.additional.olim': 'עולים חדשים ותושבים חוזרים',
    'practice.additional.commercial': 'משפט מסחרי ואזרחי',

    // Insights
    'insights.title': 'מאמרים נבחרים',
    'insights.readMore': 'קרא עוד',
    'insights.viewAll': 'קרא עוד',
    'insights.article1.title': 'רכישת נכס בישראל לתושב חוץ',
    'insights.article1.snippet': 'מדריך ליסודות המיסוי, העברת כספים ורישום בטוח בטאבו.',
    'insights.article2.title': 'ירושות וצוואות חוצות גבולות',
    'insights.article2.snippet': 'כיצד להבטיח תוקף משפטי לנכסים בישראל כחלק מעיזבון גלובלי.',
    'insights.article3.title': 'בדיקות לפני קניית דירה',
    'insights.article3.snippet': 'חריגות בנייה, היטל השבחה והגנות משפטיות בחוזה הרכישה.',

    // FAQ
    'faq.title': 'שאלות נפוצות',
    'faq.q1': 'מתי כדאי להתחיל בתכנון המס?',
    'faq.a1': 'הערכת המס צריכה להתבצע בשלב המקדמי עוד לפני החתימה על מסמך מחייב. זיהוי סטטוס התושבות והטבות המס (לעולים חדשים או תושבים חוזרים) בשלב המשא ומתן מאפשר אופטימיזציה של חבויות המס ומונע הפתעות פיננסיות.',
    'faq.q2': 'כיצד מובטחת הגנה על כספי הרוכש במהלך העסקה?',
    'faq.a2': 'הכספים לרוב מוחזקים בחשבון נאמנות (Escrow) ומשוחררים למוכר רק ובהתאם לעמידה באבני דרך משפטיות שנקבעו מראש בחוזה המכר, כגון רישום הערת אזהרה לטובתכם בלשכת רישום המקרקעין.',
    'faq.q3': 'האם ניתן לרכוש נכס לפני ביצוע העלייה לישראל?',
    'faq.a3': 'בהחלט. המשרד מלווה עולים חדשים בתכנון המבנה המשפטי והמיסויי של הרכישה עוד לפני המעבר הפיזי לישראל, תוך בחינת תזמון העסקה במטרה למקסם את הטבות המס המגיעות להם.',
    'faq.q4': 'האם אפשר לשלם מס רכישה ישראלי במטבע חוץ?',
    'faq.a4': 'לא. התשלום לרשויות המס בישראל מתבצע בשקלים (ILS). המשרד מסייע בתיאום ההמרה והעברת התשלום מחשבונות בינלאומיים בצורה המדויקת ביותר בהתאם לדרישות הדין.',
    'faq.q5': 'האם הבנק הישראלי יקבל את ההעברה שלי אוטומטית?',
    'faq.a5': 'לא. המערכת הבנקאית בישראל פועלת תחת כללי ציות (Compliance) קפדניים. ללא הכנה מוקדמת של תיק מקור כספים ואישור מוקדם מהבנק, העברות בינלאומיות עלולות להיחסם. אנו מכינים את תיק התיעוד מראש למניעת עיכובים.',
    'faq.q6': 'מתי אני הופך לתושב מס בישראל?',
    'faq.a6': 'תושבות לצרכי מס נקבעה פי מבחן מרכז החיים (שהייה של מעל 183 ימים בשנה) ולא רק על בסיס אזרחות. אנו מייעצים לגבי הקריטריונים המשפטיים ובוחנים כיצד הנוכחות שלכם בישראל משפיעה על הסטטוס.',
    'faq.q7': 'האם צוואה זרה תקפה בישראל?',
    'faq.a7': 'מימוש צוואה זרה מחייב הליך של אישור צוואה לפי דין זר המערב חוות דעת מומחים. עריכת צוואה ישראלית נפרדת המיועדת לנכסים בארץ מפשטת באופן משמעותי את התהליך וחוסכת עלויות.',
    'faq.q8': 'האם ניתן למנות מנהל עיזבון המתגורר מחוץ לישראל?',
    'faq.a8': 'כן, אך לעיתים נדרשים צעדים פרוצדורליים נוספים כגון העמדת ערבויות להבטחת ניהול העיזבון. המשרד מנחה את הלקוח בבחירת המבצעים בהתאם לנסיבות.',
    'faq.q9': 'מה ההבדל בין צו ירושה לצו קיום צוואה?',
    'faq.a9': 'צו קיום צוואה ניתן כאשר המנוח הותיר צוואה תקפה המסדירה את חלוקת רכושו. צו ירושה ניתן בהיעדר צוואה ואז חלוקת העיזבון מתבצעת לפי הוראות חוק הירושה הישראלי.',

    // CTA
    'cta.title': 'הלקוחות שלנו חשובים לנו',
    'cta.subtitle': 'אנחנו מחויבים לליווי משפטי מדויק, בהירות מחשבתית וביטחון אסטרטגי בכל החלטה',
    'cta.button': 'צור קשר',
    'cta.buttonSecondary': 'בדיקת התאמה ראשונית',

    // Footer
    'footer.brand': 'עורכת דין ונוטריון בתל אביב',
    'footer.services': 'שירותים',
    'footer.contact': 'צור קשר',
    'footer.legal': 'משפטי',
    'footer.disclaimer': 'הסתייגות',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    'footer.disclaimerText': 'התוכן באתר זה מיועד למידע כללי בלבד ואינו מהווה ייעוץ משפטי. שימוש באתר או יצירת קשר דרכו אינם יוצרים יחסי עורך דין-לקוח.',
    'footer.copyright': '© 2025 עו"ד מאיה זיו. כל הזכויות שמורות.',

    // Contact Page
    'contact.title': 'צור קשר',
    'contact.subtitle': 'התחילו את המסע שלכם לבהירות משפטית',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'כתובת אימייל',
    'contact.form.phone': 'מספר טלפון',
    'contact.form.inquiry': 'אופי הפנייה',
    'contact.form.message': 'ההודעה שלכם',
    'contact.form.submit': 'שלח הודעה',
    'contact.form.success': 'תודה על פנייתכם. נחזור אליכם תוך 24 48 שעות.',
    'contact.inquiry.realEstate': 'עסקת נדל"ן',
    'contact.inquiry.taxation': 'מיסוי בינלאומי',
    'contact.inquiry.estate': 'ירושות וצוואות',
    'contact.inquiry.other': 'עניין משפטי אחר',

    // About Page
    'about.hero.title': 'אודות המשרד',
    'about.hero.subtitle': 'פרקטיקת בוטיק המגשרת בין אסטרטגיה משפטית למשמעת פיננסית עבור לקוחות בינלאומיים בישראל.',
    'about.philosophy.title': '',
    'about.philosophy.body': 'המשרד הוקם כדי להעניק ללקוחות מקומיים ובינלאומיים ליווי משפטי דו-לשוני, המבוסס על תכנון משפטי קפדני, ראייה פיננסית ותקשורת בהירה. מתוך רקע אקדמי בינלאומי וניסיון מקצועי בפיננסים ובחשבונאות, המשרד מביא משמעת אנליטית וסטנדרטים גלובליים אל עולם המשפט הישראלי.',
    'about.philosophy.body2': 'לקוחות המשרד נהנים מליווי מובנה ושקוף בסוגיות המעצבות את נכסיהם, את התכנון המשפחתי ואת ההחלטות האישיות לטווח הארוך.',
    'about.attorney.title': 'הערכים שלנו',
    'about.attorney.body': 'מאיה זיו מביאה פרספקטיבה ייחודית לתחום המשפט. עם הכשרה בינלאומית וניסיון מקצועי בפיננסים ובחשבונאות, היא ניגשת לכל תיק עם קפדנות פיננסית וראייה אסטרטגית של התוצאה.',
    'about.attorney.body2': 'אנו מעדיפים מניעה ומבנה. העבודה שלנו נועדה להפחית חיכוך, להגן על עמדות מוקדם ולמנוע סכסוכים לפני שהם מתעוררים. על ידי צפייה מראש של מכשולים רגולטוריים ומבנון נכון של עסקאות מההתחלה, המטרה היא ליצור יציבות - להבטיח שהסידורים המשפטיים שלכם ישרתו את המורשת הפיננסית והאישית שלכם לטווח ארוך.',
    'about.serve.title': 'את מי אנו משרתים',
    'about.serve.body': 'הפרקטיקה שלנו מתאימה ללקוחות שמעדיפים בהירות, שקדנות ותוצאות מתמשכות על פני פתרונות מהירים. אנו שותפים למשקיעים בינלאומיים, תושבים חוזרים ומשפחות הדורשים רמה גבוהה של מעורבות ומדיניות של "אפס הפתעות". אנו תופסים הזדמנויות לחדש ולצמוח.',
    'about.serve.body2': 'בין אם העניין מסחרי או אישי, מקומי או חוצה גבולות, אנו מספקים הדרכה משפטית ברורה המתמקדת בתוצאות מעשיות ואמינות.',
    'about.expect.title': 'מדוע הלקוחות שלנו בוחרים בנו',
    'about.expect.intro': 'המשרד מלווה את לקוחותיו, בין אם הם מתגוררים בישראל או מעבר לים, תוך שילוב ציפיות ברורות ותקשורת קפדנית.',
    'about.expect.doc.title': 'פרספקטיבה מקומית ובינלאומית',
    'about.expect.doc.desc': 'המשרד מלווה תושבי ישראל ולקוחות העולים לישראל או מתגוררים מעבר לים, תוך הקפדה על תקשורת ברורה, תיאום ציפיות ושילוב חלק בין מערכות משפט שונות.',
    'about.expect.intl.title': 'מומחיות בעסקאות בינלאומיות',
    'about.expect.intl.desc': 'שילוב של השכלה בין לאומית, הכשרה פיננסית ופרקטיקה משפטית בישראל מאפשר גישור מדויק בין תרבויות, רגולציות ומערכות דין.',
    'about.expect.timeline.title': 'שקיפות ובהירות',
    'about.expect.timeline.desc': 'אנו מאמינים במערכות יחסים ארוכות טווח, כל התקשרות נפתחת בהגדרת מסגרת ברורה, לוחות זמנים מדויקים ושקיפות שמייצרת בעבור לקוחותינו ביטחון.',
    'about.expect.comm.title': 'חשיבה אסטרטגית',
    'about.expect.comm.desc': 'כל סוגיה נבחנת בדיוק משפטי, בהיגיון פיננסי ובתכנון פתרונות עמידים וארוכי טווח.',
    'about.expect.foresight.title': 'מחויבות אישית',
    'about.expect.foresight.desc': 'לקוחותינו מקבלים ליווי מעורכת הדין הבכירה, בשיקול דעת מקצועי ומחויבות מלאה למטרותיהם.',
    'about.cta.title': 'התחילו שיחה',
    'about.cta.body': 'תוכנית ברורה היא הצעד הראשון להגנה על נכסים ומורשת.',
    'about.cta.button': 'תיאום שיחת ייעוץ',

    // Service Pages - General
    'service.faq': 'שאלות נפוצות',

    // Estate Planning Page
    'estate.hero.title': 'משפחות עם נכסים בישראל וזיקה בינלאומית',
    'estate.hero.subtitle': 'אסטרטגיות משפטיות להעברת עושר חוצה גבולות, צוואות דו-לשוניות וייפוי כוח מתמשך (ישראל).',
    'estate.challenge.title': 'ניהול הון משפחתי בין תחומי שיפוט',
    'estate.challenge.body': 'משפחות עם נכסים בישראל וזיקות לחו"ל מתמודדות עם נוף משפטי ייחודי. הליכי ירושה ישראליים לעתים קרובות מתממשקים עם חוקים זרים, יוצרים קונפליקטים פוטנציאליים בנוגע לסמכות שיפוט וחבות מס. צוואה ישראלית סטנדרטית לעתים רחוקות מספיקה לעיזבון רב-לאומי.',
    'estate.challenge.body2': 'המשרד מפתח תוכניות עיזבון מובנות ללקוחות ישראליים ובינלאומיים למניעת סכסוכים, הימנעות מעיכובי פרובייט והפחתת חשיפה למיסוי כפול. התהליך משלב דיני ירושה ישראליים עם מסגרות משפטיות זרות רלוונטיות, תומך בלקוחות המתגוררים בישראל או בחו"ל המחזיקים בנכסים או קשרים משפחתיים במספר תחומי שיפוט. גישה מתואמת זו מבטיחה שכל ירושה מועברת ביעילות ובהתאם לכוונת הלקוח.',
    'estate.wills.title': 'משפחות עם נכסים בישראל וזיקה בינלאומית',
    'estate.wills.body': 'המשרד מפתח תוכניות עיזבון מובנות ללקוחות ישראליים ובינלאומיים למניעת סכסוכים, הימנעות מעיכובי פרובייט והפחתת חשיפה למיסוי כפול.',
    'estate.wills.compliance.title': 'ניסוח לתאימות',
    'estate.wills.compliance.desc': 'הכנת מסמכים העומדים בדרישות הצורניות והראייתיות הישראליות.',
    'estate.wills.probate.title': 'ניהול פרובייט',
    'estate.wills.probate.desc': 'ייצוג יורשים בהשגת צו ירושה או צו קיום צוואה ביעילות.',
    'estate.wills.conflict.title': 'הפחתת קונפליקטים',
    'estate.wills.conflict.desc': 'ניסוח ברור וחד-משמעי שנועד למזער מחלוקות פרשנות בין מוטבים.',
    'estate.epa.title': 'ייפוי כוח מתמשך',
    'estate.epa.body': 'ייפוי כוח מתמשך (EPA) הוא מכשיר צופה פני עתיד לשמירה על שליטה בעתידכם. הוא מאפשר לכם למנות נציגים מהימנים לנהל את ענייניכם האישיים והפיננסיים בישראל, אם יתעורר הצורך.',
    'estate.epa.body2': 'בניגוד לאפוטרופסות הממונה על ידי בית משפט, EPA מאפשר לכם להגדיר את היקף הסמכות מראש. המשרד מכין מסמכים מקיפים התואמים לבית המשפט ששומרים על האוטונומיה, הכוונה והיציבות המשפחתית שלכם.',
    'estate.process.title': 'איך אנחנו עובדים: תהליך התכנון',
    'estate.process.step1.title': 'גילוי ומיפוי',
    'estate.process.step1.desc': 'אנו ממפים את הנכסים, תחומי השיפוט והדינמיקה המשפחתית שלכם כדי להבין את התמונה המשפטית המלאה.',
    'estate.process.step2.title': 'אסטרטגיה ומבנה',
    'estate.process.step2.desc': 'אנו מציעים מבנה (מסמכים ושלבי תיאום) המותאם למטרות ולתחומי השיפוט שלכם.',
    'estate.process.step3.title': 'ניסוח וביצוע',
    'estate.process.step3.desc': 'במידת הצורך, מסמכים מנוסחים דו-לשונית ונחתמים בצורה המתאימה בישראל או בחו"ל כדי לעמוד בדרישות ראייתיות.',
    'estate.process.step4.title': 'שמירה והדרכה',
    'estate.process.step4.desc': 'אנו מספקים הנחיות לאחסון והדרכה למבצעים שלכם לגבי הפעלה עתידית.',
    'estate.process.note': 'היקף ברור, שלבים מוגדרים ודרישות תיעוד נקבעים מראש.',
    'estate.tax.title': 'שיקולי מס לעיזבונות חוצי גבולות',
    'estate.tax.body': 'משטר המס של ישראל בנוגע לירושות והעברות שונה מתחומי שיפוט מערביים רבים. העברת נכסים בין אם בחיים ובין אם לאחר מכן דורשת תזמון קפדני כדי להימנע מאירועי מס מיותרים.',
    'estate.tax.body2': 'אנו מסמנים נקודות מגע מס פוטנציאליות בישראל ומתאמים עם יועצים רלוונטיים בעת הצורך. המטרה שלנו היא להעריך את מבנה העיזבון שלכם כדי להפחית חשיפה שניתן להימנע ממנה ולהגן על ערך המורשת העוברת לדור הבא.',
    'estate.financial.title': 'הסכמי ממון טרום-נישואין ולאחר נישואין',
    'estate.financial.body': 'הסכמים דו-לשוניים באנגלית ובעברית מבטיחים בהירות ואכיפות לזוגות בינלאומיים. כל הסכם מנוסח בדיוק ומאושר על ידי בית משפט או נוטריון, תוך שמירה על בעלות רכושית וסידורים פיננסיים חוצי גבולות.',
    'estate.faq.q1': 'האם אני צריך צוואה נפרדת לנכסים הישראליים שלי?',
    'estate.faq.a1': 'במצבים חוצי גבולות רבים, צוואה ממוקדת ישראל יכולה להפחית חיכוך פרוצדורלי עבור נכסים בישראל. בעוד שצוואות זרות לעתים קרובות ניתנות לאישור כאן, התהליך מורכב יותר ואיטי יותר.',
    'estate.faq.q2': 'האם אני יכול למנות תושב חוץ כמבצע שלי?',
    'estate.faq.a2': 'כן, אם כי הדבר דורש צעדים פרוצדורליים ספציפיים. אנו מדריכים לקוחות לגבי ההשלכות המעשיות של מינוי מבצעים המתגוררים מחוץ לישראל.',
    'estate.faq.q3': 'מה ההבדל בין צו ירושה לצו קיום צוואה?',
    'estate.faq.a3': 'צו קיום צוואה ניתן כאשר המנוח הותיר צוואה תקפה. צו ירושה ניתן כאשר אין צוואה תקפה, ובמקרה זה הנכסים מחולקים לפי דיני הירושה הישראליים.',
    'estate.faq.q4': 'האם ניתן לנהל הליכי פרובייט מרחוק?',
    'estate.faq.a4': 'כן. אנו מטפלים בתהליך מול הרשם והבנקים באמצעות ייפוי כוח, כך שאינכם נדרשים להיות נוכחים בישראל לקבלת הצו.',
    'estate.cta.title': 'תכנון לעתיד',
    'estate.cta.body': 'תכנון משפטי ברור שתומך באינטרסים שלכם היום ולאורך זמן.',
    'estate.cta.button': 'תיאום שיחת ייעוץ',
    'estate.cta.note': 'מענה תוך 1-2 ימי עסקים',

    // Real Estate Page
    'realestate.hero.title': 'מקרקעין ונדל"ן',
    'realestate.hero.subtitle': 'ייעוץ מקיף לקונים בינלאומיים: בדיקת נאותות, אסטרטגיית מס ורישום מאובטח.',
    'realestate.approach.title': 'יותר מעסקה : השקעה אסטרטגית',
    'realestate.approach.body': 'עבור לקוחות רבים רכישת נכס בישראל היא יותר מהשקעה; זהו ציון דרך אישי והחלטה פיננסית לטווח ארוך. המשרד מעניק ליווי משפטי מלא הכולל ביצוע בדיקת נאותות (Due Diligence), סקירה חוזית ורישום בלשכת רישום המקרקעין. התהליך כולו מנוהל בבהירות, משמעת וראיית הנולד במטרה לקדם עסקה בטוחה ושקופה.',
    'realestate.approach.body2': '',
    'realestate.risk.title': 'צמצום חשיפה בשוק מורכב',
    'realestate.risk.intro': 'הדין הישראלי מטיל את חובת הבדיקה על הקונה ("ייזהר הקונה"). הליך בדיקת הנאותות המבוצע בעבור לקוחות המשרד נועד לזהות סיכונים ולצמצם את החשיפה בטרם התחייבות חוזית:',
    'realestate.risk.liabilities.title': 'חבויות נסתרות ושעבודים',
    'realestate.risk.liabilities.desc': 'איתור עיקולים, חובות, משכנתאות או זכויות צד ג הרשומים על הנכס.',
    'realestate.risk.planning.title': 'תכנון ורישוי (Zoning)',
    'realestate.risk.planning.desc': 'אימות התאמת הנכס להיתרי בנייה למניעת חשיפה לקנסות או ירידת ערך עתידית.',
    'realestate.risk.tax.title': 'חשיפת מס',
    'realestate.risk.tax.desc': 'זיהוי סוגיות עיתוי או סיווג תושבות העלולות לגרור חבויות מס מיותרות.',
    'realestate.tax.title': 'שיקולי רגולציה ומיסוי מקרקעין',
    'realestate.tax.body': 'מס הרכישה בישראל הוא דינמי. תושבים המנהלים זיקה בינלאומית כפופים לרוב למדרגות מס שונות בהשוואה לעולים חדשים או לתושבים חוזרים. מיסוי המקרקעין משתנה בהתאם לפרופיל הלקוח (תושב מחוץ לישראל, עולה חדש או תושב חוזר), כאשר לכל סיווג מדרגות מס והטבות ייחודיות.',
    'realestate.tax.body2': 'אנו מיישמים בקיאות רגולטורית לצורך הכנה והגשת דיווחים בלוחות זמנים קשיחים ובדיוק מרבי. המטרה היא מיצוי זכויות חוקיות וניטרול עיכובים בירוקרטיים.',
    'realestate.diligence.title': 'בדיקות נאותות קפדניות (Due Diligence)',
    'realestate.diligence.body': 'עסקה בטוחה מתחילה באימות עובדות. לפני יצירת התחייבות כלשהי אנו מבצעים ביקורת משפטית מקיפה של הנכס הכוללת אימות בעלות בטאבו, בדיקת שעבודים וסקירה תכנונית.',
    'realestate.diligence.body2': 'ניתוח מובנה זה מאפשר ללקוח לקבל החלטה מושכלת המבוססת על עובדות מתועדות ומבטיח שהנכס הנרכש תואם את המצג המשפטי.',
    'realestate.remote.title': 'ייצוג ללקוחות השוהים מחוץ לישראל (רכישה מרחוק)',
    'realestate.remote.body': 'לקוחות המתגוררים מחוץ לישראל יכולים להשלים את תהליך הרכישה מרחוק. הייצוג מבוצע באמצעות ייפוי כוח נוטריוני ספציפי (הנחתם בקונסוליה או בפני נוטריון עם אפוסטיל) המאפשר השלמה יעילה וחוקית של העסקה.',
    'realestate.remote.body2': 'מודל זה מאפשר לנו לנהל את העסקה משלב המשא ומתן ועד לרישום הסופי ומעניק ללקוח יכולת להשלים את הרכישה בביטחון מלא גם כאשר הוא נמצא בזירה הבינלאומית.',
    'realestate.faq.q1': 'מתי צריך להתחיל בתכנון מס?',
    'realestate.faq.a1': 'יש להעריך חבות מס לפני חתימה על כל זיכרון דברים או חוזה. מבנון מוקדם מאפשר לנו להגיש בקשה לפטורים רלוונטיים (כגון הטבות עולים) ולמנוע תשלום יתר.',
    'realestate.faq.q2': 'איך הכספים מוגנים במהלך העסקה?',
    'realestate.faq.a2': 'כספים מוחזקים בדרך כלל בנאמנות (Escrow) ומשוחררים לפי לוח זמנים קפדני המקושר לאבני דרך משפטיות, כגון רישום "הערת אזהרה" לטובתכם.',
    'realestate.faq.q3': 'האם אני יכול לקנות נכס לפני עלייה?',
    'realestate.faq.a3': 'כן. תושבי חוץ יכולים לרכוש נכס. אנו מייעצים כיצד תזמון הרכישה ביחס לתאריך העלייה שלכם משפיע על הטבות מס הרכישה שלכם.',
    'realestate.cta.title': 'אבטחו את ההשקעה שלכם',
    'realestate.cta.body': 'התחילו את הרכישה עם אסטרטגיה משפטית ופיננסית ברורה.',
    'realestate.cta.button': 'תיאום שיחת ייעוץ',

    // Taxation Page
    'tax.hero.title': 'מיסוי ותאימות',
    'tax.hero.subtitle': '',
    'tax.context.title': 'עדשה פיננסית על אסטרטגיה משפטית',
    'tax.context.body': 'מיסוי ותאימות מעצבים האם עסקאות מאושרות, ממומנות ומושלמות. בין אם רוכשים נכס או מעבירים כספים, כל עסקה נושאת השלכות בישראל ופוטנציאלית בחו"ל.',
    'tax.context.body2': 'אנו ניגשים לכל מקרה עם משמעת פיננסית. על ידי שילוב תכנון מס בתהליך המשפטי, אנו ממזערים חיכוך רגולטורי, תומכים בתאימות מלאה ותומכים במעמדכם מול מוסדות פיננסיים.',
    'tax.realEstate.title': 'תכנון מס מקרקעין',
    'tax.realEstate.body': 'הערכת מס היא הצעד הראשון בכל עסקת נכס. מדרגות המס בישראל למס רכישה ומס שבח משתנות בהתאם לתושבות וסטטוס.',
    'tax.realEstate.assessment.title': 'הערכה לפני חוזה',
    'tax.realEstate.assessment.desc': 'חישוב חבויות צפויות ובדיקת זכאות לפטורים רלוונטיים במידת האפשר לפני החתימה.',
    'tax.realEstate.ownership.title': 'תכנון בעלות',
    'tax.realEstate.ownership.desc': 'הערכת אפשרויות בעלות ורישום מוקדם, בהתאמה לסטטוס ולמטרות ארוכות הטווח שלכם.',
    'tax.realEstate.filing.title': 'הגשה ודיווח',
    'tax.realEstate.filing.desc': 'ניהול הגשות לרשות המיסים של ישראל עם תיעוד קפדני להפחתת שגיאות ועיכובים.',
    'tax.banking.title': 'רגולציה בנקאית ומקור כספים',
    'tax.banking.body': 'העברת כספים לישראל או ממנה דורשת הקפדה על רגולציה בנקאית ותקני מניעת הלבנת הון. כל עסקה מנוהלת בתיאום עם מוסדות פיננסיים ישראליים כדי להבטיח תאימות ל-FATCA, דרישות AML והנחיות בנקאות מקומיות.',
    'tax.banking.body2': 'המשרד גם מסייע בהכנה והגשה של הצהרות מס שוטפות, מתאם דיווח ישראלי עם התחייבויות בינלאומיות ואמנות רלוונטיות, מפחית את הסיכון למיסוי כפול ותומך ביציבות פיננסית ומשפטית לטווח ארוך בין תחומי שיפוט.',
    'tax.serve.title': 'האם שירות זה מתאים לכם?',
    'tax.serve.body': 'שירות זה מיועד ללקוחות שמעדיפים תהליך מתועד ושקוף. אנו שותפים למשקיעים בינלאומיים ולקוחות פרטיים שמבינים שתאימות היא המפתח לבטיחות הנכסים.',
    'tax.serve.compliance': 'תאימות קודמת',
    'tax.serve.compliance.desc': 'אנו נותנים ללקוחותינו נקודת מבט ברורה וממוקדת משפטית המבוססת על הבנה מוצקה של צרכיהם.',
    'tax.serve.firstStep': 'צעד ראשון',
    'tax.serve.firstStep.desc': 'ההתקשרות מתחילה עם נקודת מבט ברורה וממוקדת המבוססת על הבנה מוצקה של צרכי הנתונים.',
    'tax.crossBorder.title': 'תיאום עם התחייבויות בינלאומיות',
    'tax.crossBorder.body': 'רשת האמנות של ישראל עשויה להשפיע על אופן הטיפול בהכנסות מסוימות וחובות דיווח, בהתאם לתחום השיפוט שלכם.',
    'tax.crossBorder.body2': 'אנו מסמנים שיקולים פוטנציאליים הקשורים לאמנות ומתאמים עם יועצי המס הזרים שלכם. בעוד שאנו לא מגישים דוחות מס זרים, אנו מבטיחים שהפעולות המשפטיות הישראליות שלכם מתקשרות בבהירות לצוות הגלובלי שלכם לשמירה על עמדת מס עקבית.',
    'tax.olim.title': 'תכנון לעולים חדשים ותושבים חוזרים',
    'tax.olim.body': 'עולים חדשים ותושבים חוזרים עשויים להיות זכאים להקלות מסוימות, כולל הקלת דיווח ל-10 שנים במקרים מסוימים, בכפוף לכללי זכאות. אנו עוזרים לבנות תזמון ותיעוד לתמיכה במעבר תואם למערכת המס הישראלית.',
    'tax.faq.q1': 'האם אני יכול לשלם מס רכישה ישראלי במטבע חוץ?',
    'tax.faq.a1': 'מיסים משולמים בדרך כלל בשקלים (ש"ח). אנו מנחים לקוחות לגבי תזמון, לוגיסטיקת המרה ושוברי תשלום כדי שהכספים יגיעו בזמן ובצורה הנדרשת.',
    'tax.faq.q2': 'האם הבנק הישראלי יקבל את ההעברה שלי אוטומטית?',
    'tax.faq.a2': 'תאימות לעולם אינה אוטומטית. העברות גדולות מפעילות בדיקות. אנו מכינים את תיק "מקור הכספים" מראש כדי להפחית את הסיכון להקפאה או דחייה של כספים.',
    'tax.faq.q3': 'מתי אני הופך לתושב מס בישראל?',
    'tax.faq.a3': 'תושבות נקבעת על ידי מבחן "מרכז החיים", לא רק אזרחות. אנו מייעצים לגבי הקריטריונים המשפטיים וכיצד הנוכחות שלכם בישראל משפיעה על הסטטוס שלכם.',
    'tax.cta.title': 'תאימות אסטרטגית',
    'tax.cta.body': 'התחילו עם בהירות, תוכנית שהופכת אי ודאות למציאות.',
    'tax.cta.button': 'תיאום שיחת ייעוץ',

    // Olim & Returning Residents Page
    'olim.hero.title': 'ייעוץ משפטי לעולים חדשים ותושבים חוזרים',
    'olim.hero.subtitle': 'מסגרת משפטית מובנית למעבר שלכם לישראל: מיצוב מס, רכישת נכס ושילוב נכסים.',
    'olim.context.title': 'פרק חדש מובנה מהיום הראשון',
    'olim.context.body': 'התחלת פרק חדש בישראל מביאה הזדמנות, מורכבות ובחירות משפטיות חשובות. המשרד מספק הדרכה משפטית סבלנית, אישית ומובנית לעולים חדשים ותושבים חוזרים, מבטיח שכל לקוח מרגיש נתמך, מיודע ובטוח מהצעד הראשון ואילך.',
    'olim.context.body2': '',
    'olim.framework.title': 'מסגרת הנחיתה הרכה',
    'olim.framework.planning.title': 'תכנון לפני הגעה',
    'olim.framework.planning.desc': 'תזמון, תיעוד וצעדי מיצוב המותאמים לסטטוס התושבות שלכם למניעת אירועי מס מיותרים.',
    'olim.framework.property.title': 'תיאום רכישת נכס',
    'olim.framework.property.desc': 'בדיקת נאותות ותכנון רכישה המותאמים לשיקולי זכאות ספציפיים ומטרות לטווח ארוך.',
    'olim.framework.banking.title': 'בנקאות והעברות',
    'olim.framework.banking.desc': 'ארגון תיעוד מקור כספים ותמיכה בתהליך סקירת הציות של הבנק ודרישות התיעוד.',
    'olim.framework.peace.title': 'שקט נפשי מלא',
    'olim.framework.peace.desc': 'המשרד מתרגם תהליכים משפטיים מורכבים לצעדים ברורים ומעשיים, מציע שקט נפשי מלא במהלך אחד המעברים המשמעותיים ביותר בחיים. הלקוחות נהנים מתקשורת דו-לשונית, תיאום חוצה גבולות וגישה משפטית ממושמעת שמגנה על האינטרסים שלהם בישראל ובחו"ל.',
    'olim.tax.title': 'מיצוב מס לעולים חדשים ותושבים חוזרים',
    'olim.tax.body': 'עולים (מהגרים חדשים) ותושבים חוזרים (תושב חוזר ותיק) עשויים להיות זכאים להקלות מס ודיווח ספציפיות, בכפוף לכללי זכאות וסיווג. תזמון ותיעוד נכונים קריטיים לאבטחת הטבות אלו.',
    'olim.tax.body2': 'אנו עוזרים ללקוחות למפות את הסטטוס שלהם, לסמן שיקולים רלוונטיים ולתאם עם אנשי מקצוע במס בעת הצורך כדי לתמוך במעבר תואם ולהפחית חשיפה שניתן להימנע ממנה.',
    'olim.clients.title': 'הלקוחות שלנו סומכים עלינו',
    'olim.clients.body': 'עמוד זה מיועד ליחידים ומשפחות העוברים לישראל שמעריכים תהליך מובנה וממוקד תאימות במיוחד כאשר מעורבים נכסים משמעותיים, הכנסה זרה או מוטבים חוצי גבולות.',
    'olim.expect.title': 'מה לצפות',
    'olim.expect.body': 'ההתקשרות מתחילה עם רשימת תיעוד, מיפוי סטטוס (פרופיל תושבות ומס) ומפת דרכים מתואמת עם שלבים מוגדרים.',
    'olim.expect.item1': 'רשימת תיעוד מותאמת למצבכם',
    'olim.expect.item2': 'מיפוי סטטוס תושבות ומס',
    'olim.expect.item3': 'מפת דרכים מתואמת עם שלבים מוגדרים',
    'olim.cta.title': 'התחילו את המעבר על בסיס יציב',
    'olim.cta.body': 'התחילו עם מפת דרכים מובנית ורשימת תיעוד.',
    'olim.cta.button': 'תיאום שיחת ייעוץ',

    // Commercial & Civil Page
    'commercial.hero.title': 'מסחרי ואזרחי',
    'commercial.hero.subtitle': 'הגנה על אינטרסים עסקיים באמצעות חוזים ממושמעים וייצוג בישראל לעניינים חוצי גבולות.',
    'commercial.philosophy.title': 'דיוק לפני סכסוכים',
    'commercial.philosophy.body': 'בהתקשרויות מסחריות, עוצמת העמדה שלכם תלויה בדיוק החוזים שלכם. בין אם מנסחים הסכם שותפות או מנהלים משא ומתן על יציאה, אנו מעריכים כל עניין דרך שלוש עדשות: זכויות חוזיות, חשיפה פיננסית ואכיפה עתידית.',
    'commercial.philosophy.body2': 'המשרד מספק ניתוח משפטי ממושמע בסכסוכים חוזיים ועסקיים. כל עניין נבחן דרך זכויות חוזיות, חשיפה פיננסית וסעדים זמינים. הלקוחות מקבלים הדרכה מובנית שתומכת במשא ומתן, יישוב סכסוכים או הליכים משפטיים רשמיים בעת הצורך.',
    'commercial.services.title': 'שירותי ליבה',
    'commercial.services.contracts.title': 'ניסוח וסקירת חוזים',
    'commercial.services.contracts.desc': 'מבנון הסכמי בעלי מניות, שותפויות, חכירות מסחריות והסכמי שירות עם הגדרות מדויקות.',
    'commercial.services.negotiation.title': 'משא ומתן ומיצוב סיכון',
    'commercial.services.negotiation.desc': 'ייעוץ משפטי אסטרטגי לפני חתימה או במהלך הסלמה לשיפור המנוף שלכם.',
    'commercial.services.dispute.title': 'אסטרטגיית סכסוך ויישוב',
    'commercial.services.dispute.desc': 'צעדים לפני ליטיגציה, מסגרות פשרה וניהול ליטיגציה בעת הצורך.',
    'commercial.services.crossborder.title': 'תיעוד חוצה גבולות',
    'commercial.services.crossborder.desc': 'תיאום עם עורכי דין בחו"ל ולוקליזציה של מסמכים לאכיפה בישראל.',
    'commercial.crossborder.title': 'אינטרסים עסקיים מעבר לגבולות',
    'commercial.crossborder.body': 'אנו מנהלים עניינים מסחריים עם מרכיבים בינלאומיים, משמשים כזרוע המשפטית המקומית עבור המשקיעים והעסקים של לקוחותינו. גישה מובנית זו תומכת בלקוחות המתגוררים בחו"ל אך שומרים על אינטרסים פעילים בישראל.',
    'commercial.crossborder.body2': 'בין אם אוכפים חוזה זר בישראל או מגנים על אינטרסים של בעל מניות מקומי בזמן שהייה בחו"ל, אנו מספקים ייצוג מעשי על הקרקע לעניינים אזרחיים עם מימדים בינלאומיים. הפרקטיקה מתאמת דרישות משפטיות ישראליות עם עורכי דין זרים ואסטרטגיה חוצית גבולות, תומכת בלקוחות המתגוררים בחו"ל או שומרים על קשרים משפטיים ופיננסיים במספר תחומי שיפוט.',
    'commercial.clients.title': 'עם מי אנחנו בדרך כלל עובדים',
    'commercial.clients.body': 'הפרקטיקה המסחרית שלנו מתמקדת בחוזים, הגנה על נכסים וסכסוכים מורכבים, ומשרתת הן עסקים והן יחידים פרטיים. אנו עובדים עם בעלי עסקים, משקיעים, מנהלים ולקוחות פרטיים הזקוקים לייעוץ משפטי שוטף או פתרון אסטרטגי לעניינים מסחריים ואזרחיים משמעותיים.',
    'commercial.cta.title': 'הגנו על האינטרסים המסחריים שלכם',
    'commercial.cta.body': 'התחילו בסקירת חוזה או הערכת אסטרטגיית סכסוך. חסוי ומתועד.',
    'commercial.cta.button': 'תיאום שיחת ייעוץ',
  },
};

// NOTE: Keep a stable Context instance across hot-reloads to avoid "must be used within a Provider" errors.
// This is especially important in development, since we frequently edit translations.
const _global = globalThis as unknown as {
  __mayaLanguageContext?: React.Context<LanguageContextType | undefined>;
};

const LanguageContext =
  _global.__mayaLanguageContext ?? createContext<LanguageContextType | undefined>(undefined);

_global.__mayaLanguageContext = LanguageContext;

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('maya-ziv-lang');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'he';

  useEffect(() => {
    localStorage.setItem('maya-ziv-lang', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t,
    isRTL
  }), [language, t, isRTL]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};