import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.firm': 'The Firm',
    'nav.expertise': 'Expertise',
    'nav.realEstate': 'Real Estate',
    'nav.taxation': 'Tax and Compliance',
    'nav.estate': 'Family and Legacy',
    'nav.olim': 'Olim Hadashim and Returning Residents',
    'nav.commercial': 'Commercial and Civil',
    'nav.insights': 'Insights',
    'nav.globalClients': 'Global Clients',
    'nav.contact': 'Contact',
    'nav.schedule': 'Schedule Consultation',

    // Hero
    'hero.tagline': 'The Future Favors the Prepared',
    'hero.title': 'Attorney & Notary in Tel Aviv',
    'hero.subtitle1': 'Guiding Every Client with Clarity, Insight, and Strategic Confidence',
    'hero.subtitle2': 'Real estate, taxation, and estate planning delivered with clarity, structure, and financial foresight.',
    'hero.cta': 'Schedule a Consultation',

    // Conflict Section
    'conflict.title': 'Clarity Where Details Decide Outcomes',
    'conflict.body': 'For our clients in Israel and overseas, we bring an international perspective shaped by financial training abroad and legal practice in Israel, anchored in clear local insight. This allows us to offer bilingual counsel on domestic and cross border matters that stays close to client needs, builds strong relationships and turns complex situations into focused, confident decisions.',
    'conflict.body2': 'We begin with verification and documentation so decisions are made with facts, not assumptions. Our role is to turn complex requirements into clear, structured decisions that protect your assets.',

    // Guide Section
    'guide.title': 'About the Firm',
    'guide.bio': 'Maya Ziv Law is built on a combined legal and financial perspective, bringing analytical discipline into every matter. The practice serves clients in Israel and overseas with bilingual counsel on domestic and cross border issues, focused on clear structure and long term security for their business, assets, and personal plans.',
    'guide.punchline': 'We think ahead for our clients, using insight and inventive judgment to guide their decisions and anticipate their needs.',
    'guide.cta': 'More About the Firm',

    // Methodology
    'method.title': 'A Structured Process From Verification to Execution',
    'method.subtitle': 'Clients receive a defined process, clear timelines, and rigorous due diligence with confidentiality and precision at every stage.',
    'method.step1.title': 'Verifying Ownership Before You Sign',
    'method.step1.desc': 'Early verification of ownership, liens, planning status, and zoning under Israeli law protects clients purchasing property in Israel or abroad and prevents exposure during real estate due diligence.',
    'method.step2.title': 'The Role of Legal Counsel in Cross Border Transactions',
    'method.step2.desc': 'Accurate drafting, regulatory oversight, and coordinated execution ensure secure cross border property transfers and financial transactions for clients residing in Israel or overseas.',
    'method.step3.title': 'Coordinated Wills for Cross Jurisdiction Estates',
    'method.step3.desc': 'Harmonizing Israeli and foreign wills prevents probate conflicts, ensures enforceability across jurisdictions, and protects families managing assets in multiple countries.',
    'method.step4.title': 'Prenuptial Agreements as Strategic Instruments',
    'method.step4.desc': 'Bilingual marital agreements approved by an Israeli court preserve financial clarity, protect property rights, and prevent future disputes for domestic and international couples.',
    'method.step5.title': 'Early Tax Planning Prevents Unnecessary Exposure',
    'method.step5.desc': 'Structured preparation for purchase tax, capital gains, and reporting duties aligns Israeli obligations with foreign tax regimes, minimizing liability for residents and foreign investors.',
    'method.step6.title': 'Legal Structure Determines Long Term Outcomes',
    'method.step6.desc': 'Ownership form, personal, joint, or corporate, directly shapes taxation, inheritance, privacy, and asset transfer, making early structuring essential for clients managing Israeli or cross border assets.',

    // Practice Areas
    'practice.title': 'Areas of Practice',
    'practice.realEstate.title': 'Real Estate & Investment',
    'practice.realEstate.desc': 'Secure acquisition and tax planning.',
    'practice.taxation.title': 'International Tax & Compliance',
    'practice.taxation.desc': 'Cross border reporting and banking regulation.',
    'practice.estate.title': 'Family & Legacy Planning',
    'practice.estate.desc': 'Wills, inheritance, and intergenerational transfer.',
    'practice.learnMore': 'Learn More',
    'practice.additional.olim': 'Olim & Returning Residents',
    'practice.additional.commercial': 'Commercial & Civil',

    // Insights
    'insights.title': 'Insights',
    'insights.readMore': 'Continue Reading',
    'insights.viewAll': 'View All Insights',
    'insights.article1.title': 'Buying Property in Israel as a Foreign Resident Legal and Tax Essentials',
    'insights.article1.snippet': 'Foreign residents must address unique legal tax and registration requirements when purchasing property in Israel. Clear due diligence and structured planning ensure a compliant and secure transaction.',
    'insights.article2.title': 'Wills and Inheritance in Israel Ensuring Cross Border Validity',
    'insights.article2.snippet': 'Cross border families must align Israeli inheritance procedures with foreign wills and overseas probate rules. Coordinated planning ensures enforceability and prevents unnecessary legal conflicts.',
    'insights.article3.title': 'Buying Property in Israel Essential Legal Checks for Domestic Buyers',
    'insights.article3.snippet': 'Domestic buyers must verify ownership rights planning status and contractual protections before committing to a property purchase. Structured legal checks reduce exposure and support a transparent and compliant transaction.',

    // CTA
    'cta.title': 'Your Interests Deserve Personal Attention',
    'cta.subtitle': 'Each client, each decision, and each detail receives dedicated care and thoughtful attention.',
    'cta.button': 'Send a Confidential Inquiry',

    // Footer
    'footer.brand': 'Attorney & Notary in Tel Aviv',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.disclaimer': 'Disclaimer',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.disclaimerText': 'This website is for informational purposes only and does not constitute legal advice. No attorney-client relationship is formed by use of this site.',
    'footer.copyright': '© 2024 Maya Ziv Law. All rights reserved.',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Begin your journey to legal clarity',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.inquiry': 'Nature of Inquiry',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Thank you for your message. We will respond within 24 48 hours.',
    'contact.inquiry.realEstate': 'Real Estate Transaction',
    'contact.inquiry.taxation': 'International Taxation',
    'contact.inquiry.estate': 'Estate Planning',
    'contact.inquiry.other': 'Other Legal Matter',

    // About Page
    'about.hero.title': 'Legal Counsel Built Through a Financial Lens',
    'about.hero.subtitle': 'A boutique practice bridging the gap between legal strategy and financial discipline for international clients in Israel.',
    'about.philosophy.title': 'A Different Approach to Legal Practice',
    'about.philosophy.body': 'Maya Ziv Law was founded on a simple realization: for international investors and families, a legal contract is never just a document. It is a financial instrument. Operating in Israel requires more than just legal knowledge; it demands the ability to synchronize local bureaucracy with global standards.',
    'about.philosophy.body2': 'The firm was founded to serve both domestic and international clients who require bilingual legal counsel grounded in legal structure, financial insight, and clear communication. With an international academic background and early professional experience in finance and accounting, the practice brings analytical discipline and global professionalism into the Israeli legal environment. Clients benefit from structured, transparent guidance in matters that shape property, family planning, and long term personal decisions.',
    'about.attorney.title': 'Our Values',
    'about.attorney.body': 'Maya Ziv brings a unique perspective to the legal field. With international training and professional experience in finance and accounting, she approaches every case with financial rigor and a strategic view of the outcome.',
    'about.attorney.body2': 'We prioritize prevention and structure. Our work is designed to reduce friction, protect positions early, and prevent disputes before they arise. By anticipating regulatory hurdles and structuring transactions correctly from the outset, the goal is to create stability-ensuring that your legal arrangements serve your financial and personal legacy for the long term.',
    'about.serve.title': 'Who We Serve',
    'about.serve.body': 'Our practice suits clients who prioritize clarity, diligence and lasting results over quick fixes. We partner with international investors, returning residents, and families who require a high level of involvement and a "zero-surprise" policy. We seize opportunities to innovate and grow.',
    'about.serve.body2': 'Whether the matter is commercial or personal, local or cross border, we provide clear legal guidance focused on practical and reliable outcomes.',
    'about.expect.title': 'Why Clients Choose Us',
    'about.expect.intro': 'Engagement with the firm follows a defined, transparent path. We believe that clarity is the antidote to stress, especially when managing affairs remotely.',
    'about.expect.doc.title': 'Documentation-First Approach',
    'about.expect.doc.desc': 'We begin with verification. Decisions are made based on facts and official records, not assumptions.',
    'about.expect.timeline.title': 'Domestic and International Perspective',
    'about.expect.timeline.desc': 'With roots in international education, financial training, and Israeli legal practice, the firm bridges cultural and regulatory differences with precision and foresight.',
    'about.expect.comm.title': 'Clarity and Transparency',
    'about.expect.comm.desc': 'Every engagement begins with defined expectations, structured timelines, and full visibility on costs, creating a stable and predictable client experience.',
    'about.expect.foresight.title': 'Strategic Foresight',
    'about.expect.foresight.desc': 'Matters are evaluated with legal precision, financial reasoning, and long term planning to ensure thoughtful and durable outcomes.',
    'about.cta.title': 'Start a Conversation',
    'about.cta.body': 'A clear plan is the first step to protecting assets and legacy.',
    'about.cta.button': 'Schedule a Consultation',

    // Service Pages - General
    'service.faq': 'Common Questions',

    // Estate Planning Page
    'estate.hero.title': 'Inheritance & Estate Planning',
    'estate.hero.subtitle': 'Legal strategies for cross border wealth transfer, bilingual wills, and Enduring Power of Attorney (Israel).',
    'estate.challenge.title': 'Managing Family Wealth Across Jurisdictions',
    'estate.challenge.body': 'Families with assets in Israel and ties abroad face a unique legal landscape. Israeli inheritance procedures often interact with foreign laws, creating potential conflicts regarding jurisdiction and tax liability. A standard Israeli will is rarely sufficient for a multi national estate.',
    'estate.challenge.body2': 'The firm develops structured estate plans for families in Israel and abroad to prevent disputes, avoid delays in probate, and reduce exposure to double taxation. The process integrates Israeli inheritance law with international legal requirements, supporting clients who reside outside Israel or maintain property in multiple jurisdictions. This coordinated approach ensures that every inheritance is transferred smoothly and according to the client\'s intent.',
    'estate.wills.title': 'Cross Border Wills & Probate Strategy',
    'estate.wills.body': 'The Firm drafts bilingual wills that meet strict Israeli legal standards while referencing your global estate structure. Where appropriate, we structure an Israel-focused will that aligns with an existing foreign will, aiming to reduce friction in Israeli procedures without conflicting with your primary estate plan abroad.',
    'estate.wills.compliance.title': 'Drafting for Compliance',
    'estate.wills.compliance.desc': 'Preparing documents to meet Israeli formal requirements and evidentiary standards.',
    'estate.wills.probate.title': 'Probate Management',
    'estate.wills.probate.desc': 'Representing heirs in obtaining Succession Orders (Yerusha) or Probate Orders (Kiyum Tzava\'a) efficiently.',
    'estate.wills.conflict.title': 'Conflict Reduction',
    'estate.wills.conflict.desc': 'Clear, unambiguous drafting intended to minimize interpretation disputes among beneficiaries.',
    'estate.epa.title': 'Enduring Power of Attorney',
    'estate.epa.body': "An Enduring Power of Attorney (EPA) is a forward looking instrument for retaining control over your future. It allows you to appoint trusted representatives to manage your personal and financial affairs in Israel, should the need arise. Unlike court appointed guardianship, an EPA enables you to define the scope of authority in advance. The firm prepares comprehensive, court compliant documents that preserve your autonomy, intent, and family stability.",
    'estate.epa.body2': '',
    'estate.process.title': 'How We Work: The Planning Process',
    'estate.process.step1.title': 'Discovery & Mapping',
    'estate.process.step1.desc': 'We map your assets, jurisdictions, and family dynamics to understand the full legal picture.',
    'estate.process.step2.title': 'Strategy & Structure',
    'estate.process.step2.desc': 'We propose a structure (documents and coordination steps) aligned with your goals and jurisdictions.',
    'estate.process.step3.title': 'Drafting & Execution',
    'estate.process.step3.desc': 'If needed, documents are drafted bilingually and signed in the appropriate form in Israel or abroad to meet evidentiary requirements.',
    'estate.process.step4.title': 'Safe Keeping & Guidance',
    'estate.process.step4.desc': 'We provide instructions for storage and guidance for your executors on future activation.',
    'estate.process.note': 'Clear scope, defined next steps, and documentation requirements are established from the outset.',
    'estate.tax.title': 'Tax Considerations for Cross Border Estates',
    'estate.tax.body': "Israel's tax regime regarding inheritance and transfers differs from many western jurisdictions. Transferring assets whether during ones lifetime or after requires careful timing to avoid unnecessary tax events.",
    'estate.tax.body2': 'We flag potential tax touchpoints in Israel and coordinate with relevant advisors where needed. Our goal is to assess the structure of your estate to reduce avoidable exposure and protect the value of the legacy passing to the next generation.',
    'estate.financial.title': 'Prenuptial and Postnuptial Agreements',
    'estate.financial.body': 'Bilingual agreements in English and Hebrew ensure clarity and enforceability for international couples. Each agreement is drafted with precision and approved by a court or notary, safeguarding property ownership and financial arrangements across borders.',
    'estate.faq.q1': 'Do I need a separate will for my Israeli assets?',
    'estate.faq.a1': 'In many cross border situations, an Israel focused will can reduce procedural friction for assets in Israel. While foreign wills can often be validated here, the process is procedurally complex and slower.',
    'estate.faq.q2': 'Can I appoint a foreign resident as my executor?',
    'estate.faq.a2': 'Yes, though it requires specific procedural steps. We guide clients on the practical implications of appointing executors who reside outside Israel.',
    'estate.cta.title': 'Plan for the Future',
    'estate.cta.body': 'Clear legal planning that supports your interests today and over time.',
    'estate.cta.button': 'Request a Confidential Consultation',
    'estate.cta.note': 'Response within 1 2 business days',

    // Real Estate Page
    'realestate.hero.title': 'Real Estate',
    'realestate.hero.subtitle': 'Comprehensive counsel for international buyers: Due diligence, tax strategy, and secure registration.',
    'realestate.approach.title': 'More Than a Transaction: A Strategic Investment',
    'realestate.approach.body': 'For many clients, acquiring property in Israel represents more than an investment. It is a personal milestone and a strategic decision with long term financial implications. The firm provides seamless legal guidance throughout the entire acquisition process, including due diligence, contract review, and registration with the Israel Land Registry. Each stage is handled with clarity, discipline, and foresight, ensuring a smooth and secure transaction.',
    'realestate.approach.body2': 'We provide structured legal guidance designed to secure the asset. From preliminary checks to registration with the Israel Land Registry (Tabu), each stage is handled with clarity, discipline, and foresight to ensure a compliant transfer of ownership.',
    'realestate.risk.title': 'Reducing Exposure in a Complex Market',
    'realestate.risk.intro': 'Israeli real estate law places the burden of verification on the buyer. Our due diligence is designed to detect and neutralize risks before you sign:',
    'realestate.risk.liabilities.title': 'Hidden Liabilities',
    'realestate.risk.liabilities.desc': 'Detecting existing liens, debts, or mortgages attached to the title.',
    'realestate.risk.planning.title': 'Planning & Zoning',
    'realestate.risk.planning.desc': 'Verifying that the property is built legally and matches municipal permits to prevent future devaluation or fines.',
    'realestate.risk.tax.title': 'Tax Exposure',
    'realestate.risk.tax.desc': 'Identifying timing issues or residency classifications that could trigger unnecessary tax liabilities.',
    'realestate.tax.title': 'Regulatory and Tax Considerations',
    'realestate.tax.body': 'Purchase tax in Israel is dynamic. Foreign residents are generally subject to different tax brackets compared to new immigrants (Olim) or returning residents.',
    'realestate.tax.body2': 'Purchase tax in Israel applies differently depending on the client profile. Foreign buyers are generally subject to higher tax brackets, while new immigrants and returning residents may be eligible for reduced rates under Israeli law. Drawing on deep familiarity with Israeli regulation and tax requirements, the firm prepares and submits every filing accurately and on time, ensuring that clients benefit from all lawful exemptions and move through the process without administrative setbacks or regulatory delays.',
    'realestate.diligence.title': 'Rigorous Due Diligence',
    'realestate.diligence.body': 'A secure transaction begins with verification. Before any commitment is made, we conduct a comprehensive legal audit of the property. This includes verifying title ownership, checking for encumbrances, and reviewing the planning status.',
    'realestate.diligence.body2': 'This structured analysis allows you to make an informed decision based on documented facts, ensuring the asset you view is the asset you legally acquire.',
    'realestate.remote.title': 'Representation for Clients Abroad',
    'realestate.remote.body': 'Clients residing outside Israel can complete the entire purchase process remotely. Representation is executed through an irrevocable power of attorney signed at an Israeli consulate or before a notary with apostille, enabling secure, compliant, and efficient completion of the transaction.',
    'realestate.remote.body2': 'This enables us to manage the transaction on your behalf, from negotiation to final registration, allowing you to complete the acquisition securely while remaining overseas.',
    'realestate.faq.q1': 'When should tax planning begin?',
    'realestate.faq.a1': 'Tax liability should be assessed before signing any memorandum or contract. Early structuring allows us to apply for relevant exemptions (such as Olim benefits) and prevent overpayment.',
    'realestate.faq.q2': 'How are funds protected during the transaction?',
    'realestate.faq.a2': "Funds are typically held in escrow (trust) and released according to a strict schedule linked to legal milestones, such as the registration of a \"Warning Note\" (He'arat Azhara) in your favor.",
    'realestate.faq.q3': 'Can I buy property before making Aliyah?',
    'realestate.faq.a3': 'Yes. Non-residents can purchase property. We advise on how the timing of the purchase relative to your Aliyah date affects your purchase tax benefits.',
    'realestate.cta.title': 'Secure Your Investment',
    'realestate.cta.body': 'Start your acquisition with a clear legal and financial strategy.',
    'realestate.cta.button': 'Schedule a Consultation',

    // Taxation Page
    'tax.hero.title': 'Tax and Compliance',
    'tax.hero.subtitle': '',
    'tax.context.title': 'A Financial Lens on Legal Strategy',
    'tax.context.body': 'Tax and compliance shape whether transactions are approved, funded, and completed. Whether purchasing property or transferring funds, every transaction carries implications in Israel and potentially abroad.',
    'tax.context.body2': 'We approach every case with financial discipline. By integrating tax planning into the legal process, we minimize regulatory friction, support full compliance, and support your standing with financial institutions.',
    'tax.realEstate.title': 'Real Estate Tax Planning',
    'tax.realEstate.body': "Tax assessment is the first step of any property transaction. Israel's tax brackets for Purchase Tax (Mas Rechisha) and Capital Gains Tax (Mas Shevach) vary based on residency and status.",
    'tax.realEstate.assessment.title': 'Pre Contract Assessment',
    'tax.realEstate.assessment.desc': 'Calculating projected liabilities and checking eligibility for relevant exemptions where applicable before you sign.',
    'tax.realEstate.ownership.title': 'Ownership Planning',
    'tax.realEstate.ownership.desc': 'Evaluate ownership and registration options early, aligned with your status and long term goals.',
    'tax.realEstate.filing.title': 'Filing & Reporting',
    'tax.realEstate.filing.desc': 'Managing submissions to the Israel Tax Authority with careful documentation to reduce errors and delays.',
    'tax.banking.title': 'Banking Regulation & Source of Funds',
    'tax.banking.body': 'Transferring funds to or from Israel requires strict adherence to banking regulations and anti money laundering standards. Every transaction is managed in coordination with Israeli financial institutions to ensure compliance with FATCA, AML requirements, and local banking guidelines.',
    'tax.banking.body2': 'The firm also assists in preparing and submitting ongoing tax declarations, aligning Israeli reporting with international obligations and relevant treaties, reducing the risk of double taxation and supporting long term financial and legal stability across jurisdiction.',
    'tax.serve.title': 'Is This Service Right for You?',
    'tax.serve.body': 'This service is designed for clients who prioritize a documented, transparent process. We partner with international investors and privet clients who understand that compliance is the key to asset safety.',
    'tax.serve.compliance': 'Compliance-First',
    'tax.serve.compliance.desc': 'We give our clients a clear legal focused point of view based on a solid understanding their needs.',
    'tax.serve.firstStep': 'First Step',
    'tax.serve.firstStep.desc': 'Engagement begins with a clear and focused point of view based on a solid understanding of data needs.',
    'tax.crossBorder.title': 'Coordination with International Obligations',
    'tax.crossBorder.body': "Israel's treaty network may affect how certain income and reporting obligations are treated, depending on your jurisdiction.",
    'tax.crossBorder.body2': 'We flag potential treaty related considerations and coordinate with your foreign tax advisors. While we do not file foreign tax returns, we ensure that your Israeli legal actions are communicated clearly to your global team to maintain a consistent tax position.',
    'tax.olim.title': 'Planning for Olim & Returning Residents',
    'tax.olim.body': 'New immigrants and returning residents may be eligible for certain reliefs, including the 10 year reporting relief in certain cases, subject to eligibility rules. We help structure timing and documentation to support a compliant transition into the Israeli tax system.',
    'tax.faq.q1': 'Can I pay Israeli purchase tax in foreign currency?',
    'tax.faq.a1': 'Taxes are generally paid in Shekels (NIS). We guide clients on timing, conversion logistics, and payment vouchers so funds arrive on time and in the required form.',
    'tax.faq.q2': 'Will the Israeli bank automatically accept my transfer?',
    'tax.faq.a2': 'Compliance is never automatic. Large transfers trigger checks. We prepare the "Source of Funds" file in advance to reduce the risk of funds being frozen or rejected.',
    'tax.faq.q3': 'When do I become a tax resident of Israel?',
    'tax.faq.a3': 'Residency is determined by a "Center of Life" test, not just citizenship. We advise on the legal criteria and how your presence in Israel affects your status.',
    'tax.cta.title': 'Strategic Compliance',
    'tax.cta.body': 'Start with clarity, a plan that turns uncertainty into realty.',
    'tax.cta.button': 'Request a Confidential Consultation',

    // Olim & Returning Residents Page
    'olim.hero.title': 'Legal Counsel for Olim & Returning Residents',
    'olim.hero.subtitle': 'A structured legal framework for your transition to Israel: Tax positioning, property acquisition, and asset integration.',
    'olim.context.title': 'A New Chapter Structured from Day One',
    'olim.context.body': 'Beginning a new chapter in Israel brings opportunity, complexity, and important legal choices. The firm provides patient, personal, and structured legal guidance for Olim Hadashim and returning residents, ensuring that each client feels supported, informed, and secure from the first step onward.',
    'olim.context.body2': '',
    'olim.framework.title': 'The Soft Landing Framework',
    'olim.framework.planning.title': 'Pre Arrival Planning',
    'olim.framework.planning.desc': 'Timing, documentation, and positioning steps aligned with your residency status to prevent unnecessary tax events.',
    'olim.framework.property.title': 'Property Acquisition Coordination',
    'olim.framework.property.desc': 'Due diligence and purchase planning aligned with specific eligibility considerations and long term goals.',
    'olim.framework.banking.title': 'Banking & Transfers',
    'olim.framework.banking.desc': "Organizing source of funds documentation and supporting the bank's compliance review process and documentation requirements.",
    'olim.framework.peace.title': 'Complete Peace of Mind',
    'olim.framework.peace.desc': 'The firm translates complex legal processes into clear and practical steps, offering complete peace of mind during one of life\'s most meaningful transitions. Clients benefit from bilingual communication, cross border coordination, and a disciplined legal approach that protects their interests in Israel and abroad.',
    'olim.tax.title': 'Tax Positioning for Olim & Returning Residents',
    'olim.tax.body': 'Olim (new immigrants) and Returning Residents (Toshav Hozer Vatik) may be eligible for specific tax and reporting reliefs, subject to eligibility rules and classification. Correct timing and documentation are critical to securing these benefits.',
    'olim.tax.body2': 'We help clients map their status, flag relevant considerations, and coordinate with tax professionals where needed to support a compliant transition and reduce avoidable exposure.',
    'olim.clients.title': 'Our Clients Trust Us',
    'olim.clients.body': 'This page is designed for individuals and families relocating to Israel who value a structured, compliance first process especially where significant assets, foreign income, or cross border beneficiaries are involved.',
    'olim.expect.title': 'What to Expect',
    'olim.expect.body': 'Engagement begins with a documentation checklist, status mapping (residency & tax profile), and a coordinated roadmap with defined next steps.',
    'olim.expect.item1': 'Documentation checklist tailored to your situation',
    'olim.expect.item2': 'Residency and tax status mapping',
    'olim.expect.item3': 'Coordinated roadmap with defined next steps',
    'olim.cta.title': 'Start Your Transition on Solid Ground',
    'olim.cta.body': 'Begin with a structured roadmap and a documentation checklist.',
    'olim.cta.button': 'Request a Confidential Consultation',

    // Commercial & Civil Page
    'commercial.hero.title': 'Contractual and Business Disputes',
    'commercial.hero.subtitle': 'Protecting business interests through disciplined contracts and Israel based representation for cross border matters.',
    'commercial.philosophy.title': 'Precision Before Disputes',
    'commercial.philosophy.body': 'In commercial engagements, the strength of your position depends on the precision of your contracts. Whether drafting a partnership agreement or negotiating an exit, we evaluate each matter through three lenses: contractual rights, financial exposure, and future enforcement.',
    'commercial.philosophy.body2': 'The firm provides disciplined legal analysis in contractual and business disputes. Each matter is evaluated through contractual rights, financial exposure, and available remedies. Clients receive structured guidance that supports negotiation, dispute resolution, or formal legal proceedings when required.',
    'commercial.services.title': 'Core Services',
    'commercial.services.contracts.title': 'Contract Drafting & Review',
    'commercial.services.contracts.desc': "Structuring shareholders' agreements, partnerships, commercial leases, and service agreements with precise definitions.",
    'commercial.services.negotiation.title': 'Negotiation & Risk Positioning',
    'commercial.services.negotiation.desc': 'Strategic legal counsel before signature or during escalation to improve your leverage.',
    'commercial.services.dispute.title': 'Dispute Strategy & Resolution',
    'commercial.services.dispute.desc': 'Pre litigation steps, settlement frameworks, and litigation management where required.',
    'commercial.services.crossborder.title': 'Cross Border Documentation',
    'commercial.services.crossborder.desc': 'Coordination with overseas counsel and localization of documents for enforcement in Israel.',
    'commercial.crossborder.title': 'Business Interests Across Borders',
    'commercial.crossborder.body': 'We manage commercial matters with international components, acting as the local legal arm for for our clients investors and businesses. This structured approach supports clients who reside abroad but maintain active interests in Israel.',
    'commercial.crossborder.body2': 'Whether enforcing a foreign contract in Israel or protecting a local shareholder interest while overseas, we provide practical on the ground representation for civil matters with international dimensions. The practice coordinates Israeli legal requirements with foreign counsel and cross border strategy, supporting clients who reside abroad or maintain legal and financial ties across multiple jurisdictions.',
    'commercial.clients.title': 'Who We Typically Work With',
    'commercial.clients.body': 'Our commercial practice focuses on contracts, asset protection, and complex disputes, and serves both businesses and private individuals. We work with business owners, investors, executives, and private clients who require ongoing legal counsel or strategic resolution for significant commercial and civil matters,',
    'commercial.cta.title': 'Protect Your Commercial Interests',
    'commercial.cta.body': 'Start with a contract review or a dispute strategy assessment, confidential and documented.',
    'commercial.cta.button': 'Request a Confidential Consultation',
  },
  he: {
    // Navigation
    'nav.firm': 'המשרד',
    'nav.expertise': 'תחומי התמחות',
    'nav.realEstate': 'נדל"ן',
    'nav.taxation': 'מיסוי ותאימות',
    'nav.estate': 'משפחה ומורשת',
    'nav.olim': 'עולים חדשים ותושבים חוזרים',
    'nav.commercial': 'מסחרי ואזרחי',
    'nav.insights': 'מאמרים',
    'nav.globalClients': 'לקוחות בינלאומיים',
    'nav.contact': 'צור קשר',
    'nav.schedule': 'תיאום פגישת ייעוץ',

    // Hero
    'hero.tagline': 'העתיד מעדיף את המוכנים',
    'hero.title': 'מאיה זיו | עורכת דין ונוטריון בתל אביב',
    'hero.subtitle1': 'ליווי משפטי ללקוחות בינלאומיים ומשקיעים: נדל"ן, מיסוי והעברה בין-דורית בראייה אסטרטגית.',
    'hero.subtitle2': 'בהירות במקום אי-ודאות: מפת דרכים משפטית המעניקה לכם ביטחון בקבלת ההחלטות מול בנקים ורשויות.',
    'hero.cta': 'בקשת ייעוץ חסוי',
    'hero.ctaSecondary': 'איך עובד התהליך?',

    // Conflict Section
    'conflict.title': 'החלטות חכמות בעולם מורכב',
    'conflict.body': 'בישראל, הוודאות בעסקה תלויה לא רק בחוזה, אלא ברישום מדויק, תכנון מס מוקדם ותאימות לרגולציה. עבור לקוחות בינלאומיים, האתגר כפול: הפעולות המשפטיות בארץ חייבות להתכתב עם חובות דיווח בחו"ל ומבנים משפחתיים מורכבים.',
    'conflict.body2': 'אנו משלבים ייעוץ דו-לשוני, פרספקטיבה בינלאומית ומשמעת פיננסית. התפקיד שלנו הוא לתרגם דרישות מורכבות להחלטות ברורות, שנועדו להגן על הנכסים שלכם ולצמצם חשיפה.',

    // Guide Section
    'guide.title': 'אסטרטגיה משפטית בראייה פיננסית',
    'guide.bio': 'משרד מאיה זיו הוא משרד בוטיק המגשר בין המשפט הישראלי לסטנדרטים העסקיים של חו"ל. אנו מביאים לשולחן רקע ייחודי בפיננסים וחשבונאות, המאפשר לנו לנתח כל תיק לא רק משפטית, אלא גם דרך שורת הרווח וההשלכות המיסויות.',
    'guide.punchline': '',
    'guide.cta': 'עוד על המשרד',

    // Methodology
    'method.title': 'תהליך עבודה סדור: מאימות ועד ביצוע',
    'method.subtitle': '',
    'method.step1.title': 'אימות נכס וזכויות',
    'method.step1.desc': 'בדיקת נסח טאבו, שעבודים וזכויות בנייה לפני כל התחייבות.',
    'method.step2.title': 'תכנון מס מוקדם',
    'method.step2.desc': 'מיפוי חשיפת מס ובדיקת זכאות לפטורים לפני החתימה.',
    'method.step3.title': 'מבנה בעלות אופטימלי',
    'method.step3.desc': 'התאמת המבנה (יחיד/חברה/נאמנות) לצרכים שלכם.',
    'method.step4.title': 'עסקאות חוצות גבולות',
    'method.step4.desc': 'תיאום מול יועצים בחו"ל למניעת כפל מס.',
    'method.step5.title': 'הגנות משפטיות',
    'method.step5.desc': 'עריכת צוואות, הסכמי ממון וייפוי כוח מתמשך.',
    'method.step6.title': 'ביצוע וניהול כספים',
    'method.step6.desc': 'ניהול אבני דרך בתשלום ובטוחות (בהתאם למתווה העסקה).',

    // Practice Areas
    'practice.title': 'התמחויות הליבה',
    'practice.realEstate.title': 'נדל"ן והשקעות',
    'practice.realEstate.desc': 'ליווי רכישה ומכירה, בדיקות נאותות ורישום זכויות.',
    'practice.taxation.title': 'מיסוי ותאימות',
    'practice.taxation.desc': 'תכנון מס מקרקעין, ייעוץ תושבות ו-Compliance בנקאי.',
    'practice.estate.title': 'הון משפחתי וירושות',
    'practice.estate.desc': 'עריכת צוואות, ייפוי כוח מתמשך וניהול עיזבונות.',
    'practice.learnMore': 'למידע נוסף',
    'practice.additional.olim': 'עולים ותושבים חוזרים',
    'practice.additional.commercial': 'משפט מסחרי ויישוב סכסוכים',

    // Insights
    'insights.title': 'ידע מקצועי למשקיעים',
    'insights.readMore': 'המשך קריאה',
    'insights.viewAll': 'לכל המאמרים',
    'insights.article1.title': 'רכישת נכס בישראל לתושב חוץ',
    'insights.article1.snippet': 'מדריך ליסודות המיסוי, העברת כספים ורישום בטוח בטאבו.',
    'insights.article2.title': 'ירושות וצוואות חוצות גבולות',
    'insights.article2.snippet': 'כיצד להבטיח תוקף משפטי לנכסים בישראל כחלק מעיזבון גלובלי.',
    'insights.article3.title': 'בדיקות לפני קניית דירה',
    'insights.article3.snippet': 'חריגות בנייה, היטל השבחה והגנות משפטיות בחוזה הרכישה.',

    // FAQ Section
    'faq.title': 'שאלות נפוצות',
    'faq.q1': 'האם תושב חוץ חייב להיות נוכח בישראל כדי לרכוש נכס?',
    'faq.a1': 'לא בהכרח. ניתן לנהל את רוב תהליך הרכישה, כולל חתימה על חוזה ורישום בטאבו, באמצעות ייפוי כוח נוטריוני או קונסולרי ספציפי.',
    'faq.q2': 'מהם האתגרים בהעברת כספים מחו"ל לרכישת דירה?',
    'faq.a2': 'בנקים בישראל כפופים לרגולציית איסור הלבנת הון מחמירה. יש להכין מראש תיק "מקור כספים" מסודר ומתועד כדי למנוע עיכובים בקליטת הכספים.',
    'faq.q3': 'האם יש מס ירושה בישראל?',
    'faq.a3': 'נכון להיום, אין מס ירושה בישראל. עם זאת, ייתכנו חבויות מס שבח בעת מכירת נכס שהתקבל בירושה, ולכן תכנון המס הוא קריטי.',

    // CTA
    'cta.title': 'האינטרסים שלכם ראויים לתשומת לב אישית',
    'cta.subtitle': 'כל לקוח וכל פרט בתיק מקבלים מענה מקצועי, דיסקרטי ומחושב.',
    'cta.button': 'בקשת ייעוץ חסוי',
    'cta.buttonSecondary': 'בדיקת התאמה ראשונית',

    // Footer
    'footer.brand': 'עורכת דין ונוטריון בתל אביב',
    'footer.services': 'שירותים',
    'footer.contact': 'צור קשר',
    'footer.legal': 'משפטי',
    'footer.disclaimer': 'הסתייגות',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    'footer.disclaimerText': 'אתר זה הינו למטרות מידע בלבד ואינו מהווה ייעוץ משפטי. אין יצירת יחסי עורך דין-לקוח באמצעות השימוש באתר זה.',
    'footer.copyright': '© 2024 מאיה זיו עו"ד. כל הזכויות שמורות.',

    // Contact Page
    'contact.title': 'צור קשר',
    'contact.subtitle': 'התחילו את המסע שלכם לבהירות משפטית',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'כתובת אימייל',
    'contact.form.phone': 'מספר טלפון',
    'contact.form.inquiry': 'אופי הפנייה',
    'contact.form.message': 'ההודעה שלכם',
    'contact.form.submit': 'שלח הודעה',
    'contact.form.success': 'תודה על פנייתכם. נחזור אליכם תוך 24 48 שעות.',
    'contact.inquiry.realEstate': 'עסקת נדל"ן',
    'contact.inquiry.taxation': 'מיסוי בינלאומי',
    'contact.inquiry.estate': 'ירושות וצוואות',
    'contact.inquiry.other': 'עניין משפטי אחר',

    // About Page
    'about.hero.title': 'אסטרטגיה משפטית בראייה פיננסית',
    'about.hero.subtitle': 'משרד בוטיק שמחבר בין אסטרטגיה משפטית למשמעת פיננסית עבור לקוחות בינלאומיים בישראל.',
    'about.philosophy.title': 'החוזה כמכשיר פיננסי',
    'about.philosophy.body': 'משרד מאיה זיו הוקם מתוך הבנה פשוטה: עבור משקיעים ומשפחות הפועלים חוצה גבולות, חוזה משפטי לעולם אינו רק מסמך – הוא מכשיר פיננסי.',
    'about.philosophy.body2': 'פעילות בישראל דורשת יותר מאשר הכרת החוק; היא דורשת את היכולת לסנכרן בירוקרטיה מקומית עם סטנדרטים גלובליים. אנו מתרגמים דרישות רגולטוריות מורכבות – מסטטוס רישום וחשיפת מס ועד תאימות בנקאית – לתוכנית פעולה ברורה, שמטרתה לבנות יציבות לטווח הארוך.',
    'about.attorney.title': 'מאיה זיו, עורכת דין ונוטריון בתל אביב',
    'about.attorney.body': 'מאיה מביאה לשולחן פרספקטיבה היברידית ייחודית: הכשרה משפטית בינלאומית לצד רקע מקצועי בפיננסים וחשבונאות. שילוב זה מאפשר למשרד לנתח כל תיק לא רק דרך הסעיפים המשפטיים, אלא גם דרך שורת הרווח וההשלכות האסטרטגיות.',
    'about.attorney.body2': 'אנו מלווים משקיעים זרים ולקוחות בינלאומיים בגישה מניעתית. המטרה שלנו היא לזהות את הכשלים הפוטנציאליים עוד בשלב התכנון ולמנוע מחלוקות עתידיות לפני שהן נוצרות.',
    'about.serve.title': 'שותפים לדרך',
    'about.serve.body': 'הפרקטיקה שלנו מותאמת ללקוחות המעדיפים יסודיות על פני מהירות. אנו משתפים פעולה עם משקיעים בינלאומיים, תושבים חוזרים ומשפחות המנהלות הון בין-דורי, הדורשים רמה גבוהה של מעורבות ומדיניות של "אפס הפתעות".',
    'about.serve.body2': 'השירות אינו מתאים למי שמחפש פתרונות בזק ("יהיה בסדר") או קיצורי דרך רגולטוריים.',
    'about.expect.title': 'סטנדרט שירות בינלאומי',
    'about.expect.intro': '',
    'about.expect.doc.title': 'גישה מבוססת תיעוד (Documentation First)',
    'about.expect.doc.desc': 'אנו לא פועלים לפי תחושות בטן אלא על בסיס עובדות. כל החלטה מתחילה באימות נתונים ותיעוד רשמי.',
    'about.expect.timeline.title': 'פרספקטיבה מקומית ובינלאומית',
    'about.expect.timeline.desc': 'הבנה עמוקה של המנטליות והחוק הישראלי, תוך עמידה בסטנדרטים של שירות ודיווח המקובלים בחו"ל.',
    'about.expect.comm.title': 'שקיפות ומסגרת ברורה',
    'about.expect.comm.desc': 'הגדרת היקף העבודה, לוחות הזמנים ושכר הטרחה מראש. אתם תדעו בדיוק מה צפוי לקרות ומתי.',
    'about.expect.foresight.title': 'תקשורת ישירה',
    'about.expect.foresight.desc': 'ליווי אישי וזמין בעברית ובאנגלית, המאפשר לכם לקבל החלטות בביטחון ולנהל את הנכסים גם כשאתם בחו"ל.',
    'about.cta.title': 'התחילו ברגל ימין',
    'about.cta.body': 'תכנון נכון הוא המפתח להגנה על הנכסים והמורשת שלכם.',
    'about.cta.button': 'בקשת ייעוץ חסוי',

    // Service Pages - General
    'service.faq': 'שאלות נפוצות',

    // Estate Planning Page
    'estate.hero.title': 'עריכת צוואות, ירושות והעברה בין-דורית',
    'estate.hero.subtitle': 'תכנון עיזבון אסטרטגי למשפחות בינלאומיות: הרמוניזציה בין הדין הישראלי למערכות משפט זרות.',
    'estate.challenge.title': 'להגן על המורשת המשפחתית',
    'estate.challenge.body': 'משפחות עם נכסים בישראל וזיקות לחו"ל מתמודדות עם "התנגשות דינים": חוקי הירושה בישראל שונים מהותית מאלו בארה"ב או באירופה. הסתמכות על צוואה זרה בלבד עלולה ליצור מורכבות משפטית בעת המימוש.',
    'estate.challenge.body2': 'התפקיד שלנו הוא לסנכרן בין המערכות. אנו בונים מעטפת משפטית שנועדה לצמצם סכסוכים פרשניים, להפחית חשיפת מס עתידית ולסייע בכך שרצונכם יכובד בכל טריטוריה.',
    'estate.wills.title': 'צוואות מותאמות אישית',
    'estate.wills.body': 'אנו עורכים צוואות (כולל צוואות נוטריוניות וצוואות דו-לשוניות) המותאמות לדרישות הראייתיות של הרשם לענייני ירושה בישראל.',
    'estate.wills.concurrent': 'פתרון הצוואות המקבילות (Concurrent Wills): במקרים מתאימים, אנו ממליצים על עריכת "צוואה ישראלית נפרדת" לנכסים בארץ, הפועלת במקביל לצוואה הזרה.',
    'estate.wills.warning': 'הערה חשובה: הליך זה מבוצע בזהירות רבה כדי להבטיח שהצוואה החדשה לא תבטל בטעות (Revoke) את הצוואה הזרה הקיימת, אלא תשלים אותה.',
    'estate.wills.remote': 'ניהול ירושה מרחוק: אנו מייצגים יורשים תושבי חוץ בהליך הוצאת צו קיום צוואה או צו ירושה, ומנהלים את הבירוקרטיה המקומית (בנקים, טאבו) ללא צורך בהגעה פיזית של היורשים לישראל.',
    'estate.wills.compliance.title': 'ניסוח לתאימות',
    'estate.wills.compliance.desc': 'הכנת מסמכים העומדים בדרישות פורמליות ישראליות ובסטנדרטים ראייתיים.',
    'estate.wills.probate.title': 'ניהול ירושה',
    'estate.wills.probate.desc': 'ייצוג יורשים בקבלת צווי ירושה או צווי קיום צוואה ביעילות.',
    'estate.wills.conflict.title': 'הפחתת סכסוכים',
    'estate.wills.conflict.desc': 'ניסוח ברור וחד-משמעי שנועד למזער מחלוקות פרשניות בין מוטבים.',
    'estate.epa.title': 'שליטה מלאה בעתידכם',
    'estate.epa.body': 'ייפוי כוח מתמשך הוא כלי משפטי קריטי המאפשר לכם לקבוע מראש מי ינהל את ענייניכם האישיים, הרפואיים והרכושיים אם לא תוכלו לעשות זאת בעתיד.',
    'estate.epa.body2': 'הגישה שלנו: בניגוד למינוי אפוטרופוס על ידי בית המשפט, מסמך זה משאיר את השליטה בידיים שלכם. אנו עורכים עבורכם מסמך הכולל "הנחיות מקדימות" ברורות למיופי הכוח, כדי למנוע אי-בהירות ברגע האמת.',
    'estate.financial.title': 'ודאות כלכלית במשפחה',
    'estate.financial.body': 'עבור זוגות עם נכסים משמעותיים (לפני נישואין או בפרק ב\'), הסכם ממון הוא כלי לתכנון פיננסי. אנו מנסחים הסכמים צופי פני עתיד ומאשרים אותם בפני נוטריון או בית משפט, כדי להעניק להם תוקף של פסק דין.',
    'estate.tax.title': 'תכנון מס בהעברה בין-דורית',
    'estate.tax.body': 'נכון להיום, אין בישראל מס עיזבון (Estate Tax), אך העברת נכסים עשויה לגרור חבויות מס אחרות (כגון מס שבח במכירה עתידית על ידי היורשים).',
    'estate.tax.body2': 'אנו מנתחים את השלכות המס של ההורשה עוד בשלב הניסוח, ומתאמים עם יועצי המס שלכם בחו"ל כדי למנוע מצבים של "כפל מס" הנובעים משינויי בעלות.',
    'estate.process.title': 'תהליך העבודה',
    'estate.process.step1.title': 'סקירת מסמכים קיימים',
    'estate.process.step1.desc': 'בדיקת צוואות זרות, נאמנויות (Trusts) והסכמי ממון קיימים למניעת סתירות.',
    'estate.process.step2.title': 'מיפוי ואסטרטגיה',
    'estate.process.step2.desc': 'מיפוי נכסים ואזרחויות, ובחירת המנגנון המשפטי הנכון.',
    'estate.process.step3.title': 'עריכה ואימות',
    'estate.process.step3.desc': 'ניסוח מדויק למניעת פרשנות כפולה ואימות חתימה (נוטריוני במידת הצורך).',
    'estate.process.step4.title': 'הפקדה ושמירה',
    'estate.process.step4.desc': 'הנחיות להפקדת הצוואה אצל הרשם לענייני ירושה ושמירת העותקים ליום פקודה.',
    'estate.process.note': '',
    'estate.faq.q1': 'האם הצוואה הזרה שלי תקפה בישראל?',
    'estate.faq.a1': 'באופן עקרוני כן, אך כדי לממשה יש צורך בהליך משפטי של "אישור צוואה לפי דין זר" הכולל חוות דעת מומחה לדין הזר. עריכת צוואה ישראלית נפרדת יכולה לפשט את ההליך ולחסוך עלויות וזמן יקר בבירוקרטיה המקומית.',
    'estate.faq.q2': 'מה ההבדל בין צו ירושה לצו קיום צוואה?',
    'estate.faq.a2': 'צו קיום צוואה ניתן כאשר המנוח הותיר צוואה תקפה. צו ירושה ניתן כאשר אין צוואה, והרכוש מחולק לפי מפתח הקבוע בחוק הירושה הישראלי.',
    'estate.faq.q3': 'האם ניתן לנהל את הליך הירושה כשאני גר בחו"ל?',
    'estate.faq.a3': 'כן. אנו מטפלים בכל ההליך מול הרשם לענייני ירושה והבנקים באמצעות ייפוי כוח, כך שאינכם נדרשים לשהות בישראל לצורך קבלת הצו או שחרור הנכסים.',
    'estate.cta.title': 'להבטיח את העתיד, היום',
    'estate.cta.body': 'תכנון משפטי נכון מעניק שקט נפשי לכם וביטחון ליקרים לכם.',
    'estate.cta.button': 'בקשת ייעוץ חסוי לירושות',
    'estate.cta.note': '',

    // Real Estate Page
    'realestate.hero.title': 'עורכת דין מקרקעין ונדל"ן בתל אביב',
    'realestate.hero.subtitle': 'ליווי משפטי לתושבי חוץ ומשקיעים: בדיקות נאותות, תכנון מס, העברת כספים ורישום זכויות בטוח.',
    'realestate.approach.title': 'להגן על ההון שלכם',
    'realestate.approach.body': 'עבור הלקוחות שלנו, רכישת נכס בישראל היא מהלך הוני משמעותי עם השלכות לטווח ארוך. הגישה שלנו היא אנליטית: אנו מנתחים את העסקה "מהסוף להתחלה" – מהרישום הסופי (בטאבו, ברמ"י או בחברה משכנת) ועד לתכנון המס והעברת הכספים – כדי להבטיח שהנכס שאתם רואים הוא הנכס שאתם מקבלים משפטית.',
    'realestate.risk.title': 'אימות לפני התחייבות',
    'realestate.risk.intro': 'כלל הברזל בישראל הוא "ייזהר הקונה". האחריות לבדוק מוטלת עליכם. אנו מבצעים בדיקות עומק לאיתור סיכונים:',
    'realestate.risk.liabilities.title': 'רישום ובעלות',
    'realestate.risk.liabilities.desc': 'ניתוח המצב המשפטי בטאבו, ברשות מקרקעי ישראל (רמ"י) או בחברה המשכנת, לאיתור עיקולים, שעבודים או זכויות צד ג\'.',
    'realestate.risk.planning.title': 'תכנון ובנייה',
    'realestate.risk.planning.desc': 'השוואת היתר הבנייה למצב בפועל לשלילת חריגות בנייה וצווי הריסה.',
    'realestate.risk.tax.title': 'חשיפה להיטלים',
    'realestate.risk.tax.desc': 'בדיקת חשיפה להיטל השבחה והסדרה חוזית ברורה של חלוקת התשלומים מול המוכר.',
    'realestate.tax.title': 'תכנון אסטרטגי ומיסוי',
    'realestate.tax.body': 'מיסוי המקרקעין בישראל הוא דינמי ותלוי סטטוס (תושב ישראל, תושב חוץ, עולה חדש). אנו בוחנים את זכאותכם לפטורים (כגון מדרגות מס רכישה מופחתות) לפני החתימה.',
    'realestate.tax.body2': 'תיאום בינלאומי: עבור משקיעים עם זיקות לחו"ל, אנו בוחנים את מבנה הרכישה האופטימלי (אדם פרטי, חברה זרה או נאמנות/Trust) ומתאמים את ההשלכות מול יועצי המס שלכם במדינת המקור במידת הצורך.',
    'realestate.banking.title': 'האתגר הבנקאי ומקור הכספים (Source of Funds)',
    'realestate.banking.body': 'העברת הון לישראל הפכה למורכבת עקב רגולציה מחמירה. הבנקים בישראל מפעילים שיקול דעת נרחב ודורשים הוכחת מקור כספים לפני קליטת העברות מחו"ל.',
    'realestate.banking.body2': 'הפתרון שלנו: אנו מכינים איתכם תיק "מקור כספים" מתועד ומסודר מראש, כדי למנוע עיכובים קריטיים בלוח התשלומים ולצמצם את הסיכון לסירוב בנקאי.',
    'realestate.remote.title': 'שליטה מלאה בתהליך',
    'realestate.remote.body': 'אינכם חייבים להיות נוכחים בישראל. התהליך מנוהל באמצעות ייפוי כוח קונסולרי או נוטריוני (עם אפוסטיל).',
    'realestate.remote.body2': 'מנגנון תשלום בטוח (Milestones): כספכם משוחרר למוכר אך ורק כנגד עמידה באבני דרך משפטיות (כגון רישום הערת אזהרה, סילוק משכנתא או המצאת אישורי מיסים), תוך שימוש בנאמנות במידת הצורך להבטחת כספכם.',
    'realestate.requirements.title': 'מוכנים לצאת לדרך? כדי שנוכל לבצע בדיקת התאמה ובדיקת ניגוד עניינים ראשונית, נזדקק ל:',
    'realestate.requirements.item1': 'צילום דרכון / תעודת זהות.',
    'realestate.requirements.item2': 'פרטי הנכס (גוש/חלקה או כתובת).',
    'realestate.requirements.item3': 'טיוטת חוזה (אם התקבלה) או פרטי המתווך/מוכר.',
    'realestate.faq.q1': 'מה ההבדל בין רישום בטאבו לרישום ברמ"י או חברה משכנת?',
    'realestate.faq.a1': 'הטאבו הוא המרשם החזק ביותר ("זכות קניינית"), בעוד שרישום ברמ"י או בחברה משכנת מעיד לרוב על "זכות חוזית". מבחינתכם כקונים, ההבדל משפיע על הביטחונות הנדרשים ועל אופן רישום הזכויות בסוף התהליך. אנו מוודאים שהזכויות בטוחות בכל סוג רישום.',
    'realestate.faq.q2': 'מתי משלמים מס רכישה?',
    'realestate.faq.a2': 'ככלל, החוק דורש תשלום תוך כ-60 יום ממועד החתימה, אך מועדים אלו כפופים לשינויים ולנהלים עדכניים. אנו ננפיק עבורכם את השוברים ונדאג לדיווח המדויק בזמן.',
    'realestate.faq.q3': 'האם הבנק בישראל יקבל את הכסף שלי אוטומטית?',
    'realestate.faq.a3': 'לא. קליטת כספים מחו"ל אינה אוטומטית וכפופה לבדיקות ציות (Compliance). ללא תיק מסודר המוכיח את נתיב הכסף ומיסויו בחו"ל, הבנק עלול לסרב לקבל את הכספים.',
    'realestate.faq.q4': 'האם ניתן לרכוש דירה לפני העלייה לארץ?',
    'realestate.faq.a4': 'כן. ניתן לרכוש נכס כתושב חוץ. במקרים מסוימים, ניתן לשמור על זכאות להטבות מס רכישה של עולה חדש גם אם הרכישה מתבצעת לפני העלייה בפועל (בכפוף לתנאי החוק ולמועד העלייה).',
    'realestate.cta.title': 'התחילו את הרכישה בקרקע יציבה',
    'realestate.cta.body': 'אל תשאירו את העסקה הגדולה בחייכם ליד המקרה.',
    'realestate.cta.button': 'בקשת ייעוץ חסוי לנדל"ן',

    // Taxation Page - V3.0
    'tax.hero.title': 'מיסוי מקרקעין, מיסוי בינלאומי ותאימות',
    'tax.hero.subtitle': 'תכנון אסטרטגי וליווי רגולטורי: מזעור חיכוך בירוקרטי ושמירה על התנהלות תקינה מול הרשויות.',
    'tax.context.title': 'מס ותאימות – חלק בלתי נפרד מהתהליך',
    'tax.context.body': 'כיום, שאלות של מיסוי ורגולציה (Compliance) הן אלו שקובעות את היתכנות העסקה. בין אם מדובר ברכישת נכס או בהעברת כספים מחו"ל – לכל פעולה יש השלכות מיסויות ורגולטוריות.',
    'tax.context.body2': 'אנו ניגשים לכל תיק עם משמעת פיננסית. על ידי שילוב תכנון מס כבר בשלב הראשוני, אנו שואפים למזער חיכוך רגולטורי (Regulatory Friction), להבטיח תאימות מלאה, ולסייע לכם לשמור על מעמד תקין (Standing) מול המוסדות הפיננסיים.',
    'tax.realEstate.title': 'תכנון מוקדם ומניעת עיכובים',
    'tax.realEstate.body': 'הערכת חבות המס היא הצעד הראשון. מדרגות המס בישראל משתנות בהתאם לתושבות ולסטטוס (Residency & Status).',
    'tax.realEstate.assessment.title': 'בדיקת נאותות מיסוית',
    'tax.realEstate.assessment.desc': 'חישוב חבויות צפויות ובדיקת זכאות לפטורים לפני החתימה (Before Signing).',
    'tax.realEstate.ownership.title': 'תכנון מבנה הבעלות',
    'tax.realEstate.ownership.desc': 'בחינת הכדאיות של רכישה על ידי יחיד, חברה או נאמנות.',
    'tax.realEstate.filing.title': 'דיווח ותיעוד',
    'tax.realEstate.filing.desc': 'ניהול הגשות ודיווחים לרשות המיסים בצורה מדויקת ומתועדת, במטרה להפחית טעויות ולמנוע עיכובים מיותרים בקבלת האישורים.',
    'tax.banking.title': 'צולחים את דרישות הבנקים (FATCA & AML)',
    'tax.banking.body': 'העברת הון לישראל מחייבת עמידה בסטנדרטים בינלאומיים (כגון FATCA וכללי איסור הלבנת הון). הבנקים נדרשים להבין את מקור הכספים ולוודא עמידה בהנחיות לפני קליטתם.',
    'tax.banking.body2': 'השירות שלנו: אנו מלווים אתכם בתהליך ה-Compliance הבנקאי. אנו בונים עבורכם תיק "מקור כספים" (Source of Funds) מסודר, המסייע לקציני הציות בבנק להבין את התמונה המלאה ולאשר את הפעילות (בכפוף למדיניות הבנק).',
    'tax.crossBorder.title': 'ראייה גלובלית',
    'tax.crossBorder.body': 'למערכת המס הישראלית יש ממשקים (אמנות מס) עם תחומי שיפוט רבים. הכנסה בישראל עשויה להיות חייבת בדיווח גם במדינת התושבות שלכם.',
    'tax.crossBorder.body2': 'תיאום ולא הגשה: אנו מסמנים את נקודות הממשק הללו ומתאמים את המהלכים מול יועצי המס שלכם בחו"ל.',
    'tax.crossBorder.disclaimer': 'הבהרה: המשרד מטפל בהיבטים המשפטיים והמיסויים בישראל בלבד, ואינו מגיש דוחות מס לרשויות זרות.',
    'tax.serve.title': 'למי השירות מתאים?',
    'tax.serve.body': '',
    'tax.serve.compliance': 'Compliance First',
    'tax.serve.compliance.desc': 'אנו עובדים עם לקוחות המעדיפים תהליך שקוף, מתועד וחוקי ("Clean Money"). השירות אינו מיועד לעקיפת רגולציה.',
    'tax.serve.firstStep': 'הצעד הראשון',
    'tax.serve.firstStep.desc': 'כל תהליך מתחיל בהערכת סיכונים (Risk Assessment) וברשימת מסמכים מסודרת שעליכם להמציא, כדי למנוע הפתעות בהמשך.',
    'tax.faq.q1': 'האם אפשר לשלם מיסים בישראל במטבע חוץ?',
    'tax.faq.a1': 'לא. תשלומי מס לרשות המיסים מבוצעים בשקלים בלבד. אנו מנחים את הלקוחות לגבי תזמון ההמרה והעברת הכספים כדי להבטיח עמידה במועדי התשלום.',
    'tax.faq.q2': 'האם הבנק יקבל את הכסף שלי אוטומטית?',
    'tax.faq.a2': 'קליטת כספים אינה אוטומטית. הבנקים מפעילים נהלי ציות (Compliance) קפדניים. הכנה מוקדמת של תיק "מקור כספים" היא קריטית כדי לאפשר את קליטת הכספים.',
    'tax.faq.q3': 'מתי אני נחשב "תושב ישראל" לצרכי מס?',
    'tax.faq.a3': 'המבחן המרכזי הוא "מרכז החיים" (קשרים משפחתיים, כלכליים וחברתיים). אנו מבצעים ניתוח של הסטטוס שלכם כדי להבין את חובות הדיווח המדויקות בישראל.',
    'tax.cta.title': 'מאי-ודאות לבהירות',
    'tax.cta.body': 'התחילו עם תוכנית פעולה ברורה שתהפוך את המורכבות למציאות יציבה.',
    'tax.cta.button': 'בקשת ייעוץ חסוי למיסוי',

    // Olim & Returning Residents Page
    'olim.hero.title': 'ליווי משפטי לעולים ולתושבים חוזרים',
    'olim.hero.subtitle': 'מסגרת משפטית מובנית למעבר לישראל: מיצוב מס, רכישת נכס והעברת הון בטוחה.',
    'olim.context.title': 'פרק חדש, מתוכנן היטב',
    'olim.context.body': 'מעבר לישראל הוא אירוע מס מורכב. החלטות מוקדמות – לגבי תזמון המעבר, ניתוק התושבות במדינת המקור ומועד מכירת נכסים – מעצבות את החשיפה המיסויית לשנים קדימה.',
    'olim.context.body2': 'אנו מספקים מפת דרכים משפטית שנועדה לצמצם סיכונים ולסייע במיצוי הזכויות המגיעות לכם בחוק, תוך הפחתת החיכוך הבירוקרטי מול הבנקים ורשויות המס.',
    'olim.framework.title': 'הטבות מס ותכנון סטטוס ("חוק מילצ\'ן")',
    'olim.framework.body': 'עולים חדשים ותושבים חוזרים ותיקים עשויים להיות זכאים למעטפת הטבות מס נרחבת, בכפוף לעמידה בתנאי החוק המשתנים.',
    'olim.framework.planning.title': 'הטבות מס ודיווח',
    'olim.framework.planning.desc': 'מסגרת החוק הנוכחית מאפשרת פטור ממס על הכנסות מחו"ל ל-10 שנים. הקלות הדיווח כפופות לשינויי חקיקה ולדרישות שקיפות בינלאומיות (CRS).',
    'olim.framework.property.title': 'שנת הסתגלות',
    'olim.framework.property.desc': 'אנו מסייעים בבחינת הכדאיות והגשת הבקשה לשנת הסתגלות (עד 90 יום מההגעה), המאפשרת דחייה אסטרטגית של קביעת התושבות לצרכי מס.',
    'olim.framework.banking.title': 'תכנון מס יציאה',
    'olim.framework.banking.desc': 'תיאום מול יועצים בחו"ל לגבי עיתוי המעבר כדי להימנע מחיוב במס יציאה במדינת המוצא.',
    'olim.realestate.title': 'הטבות מס רכישה לעולים',
    'olim.realestate.body': 'עולים זכאים למדרגות מס רכישה מופחתות (למשל מדרגות ה-0.5% וה-5%), בכפוף לתקרות השווי המתעדכנות מדי שנה על ידי רשות המיסים.',
    'olim.realestate.body2': 'ברוב המקרים, ניתן לממש זכאות זו החל משנה לפני העלייה ועד 7 שנים אחריה. אנו מייעצים לגבי התזמון הנכון – האם לרכוש כתושב חוץ או להמתין לתעודה – בהתאם לנתוני העסקה הספציפית.',
    'olim.banking.title': 'הכנת הקרקע להעברת כספים',
    'olim.banking.body': 'הבנקים בישראל פועלים תחת משטר דיווח בינלאומי (FATCA האמריקאי ו-CRS האירופי/גלובלי). משמעות הדבר היא שהבנק חייב לאמת את מקור הכספים ודיווחם לפני קליטתם.',
    'olim.banking.body2': 'אנו בונים איתכם תיק "מקור כספים" (Source of Funds) מתועד עוד לפני ההגעה, כדי לספק למחלקת הציות בבנק את הביטחון הנדרש ולאפשר את העברת הכספים.',
    'olim.expect.title': 'מתחילים בשקיפות מלאה',
    'olim.expect.body': 'כדי לבנות אסטרטגיה נכונה, הפגישה הראשונה מוקדשת למיפוי ותיאום ציפיות:',
    'olim.expect.item1': 'מיפוי סטטוס: בחינת "מרכז החיים" וזכאות לסטטוס עולה/תושב חוזר.',
    'olim.expect.item2': 'מסגרת עבודה: הגדרת היקף הטיפול המשפטי, לוחות הזמנים ושכר הטרחה מראש (מדיניות אפס הפתעות).',
    'olim.expect.item3': 'רשימת תיעוד: אפיון המסמכים הנדרשים לבנקים ולרשויות.',
    'olim.faq.title': 'שאלות נפוצות',
    'olim.faq.q1': 'מה צריך להכין לפגישה הראשונה?',
    'olim.faq.a1': 'מומלץ להגיע עם לוח זמנים משוער למעבר, פירוט כללי של הנכסים/ההון שברצונכם להעביר לישראל, ומידע על הסטטוס האזרחי שלכם (האם גרתם בישראל בעבר? כמה שנים?).',
    'olim.faq.q2': 'האם אתם מגישים את דוחות המס שלי בחו"ל?',
    'olim.faq.a2': 'לא. המשרד מתמקד בייצוג משפטי ומיסויי בישראל בלבד. אנו מתאמים את המהלכים מול רואי החשבון שלכם בחו"ל כדי למנוע כפל מס, אך איננו מבצעים את הדיווח הזר בפועל.',
    'olim.faq.q3': 'מתי כדאי להתחיל בתהליך?',
    'olim.faq.a3': 'האידיאל הוא להתחיל בתכנון כ-6 עד 12 חודשים לפני המעבר הפיזי, במיוחד אם יש צורך למכור נכסים בחו"ל או לתכנן את ניתוק התושבות.',
    'olim.cta.title': 'התחילו ברגל ימין',
    'olim.cta.body': 'תכנון מוקדם הוא המפתח למעבר חלק ולמיצוי זכויות כלכליות.',
    'olim.cta.button': 'בקשת ייעוץ חסוי לעולים',
    'olim.cta.button2': 'בדיקת זכאות ראשונית',

    // Commercial Page - V3.0
    'commercial.hero.title': 'עורכת דין מסחרית ויישוב סכסוכים בתל אביב',
    'commercial.hero.subtitle': 'הגנה על אינטרסים עסקיים: ניסוח חוזים, אסטרטגיית סכסוכים וייצוג חברות ומשקיעים זרים בישראל.',
    'commercial.philosophy.title': 'מניעה לפני ליטיגציה',
    'commercial.philosophy.body': 'בעולם העסקי, איכות החוזה נמדדת ברגע המשבר. חוזה חזק הוא כזה שצופה את התרחישים הבעייתיים – מבוי סתום בין שותפים, הפרה או יציאה מההסכם – ומגדיר להם פתרון מראש.',
    'commercial.philosophy.body2': 'אנו עובדים במתודולוגיה של מיפוי חשיפה: זיהוי נקודות התורפה המסחריות וסגירתן בחוזה, כדי למזער את הסיכון להגיע לבית המשפט ולחסוך בעלויות התדיינות יקרות.',
    'commercial.contracts.title': 'הבסיס ליציבות עסקית',
    'commercial.contracts.body': 'אנו מלווים יזמים ומשקיעים בניסוח וניהול משא ומתן על הסכמי הליבה של העסק, תוך דגש על מנגנונים מעשיים:',
    'commercial.contracts.founders': 'הסכמי מייסדים ושותפות: הגדרה ברורה של מנגנוני היפרדות (Buy-Sell), זכויות וטו והגנה מפני דילול.',
    'commercial.contracts.localization': 'לוקליזציה של חוזים: התאמת חוזים בינלאומיים לדין הישראלי, כדי להבטיח שהם אכיפים בבתי המשפט בארץ.',
    'commercial.contracts.transactions': 'עסקאות והשקעות: ליווי הסכמי השקעה, רכישת פעילות וחוזים מול ספקים אסטרטגיים.',
    'commercial.dispute.title': 'ניהול משברים וייצוג אסטרטגי',
    'commercial.dispute.body': 'כאשר מתגלע סכסוך, אנו בוחנים אותו דרך "עדשה פיננסית": מהי תוחלת התביעה מול העלות והסיכון?',
    'commercial.dispute.body2': 'אנו מייצגים לקוחות בסכסוכים עסקיים ואזרחיים מורכבים (ליטיגציה). אנו פועלים בנחישות למיצוי זכויותיכם, אך תמיד בוחנים חלופות של פשרה או גישור אם הן משרתות טוב יותר את האינטרס הכלכלי שלכם.',
    'commercial.crossborder.title': 'הזרוע המשפטית שלכם בישראל',
    'commercial.crossborder.body': 'עבור חברות ומשקיעים זרים, ניהול אינטרסים בישראל מרחוק הוא אתגר. אנו משמשים כנציגים המקומיים שלכם: החל מאכיפת חוזים מול גורמים ישראלים ועד ייצוג מול רשויות.',
    'commercial.crossborder.body2': 'אנו מספקים עדכונים מסודרים ומתועדים באנגלית, כך שתישארו בשליטה מלאה על הנעשה בארץ ללא פערי שפה או תרבות.',
    'commercial.deliverables.title': 'חבילת הליווי',
    'commercial.deliverables.item1': 'בדיקה, ניסוח וניהול משא ומתן על חוזים.',
    'commercial.deliverables.item2': 'בניית אסטרטגיה לניהול סכסוך (לפני ובמהלך תביעה).',
    'commercial.deliverables.item3': 'התאמת מסמכים משפטיים מחו"ל לדין הישראלי.',
    'commercial.clients.title': 'מיקוד עסקי',
    'commercial.clients.body': 'הפרקטיקה המסחרית שלנו מתמקדת בתיקים בעלי פרופיל גבוה ומורכבות משפטית. השירות מיועד לבעלי עסקים, משקיעים ומנהלי עיזבונות.',
    'commercial.clients.filter': 'המשרד אינו מטפל בתביעות קטנות או בנושאים אדמיניסטרטיביים פשוטים.',
    'commercial.faq.title': 'שאלות נפוצות',
    'commercial.faq.q1': 'האם ניתן לאכוף פסק דין זר בישראל?',
    'commercial.faq.a1': 'כן, כפוף לעמידה בתנאי "חוק אכיפת פסקי חוץ" (למשל, סמכות שיפוט והדדיות בין המדינות). אנו בוחנים את פסק הדין ומייעצים לגבי סיכויי האכיפה וההליך הנדרש בישראל.',
    'commercial.faq.q2': 'איך מתמודדים עם שותף שרוצה לפרק את העסק?',
    'commercial.faq.a2': 'הפתרון תלוי בהסכם המייסדים. אם קיים מנגנון היפרדות מוגדר (כגון BMBY), פועלים לפיו. בהיעדר הסכם, המצב מורכב ודורש אסטרטגיה משפטית מהירה להגנה על שווי האחזקות.',
    'commercial.faq.q3': 'האם אתם עובדים בריטיינר או לפי שעה?',
    'commercial.faq.a3': 'אנו מתאימים את המודל לצרכי הלקוח. בעסקאות נקודתיות (כגון חוזה) אנו מעדיפים שכר טרחה קבוע וידוע מראש. בניהול סכסוכים או ליווי שוטף, העבודה היא לרוב לפי שעות או ריטיינר.',
    'commercial.cta.title': 'הגנו על האינטרסים העסקיים שלכם',
    'commercial.cta.body': 'התחילו עם בדיקת חוזה או הערכת אסטרטגיה לניהול הסכסוך.',
    'commercial.cta.button': 'בקשת ייעוץ חסוי למסחרי',
  },
};

// NOTE: Keep a stable Context instance across hot-reloads to avoid "must be used within a Provider" errors.
// This is especially important in development, since we frequently edit translations.
const _global = globalThis as unknown as {
  __mayaLanguageContext?: React.Context<LanguageContextType | undefined>;
};

const LanguageContext =
  _global.__mayaLanguageContext ?? createContext<LanguageContextType | undefined>(undefined);

_global.__mayaLanguageContext = LanguageContext;

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('maya-ziv-lang');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'he';

  useEffect(() => {
    localStorage.setItem('maya-ziv-lang', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};