import React, { createContext, useContext, useState, useEffect, useCallback, useMemo, ReactNode } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.firm': 'About the Firm',
    'nav.about': 'About',
    'nav.expertise': 'Expertise',
    'nav.realEstate': 'Real Estate',
    'nav.taxation': 'Tax and Compliance',
    'nav.estate': 'Family and Legacy',
    'nav.olim': 'Olim Hadashim and Returning Residents',
    'nav.commercial': 'Commercial and Civil',
    'nav.insights': 'Insights',
    'nav.globalClients': 'Global Clients',
    'nav.contact': 'Contact',
    'nav.schedule': 'Schedule Consultation',

    // Hero
    'hero.tagline': 'Clarity in a Changing World',
    'hero.title': 'Attorney in Israel',
    'hero.subtitle1': 'Premier legal counsel must be as unique as the clients it serves. At Maya Ziv Law, every matter receives the personal focus it deserves and the depth and reach that serious work demands.',
    'hero.subtitle2': '',

    // Guide Section
    'guide.title': 'About Maya Ziv Law',
    'guide.bio': 'The firm operates as a dedicated partner to each client, creating original solutions for the most complex domestic and cross border matters. The firm is based in Israel.',
    'guide.punchline': 'We think ahead for our clients, using insight and judgment to anticipate their needs.',
    'guide.cta': 'More About the Firm',
    'parallax.quote': 'The details that seem technical are often the ones that determine the outcome.',

    // Methodology
    'method.step1.title': 'Our Clients',
    'method.step1.desc': 'Private individuals, families, and businesses who bring us their most important matters, knowing they will receive the personal attention their situation deserves. Some are based in Israel. Others come from across the world.',
    'method.step2.title': 'No Detail Overlooked',
    'method.step2.desc': 'We bring insight and judgment to every situation. Whether navigating a real estate acquisition, managing cross border compliance, or structuring an estate, every matter is handled with the attention it deserves.',
    'method.step3.title': 'Fully Informed, Always',
    'method.step3.desc': 'Clients know exactly where their matter stands at every stage. What has been resolved, what is in progress, what requires their input.',
    'method.step4.title': 'Full Coverage, One Relationship',
    'method.step4.desc': 'The expansive reach and technical depth of a premier practice, with the individual attention each situation requires. Through a network of trusted advisors across jurisdictions, coordinated through a single point of contact. Counsel available in Hebrew and English.',
    'method.step5.title': 'Deep Understanding',
    'method.step5.desc': 'Every matter begins with listening. We take the time to understand what clients are truly trying to achieve, not just the immediate legal question.',
    'method.step6.title': 'Areas of Practice',
    'method.step6.desc': 'We specialize in real estate transactions and due diligence. Taxation, cross border compliance. Estate planning, wills, and succession. Commercial agreements and civil disputes. Both domestic and international.',

    // Practice Areas
    'practice.title': 'Areas of Practice',
    'practice.realEstate.title': 'Real Estate and Investment',
    'practice.realEstate.desc': 'Secure acquisition and tax planning.',
    'practice.taxation.title': 'International Tax and Compliance',
    'practice.taxation.desc': 'Cross border reporting and banking regulation.',
    'practice.estate.title': 'Family and Legacy Planning',
    'practice.estate.desc': 'Wills, inheritance, and intergenerational transfer.',
    'practice.learnMore': 'Learn More',
    'practice.olim.desc': 'Legal guidance for new immigrants and returning residents.',
    'practice.commercial.desc': 'Contracts, risk allocation, and business advisory.',
    'practice.additional.olim': 'Olim Hadashim and Returning Residents',
    'practice.additional.commercial': 'Commercial and Civil',

    // Insights
    'insights.title': 'Insights',
    'insights.readMore': 'Continue Reading',
    'insights.viewAll': 'View All Insights',
    'insights.hero.title': 'Legal Insights and Strategic Commentary',
    'insights.hero.subtitle': 'Practical guidance on Israeli real estate, cross border taxation, compliance, and legacy planning.',
    'insights.philosophy.title': 'Clarity for Cross Border Decisions',
    'insights.philosophy.body': 'Our insights are written to be practical. Structured explanations, key considerations, and common pitfalls to flag early. The goal is to help you ask better questions and understand the legal roadmap before committing to a transaction.',
    'article.notFound': 'Article Not Found',
    'article.backToInsights': 'Back to Insights',
    'article.readMore': 'Want to Read More?',
    'article.readMoreBody': 'Return to our insights page for more articles and professional content.',
    'article.allArticles': 'All Articles',
    'insights.article1.title': 'Buying Property in Israel as a Foreign Resident: Legal and Tax Essentials',
    'insights.article1.snippet': 'Foreign residents must address unique legal, tax, and registration requirements when purchasing property in Israel. Clear due diligence and structured planning ensure a compliant and secure transaction.',
    'insights.article2.title': 'Wills and Inheritance in Israel: Ensuring Cross Border Validity',
    'insights.article2.snippet': 'Cross border families must align Israeli inheritance procedures with foreign wills and overseas probate rules. Coordinated planning ensures enforceability and prevents unnecessary legal conflicts.',
    'insights.article3.title': 'Buying Property in Israel: Essential Legal Checks for Domestic Buyers',
    'insights.article3.snippet': 'Domestic buyers must verify ownership rights, planning status, and contractual protections before committing to a property purchase. Structured legal checks reduce exposure and support a transparent and compliant transaction.',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'When should I start tax planning?',
    'faq.a1': 'Tax planning on an Israeli property transaction must begin before any document is signed, ideally at the negotiation stage. The applicable Purchase Tax rate depends on your residency status, whether this is your first property in Israel, and the timing of the transaction relative to any Aliyah or relocation. Getting this wrong after the fact is expensive and in some cases irreversible. We assess your tax position at the outset, as part of the transaction structure.',
    'faq.q2': 'How are buyer funds protected during the transaction?',
    'faq.a2': 'Buyer funds in Israeli property transactions are released to the seller in stages, tied to specific legal milestones rather than as a lump sum. At each stage, a corresponding security interest is registered in the buyer\'s favor at the Land Registry, known as a Hearat Azhara or warning note. This mechanism ensures that if the transaction does not complete, the buyer\'s financial exposure is limited. The payment schedule and its linkage to milestones is one of the most important elements of the purchase contract and is negotiated before signing.',
    'faq.q3': 'Can I purchase property before making Aliyah?',
    'faq.a3': 'Yes. Non residents can purchase property in Israel. The more important question is the timing of the purchase relative to your Aliyah date, as this affects your Purchase Tax eligibility. In some cases purchasing before making Aliyah preserves certain benefits. In others, waiting is the better structure. This analysis is specific to each client\'s situation and should be done before any commitment is made.',
    'faq.q4': 'Can I pay Israeli purchase tax in foreign currency?',
    'faq.a4': 'No. Purchase Tax payments to the Israeli Tax Authority are made in New Israeli Shekels. For clients transferring funds from abroad, this requires coordinating currency conversion, timing the transfer to limit exchange rate exposure, and ensuring the receiving Israeli bank accepts the funds. We manage this process as part of the transaction.',
    'faq.q5': 'Will the Israeli bank automatically accept my transfer?',
    'faq.a5': 'No. Israeli banks operate under strict anti money laundering and compliance requirements. An international transfer that arrives without prior documentation establishing the source of funds, the purpose of the transfer, and the underlying transaction is likely to be held or returned. Preparing the source of funds file in advance and coordinating with the bank before the transfer is initiated is standard practice on any cross border transaction. We handle this as part of our representation.',
    'faq.q6': 'When do I become a tax resident of Israel?',
    'faq.a6': 'Israeli tax residency is determined by the center of life test, a factual assessment that includes physical presence of over 183 days in a tax year or over 425 days across three consecutive years, as well as the location of your economic and personal ties. It is not determined by citizenship or Aliyah status alone. The consequences of becoming an Israeli tax resident are significant and affect reporting obligations on worldwide income. We advise on residency classification as part of pre arrival planning.',
    'faq.q7': 'Is a foreign will valid in Israel?',
    'faq.a7': 'A foreign will can be recognized in Israel but it must go through a probate process that includes expert opinions on the relevant foreign law. This process adds time, cost, and uncertainty, particularly when the estate includes Israeli real estate. The more reliable approach is to draft a separate Israeli will that addresses Israeli assets specifically, coordinated with your foreign will so that the two instruments do not conflict. We advise on both the drafting and the coordination across jurisdictions.',
    'faq.q8': 'Can I appoint an estate administrator residing outside Israel?',
    'faq.a8': 'Yes, though Israeli courts may require additional procedural steps including the provision of guarantees before appointing a non resident administrator. The practical implications depend on the composition of the estate and the complexity of the proceedings. We advise on executor selection as part of the estate planning process, with attention to the realistic demands of the role and the client\'s family and asset structure.',
    'faq.q9': 'What is the difference between an inheritance order and a probate order?',
    'faq.a9': 'A Probate Order (Kiyum Tzava\'a) is issued by the Israeli Registrar of Inheritance when the deceased left a valid will. It confirms the will\'s validity and authorizes its execution. An Inheritance Order (Tzav Yerusha) is issued when there is no valid will, and estate distribution then follows the statutory provisions of Israel\'s Succession Law. In cross border estates, coordinating the Israeli process with foreign proceedings is essential to avoid conflicts between jurisdictions.',

    // CTA
    'cta.title': 'When the Matter Requires Both Legal and Financial Judgment',
    'cta.subtitle': 'Clients in Israel and abroad turn to Maya Ziv Law for transactions where precision matters. Inquiries welcome in Hebrew and English.',
    'cta.button': 'Schedule a Consultation',
    'cta.buttonSecondary': 'Initial Fit Assessment',

    // Footer
    'footer.brand': 'Attorney in Israel',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.disclaimer': 'Disclaimer',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.disclaimerText': 'This website is for informational purposes only and does not constitute legal advice. No attorney client relationship is formed by use of this site.',
    'footer.copyright': '© 2026 Maya Ziv Law. All rights reserved.',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Begin your journey to legal clarity',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.inquiry': 'Nature of Inquiry',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Thank you for your message. We will respond within 24 to 48 hours.',
    'contact.inquiry.realEstate': 'Real Estate Transaction',
    'contact.inquiry.taxation': 'International Taxation',
    'contact.inquiry.estate': 'Estate Planning',
    'contact.inquiry.other': 'Other Legal Matter',

    // About Page
    'about.hero.title': 'About Maya Ziv Law',
    'about.mainBody': 'Our clients bring us matters that require both legal precision and judgment. We treat each one as a unique situation with its own stakes, its own complexity, and its own required outcome.',
    'about.cta.title': 'Tell Us About Your Matter',
    'about.cta.body': 'From the first conversation, clients know exactly what their matter involves and what to expect next.',
    'about.cta.button': 'Get in Touch',

    // Service Pages - General
    'service.faq': 'Common Questions',

    // Estate Planning Page
    'estate.hero.title': 'Protecting Your Family Across Borders',
    'estate.hero.subtitle': 'Structured legal planning for cross border wealth transfer, bilingual wills, and Enduring Power of Attorney under Israeli law.',
    'estate.challenge.title': 'Managing Family Wealth Across Jurisdictions',
    'estate.challenge.body': 'Families with assets in Israel and ties to other countries face a specific challenge ensuring that wealth passes to the next generation efficiently, in accordance with your wishes, and without unnecessary tax events or procedural delays. Israeli inheritance law operates under its own rules of formality, jurisdiction, and procedure. When foreign wills, foreign beneficiaries, or assets in multiple countries are involved, the complexity increases significantly. We develop structured estate plans that integrate Israeli inheritance law with relevant foreign legal frameworks. The objective is to prevent disputes, minimize probate delays, and reduce exposure to double taxation or conflicting succession orders.',
    'estate.challenge.body2': '',
    'estate.wills.title': 'Wills, Succession, and Cross Border Coordination',
    'estate.wills.body': 'We prepare Israel specific wills and comprehensive estate plans for clients who hold assets or maintain family connections across jurisdictions. Each document is drafted to meet Israeli formal and evidentiary requirements while coordinating with any existing foreign testamentary instruments.',
    'estate.wills.compliance.title': 'Drafting for Compliance',
    'estate.wills.compliance.desc': 'Preparing wills that satisfy the formal requirements of Israeli law, including witness provisions and language considerations for bilingual instruments.',
    'estate.wills.probate.title': 'Probate and Succession Orders',
    'estate.wills.probate.desc': 'Representing heirs in obtaining a Probate Order (Kiyum Tzava\'a) where a valid will exists, or a Succession Order (Tzvav Yerusha) where no will was left, through the Registrar of Inheritance or the Family Court.',
    'estate.wills.conflict.title': 'Minimizing Conflict',
    'estate.wills.conflict.desc': 'Clear, unambiguous drafting that reduces the scope for interpretation disputes among beneficiaries. Where family dynamics are sensitive, we structure instruments to limit the grounds for challenge.',
    'estate.epa.title': 'Enduring Power of Attorney',
    'estate.epa.body': 'An Enduring Power of Attorney (EPA) is a forward looking legal instrument that allows you to designate trusted individuals to manage your personal, medical, and financial affairs in Israel should you become unable to do so. Unlike court appointed guardianship, an EPA enables you to define the scope of authority, the identity of your representatives, and the conditions under which the instrument takes effect.',
    'estate.epa.body2': 'We prepare comprehensive, court compliant EPA documents that preserve your autonomy, reflect your intentions, and provide your family with clear instructions for a situation that most people prefer to plan for in advance rather than leave to judicial discretion.',
    'estate.process.title': 'How We Work',
    'estate.process.step1.title': 'Discovery and Mapping',
    'estate.process.step1.desc': 'We identify and map your assets, jurisdictions, beneficiaries, and family dynamics to understand the full legal and financial picture.',
    'estate.process.step2.title': 'Strategy and Structure',
    'estate.process.step2.desc': 'We propose a structure consisting of documents and coordination steps aligned with your objectives and the requirements of each jurisdiction involved.',
    'estate.process.step3.title': 'Drafting and Execution',
    'estate.process.step3.desc': 'Documents are drafted bilingually where required and executed in the form prescribed by Israeli law. For clients abroad, execution can take place at a consulate or before a notary with apostille.',
    'estate.process.step4.title': 'Safekeeping and Guidance',
    'estate.process.step4.desc': 'We provide instructions for secure storage and practical guidance for executors on future activation, so that the plan works when it is needed.',
    'estate.process.note': 'Clear scope, defined next steps, and documentation requirements are established from the outset.',
    'estate.tax.title': 'Tax Considerations for Cross Border Estates',
    'estate.tax.body': 'Israel\'s tax treatment of inheritance and lifetime transfers differs from that of many Western jurisdictions. Transferring assets, whether during one\'s lifetime or after death, may trigger tax events that vary depending on the nature of the asset, the residency of the parties, and the timing of the transfer.',
    'estate.tax.body2': 'We identify potential tax exposure at the outset and coordinate with relevant advisors in other jurisdictions where needed. The objective is to structure the estate in a way that reduces avoidable liability and protects the value of the legacy passing to the next generation.',
    'estate.financial.title': 'Prenuptial and Postnuptial Agreements',
    'estate.financial.body': 'For domestic and international couples, we prepare bilingual agreements in English and Hebrew that address property ownership, financial arrangements, and asset protection across borders. Each agreement is drafted with precision and, where required, approved by a court or notary to ensure enforceability under Israeli law.',
    'estate.faq.q1': 'Is a foreign will valid in Israel?',
    'estate.faq.a1': 'A foreign will can be recognized in Israel but it must go through a probate process that includes expert opinions on the relevant foreign law. This process adds time, cost, and uncertainty, particularly when the estate includes Israeli real estate. The more reliable approach is to draft a separate Israeli will that addresses Israeli assets specifically, coordinated with your foreign will so that the two instruments do not conflict. We advise on both the drafting and the coordination across jurisdictions.',
    'estate.faq.q2': 'Can I appoint an estate administrator residing outside Israel?',
    'estate.faq.a2': 'Yes, though Israeli courts may require additional procedural steps including the provision of guarantees before appointing a non resident administrator. The practical implications depend on the composition of the estate and the complexity of the proceedings. We advise on executor selection as part of the estate planning process, with attention to the realistic demands of the role and the client\'s family and asset structure.',
    'estate.faq.q3': 'What is the difference between an inheritance order and a probate order?',
    'estate.faq.a3': 'A probate order, Kiyum Tzava\'a, is issued by the Israeli Registrar of Inheritance when the deceased left a valid will. It confirms the will\'s validity and authorizes its execution. An inheritance order, Tzav Yerusha, is issued when there is no valid will, and estate distribution then follows the statutory provisions of Israel\'s Succession Law. In cross border estates, coordinating the Israeli process with foreign proceedings is essential to avoid conflicts between jurisdictions.',
    'estate.faq.q4': 'Can probate proceedings be managed remotely?',
    'estate.faq.a4': 'Yes. We handle the entire process with the Registrar of Inheritance or the Family Court, as well as coordination with banks and the Land Registry, through a power of attorney. You are not required to be physically present in Israel to obtain the order or to administer the estate.',
    'estate.cta.title': 'Planning That Protects What Matters',
    'estate.cta.body': 'Structured legal planning that supports your interests today and safeguards your family\'s position over time. Inquiries welcome in English and Hebrew.',
    'estate.cta.button': 'Begin Your Estate Plan',
    'estate.cta.note': 'Response within one to two business days.',

    // Real Estate Page
    'realestate.hero.title': 'Real Estate',
    'realestate.hero.subtitle': 'Guiding domestic and international clients through every stage of acquiring property in Israel.',
    'realestate.approach.title': 'Acquiring Property in Israel',
    'realestate.approach.body': 'For many clients, acquiring property in Israel represents more than an investment. It is a personal milestone and a strategic decision with long term financial implications. Israeli real estate law is technically demanding. Title verification, planning compliance, tax classification, and staged payment structures each carry consequences if mishandled. We provide seamless legal guidance throughout the entire acquisition process, from preliminary due diligence through contract negotiation to final registration at the Israel Land Registry (Tabu).',
    'realestate.approach.body2': 'Each stage is handled with clarity, discipline, and foresight, ensuring a smooth and secure transaction. Whether you are purchasing your first home, adding to an investment portfolio, or relocating from abroad, the legal strategy is tailored to your circumstances from the outset.',
    'realestate.risk.title': 'Identifying and Neutralizing Risk Before You Commit',
    'realestate.risk.intro': 'Israeli real estate law places the burden of verification squarely on the buyer. Our due diligence process is designed to surface and address exposure before any binding commitment is made',
    'realestate.risk.liabilities.title': 'Title and Encumbrances',
    'realestate.risk.liabilities.desc': 'Confirming registered ownership and detecting any liens, mortgages, caveats, or third party rights that could affect the transaction or limit future use.',
    'realestate.risk.planning.title': 'Planning and Permit Compliance',
    'realestate.risk.planning.desc': 'Verifying that the property was built in accordance with approved permits and that no open enforcement proceedings, deviation orders, or building code violations exist that could trigger fines or devaluation.',
    'realestate.risk.tax.title': 'Tax Exposure',
    'realestate.risk.tax.desc': 'Analyzing the client\'s residency status, acquisition timing, and transaction structure to identify the applicable Purchase Tax bracket and any Capital Gains exposure, and to ensure that no avoidable liability is triggered.',
    'realestate.tax.title': 'Tax and Regulatory Considerations',
    'realestate.tax.body': 'Purchase Tax (Mas Rechisha) in Israel is calculated according to a tiered bracket system that varies based on the buyer\'s classification. Israeli resident, foreign resident, new immigrant (Oleh), or returning resident (Toshav Hozer). The applicable rate can differ substantially between categories, and misclassification, whether by omission or by poor timing, can result in significant overpayment.',
    'realestate.tax.body2': 'We assess each client\'s tax position at the outset of every transaction. Filings to the Israel Tax Authority are prepared and submitted with careful attention to deadlines, documentation, and eligibility for any lawful relief. Clients who qualify for reduced rates under immigration or residency provisions receive structured guidance on the documentation and timing required to secure those benefits.',
    'realestate.diligence.title': 'Comprehensive Legal Due Diligence',
    'realestate.diligence.body': 'A secure acquisition begins with verification. Before any contractual commitment, we conduct a thorough legal audit of the property, covering registered title, encumbrances, planning history, building permits, and any pending administrative or legal proceedings that could affect the asset.',
    'realestate.diligence.body2': 'This structured analysis ensures that the property you acquire corresponds to the legal and physical reality you were shown. Clients make decisions based on documented facts, not assumptions.',
    'realestate.remote.title': 'Representation for Clients Outside Israel',
    'realestate.remote.body': 'Clients who reside abroad can complete the entire acquisition remotely. We act under an irrevocable power of attorney, signed at an Israeli consulate or before a notary public with apostille certification. This instrument enables full legal representation from negotiation through to final registration, without requiring the client\'s physical presence in Israel at any stage.',
    'realestate.remote.body2': 'We manage every step of the process on the client\'s behalf. Contract negotiation, due diligence, tax filings, coordination with the seller\'s counsel, and registration at the Land Registry. Communication is maintained throughout in English and Hebrew.',
    'realestate.faq.q1': 'When should I start tax planning?',
    'realestate.faq.a1': 'Tax planning on an Israeli property transaction must begin before any document is signed, ideally at the negotiation stage. The applicable Purchase Tax rate depends on your residency status, whether this is your first property in Israel, and the timing of the transaction relative to any Aliyah or relocation. Getting this wrong after the fact is expensive and in some cases irreversible. We assess your tax position at the outset, as part of the transaction structure.',
    'realestate.faq.q2': 'How are buyer funds protected during the transaction?',
    'realestate.faq.a2': 'Buyer funds in Israeli property transactions are released to the seller in stages, tied to specific legal milestones rather than as a lump sum. At each stage, a corresponding security interest is registered in the buyer\'s favor at the Land Registry, known as a Hearat Azhara or warning note. This mechanism ensures that if the transaction does not complete, the buyer\'s financial exposure is limited. The payment schedule and its linkage to milestones is one of the most important elements of the purchase contract and is negotiated before signing.',
    'realestate.faq.q3': 'Can I purchase property before making Aliyah?',
    'realestate.faq.a3': 'Yes. Non residents can purchase property in Israel. The more important question is the timing of the purchase relative to your Aliyah date, as this affects your Purchase Tax eligibility. In some cases purchasing before making Aliyah preserves certain benefits. In others, waiting is the better structure. This analysis is specific to each client\'s situation and should be done before any commitment is made.',
    'realestate.cta.title': 'Your Property, Our Priority',
    'realestate.cta.body': 'Whether you are buying your first home in Israel or adding to an existing portfolio, we are here to guide you through every legal and financial step. Inquiries welcome in English and Hebrew.',
    'realestate.cta.button': 'Discuss Your Property Plans',

    // Taxation Page
    'tax.hero.title': 'Tax and Compliance',
    'tax.hero.subtitle': 'Navigating Israeli tax obligations, banking compliance, and cross border coordination so you can move capital, close transactions, and stay compliant across jurisdictions.',
    'tax.context.title': 'Getting Your Tax Position Right from the Start',
    'tax.context.body': 'Tax and regulatory compliance determine whether transactions are approved, funded, and completed. Whether you are purchasing property, transferring capital, or restructuring holdings, every transaction carries implications in Israel and potentially in other jurisdictions. A misstep in classification, timing, or documentation can result in penalties, blocked funds, or lost treaty benefits.',
    'tax.context.body2': 'We integrate tax planning into the legal process from the outset, working to minimize regulatory friction, support full compliance, and protect your standing with Israeli financial institutions and tax authorities. The goal is a clear, documented position before any commitment is made.',
    'tax.realEstate.title': 'Real Estate Tax Planning',
    'tax.realEstate.body': 'Tax assessment is the critical first step of any property transaction in Israel. The brackets for Purchase Tax (Mas Rechisha) and Capital Gains Tax (Mas Shevach) vary based on your residency classification, the nature of the property, and whether other properties are held.',
    'tax.realEstate.assessment.title': 'Pre Contract Assessment',
    'tax.realEstate.assessment.desc': 'Calculating projected tax liabilities, identifying the correct residency classification, and confirming eligibility for any applicable relief before a binding commitment is made.',
    'tax.realEstate.ownership.title': 'Ownership and Structure Planning',
    'tax.realEstate.ownership.desc': 'Evaluating registration and ownership options aligned with your status, family structure, and long term financial objectives.',
    'tax.realEstate.filing.title': 'Filing and Reporting',
    'tax.realEstate.filing.desc': 'Preparing and submitting all declarations to the Israel Tax Authority with precise documentation, within the statutory deadlines, to avoid interest, penalties, and administrative delays.',
    'tax.banking.title': 'Banking Regulation and Source of Funds',
    'tax.banking.body': 'Transferring capital to or from Israel requires strict compliance with anti money laundering regulations and banking guidelines. Israeli banks conduct their own due diligence on incoming funds, and transfers that are not supported by clear documentation of source and purpose may be delayed, rejected, or flagged for further review.',
    'tax.banking.body2': 'We prepare comprehensive source of funds files and coordinate directly with the receiving bank to facilitate smooth acceptance. We also assist in preparing ongoing tax declarations, aligning Israeli reporting obligations with international requirements including FATCA and relevant treaty provisions to reduce the risk of double taxation.',
    'tax.serve.title': 'Is This Service Right for You?',
    'tax.serve.body': 'This service is designed for clients who prioritize a documented, transparent process. We partner with international investors and private clients who understand that compliance is the key to asset safety.',
    'tax.serve.compliance': 'Compliance First',
    'tax.serve.compliance.desc': 'Every engagement is built on documented verification, transparent timelines, and a structured process that prioritizes regulatory accuracy over speed.',
    'tax.serve.firstStep': 'First Step',
    'tax.serve.firstStep.desc': 'Engagement begins with a structured assessment of your tax position, residency status, and reporting obligations to establish a clear compliance roadmap.',
    'tax.crossBorder.title': 'Coordination with International Tax Obligations',
    'tax.crossBorder.body': 'Israel\'s network of bilateral tax treaties may affect how income, gains, and reporting obligations are treated depending on your jurisdiction of residence or citizenship.',
    'tax.crossBorder.body2': 'We identify potential treaty related considerations and coordinate with your foreign tax advisors to maintain a consistent tax position across jurisdictions. While we do not file foreign tax returns, we ensure that every Israeli legal action is documented and communicated clearly to your global advisory team.',
    'tax.olim.title': 'Tax Planning for Olim Hadashim and Returning Residents',
    'tax.olim.body': 'New immigrants (Olim Hadashim) and qualifying returning residents (Toshav Hozer Vatik) may be eligible for significant tax and reporting reliefs. These include reduced Purchase Tax rates on a first residential property in Israel and, for those who became Israeli residents before January 1, 2026, the ten year exemption from reporting on foreign source income. For those arriving from 2026 onward, the reporting exemption no longer applies, but additional Israeli source income benefits may be available depending on the year of arrival and legislative developments. These benefits are subject to strict eligibility criteria, classification rules, and timing requirements. The distinction between an Oleh Hadash and a Toshav Hozer Vatik carries different entitlements, and the date of arrival, the date of establishing tax residency, and the timing of first transactions in Israel all affect which reliefs are available. We help clients map their status, understand the implications of each classification, and structure the timing and documentation of their transition to support a compliant and tax efficient entry into the Israeli system.',
    'tax.faq.q1': 'Can I pay Israeli Purchase Tax in foreign currency?',
    'tax.faq.a1': 'No. Purchase Tax payments to the Israel Tax Authority are made in New Israeli Shekels. For clients transferring funds from abroad, this requires coordinating currency conversion, timing the transfer to limit exchange rate exposure, and ensuring the receiving Israeli bank accepts the funds. We manage this process as part of the transaction.',
    'tax.faq.q2': 'Will the Israeli bank automatically accept my transfer?',
    'tax.faq.a2': 'No. Israeli banks operate under strict anti money laundering and compliance requirements. An international transfer that arrives without prior documentation establishing the source of funds, the purpose of the transfer, and the underlying transaction is likely to be held or returned. Preparing the source of funds file in advance and coordinating with the bank before the transfer is initiated is standard practice on any cross border transaction. We handle this as part of our representation.',
    'tax.faq.q3': 'When do I become a tax resident of Israel?',
    'tax.faq.a3': 'Israeli tax residency is determined by the center of life test, a factual assessment that includes physical presence of over 183 days in a tax year or over 425 days across three consecutive years, as well as the location of your economic and personal ties. It is not determined by citizenship or Aliyah status alone. The consequences of becoming an Israeli tax resident are significant and affect reporting obligations on worldwide income. We advise on residency classification as part of pre arrival planning.',
    'tax.cta.title': 'Clarity Before You Commit',
    'tax.cta.body': 'Start with a structured tax assessment that turns uncertainty into documented decisions. Inquiries welcome in English and Hebrew.',
    'tax.cta.button': 'Request a Tax Review',

    // Olim & Returning Residents Page
    'olim.hero.title': 'Legal Counsel for Olim Hadashim and Returning Residents',
    'olim.hero.subtitle': 'Clear, personal legal guidance for one of life\'s most meaningful transitions.',
    'olim.context.title': 'A New Chapter, Structured from Day One',
    'olim.context.body': 'Beginning a new chapter in Israel brings opportunity, complexity, and important legal choices. The decisions you make in the first months of arrival, from how you classify your residency to when you purchase property and how you transfer capital, will affect your tax position, banking relationships, and financial structure for years to come.\n\nWe provide patient, personalized, and structured legal guidance for Olim Hadashim and Returning Residents. Each client receives a clear roadmap tailored to their specific situation, so that no critical step is missed and no benefit is forfeited through poor timing or incomplete documentation.',
    'olim.context.body2': '',
    'olim.framework.title': 'The Soft Landing Framework',
    'olim.framework.planning.title': 'Pre Arrival Planning',
    'olim.framework.planning.desc': 'Reviewing the client\'s residency status, asset profile, and family structure before arrival. Identifying timing sensitive decisions and positioning the client to preserve eligibility for available benefits.',
    'olim.framework.property.title': 'Property Acquisition Coordination',
    'olim.framework.property.desc': 'Managing the legal aspects of purchasing a first property in Israel, including due diligence, contract negotiation, tax filing, and registration, with particular attention to the interaction between purchase timing and Oleh or returning resident status.',
    'olim.framework.banking.title': 'Banking and Capital Transfers',
    'olim.framework.banking.desc': 'Preparing source of funds documentation, coordinating with the receiving Israeli bank, and ensuring that international transfers are accepted without unnecessary delay or complication.',
    'olim.framework.peace.title': 'Bilingual, Cross Border Support',
    'olim.framework.peace.desc': 'We communicate in both English and Hebrew and coordinate with the client\'s foreign advisors where needed. The goal is to translate complex Israeli legal processes into clear, practical steps, providing confidence during one of life\'s most significant transitions.',
    'olim.tax.title': 'Tax Positioning for Olim Hadashim and Returning Residents',
    'olim.tax.body': 'New immigrants and qualifying returning residents may be eligible for specific reliefs, including reduced Purchase Tax rates and the ten year exemption from reporting on foreign source income. These benefits are subject to strict eligibility criteria, and correct timing, classification, and documentation are essential to securing them.',
    'olim.tax.body2': 'We help clients understand how their specific circumstances affect their classification, what documentation is required, and how the timing of their arrival and first transactions should be structured to support a compliant and tax efficient transition into the Israeli system.',
    'olim.clients.title': 'Who This Service Is For',
    'olim.clients.body': 'This practice area is designed for individuals and families relocating to Israel who hold significant assets, foreign income, or cross border financial structures. Whether you are moving from the United States, the United Kingdom, Europe, or elsewhere, we bring the same level of attention and care to every engagement. Our clients value a disciplined, compliance first approach and understand that the legal and financial decisions made during the transition period will shape their position in Israel for years to come.',
    'olim.expect.title': 'What to Expect',
    'olim.expect.body': 'Engagement begins with a structured intake. A tailored documentation checklist, a residency and tax status assessment, and a coordinated roadmap with clearly defined next steps. Every client knows what is required, when it is required, and why it matters.',
    'olim.expect.item1': 'Documentation checklist tailored to your situation',
    'olim.expect.item2': 'Residency and tax status mapping',
    'olim.expect.item3': 'Coordinated roadmap with defined next steps',
    'olim.cta.title': 'Begin Your New Chapter with Confidence',
    'olim.cta.body': 'We understand that relocating to Israel is more than a legal process. It is a life decision. Let us help you make it with clarity, structure, and peace of mind. Inquiries welcome in English and Hebrew.',
    'olim.cta.button': 'Plan Your Arrival',

    // Commercial & Civil Page
    'commercial.hero.title': 'Commercial and Civil',
    'commercial.hero.subtitle': 'Protecting business interests through disciplined contracts, structured risk allocation, and Israel based representation for cross border matters.',
    'commercial.philosophy.title': 'Precision Before Disputes',
    'commercial.philosophy.body': 'In commercial engagements, the strength of your position depends on the quality of your contracts. Whether drafting a shareholders\' agreement, negotiating an exit, or structuring a cross border arrangement, we evaluate each matter through three lenses. Contractual rights, financial exposure, and future enforceability.',
    'commercial.philosophy.body2': 'This approach reflects our core discipline. Legal analysis that is informed by financial understanding. Clients receive structured guidance that supports negotiation, dispute resolution, or formal proceedings, depending on what the matter requires.',
    'commercial.services.title': 'Core Services',
    'commercial.services.contracts.title': 'Contract Drafting and Review',
    'commercial.services.contracts.desc': 'Structuring shareholders\' agreements, partnership agreements, commercial leases, service contracts, and other commercial instruments with precise definitions, clear allocation of risk, and enforceable remedies.',
    'commercial.services.negotiation.title': 'Negotiation and Risk Positioning',
    'commercial.services.negotiation.desc': 'Strategic legal counsel before signature or during escalation to improve the client\'s leverage, manage exposure, and define acceptable outcomes.',
    'commercial.services.dispute.title': 'Dispute Strategy and Resolution',
    'commercial.services.dispute.desc': 'Pre litigation analysis, settlement frameworks, and litigation management where required. Our approach prioritizes the client\'s commercial interest, whether that calls for determined enforcement or a negotiated resolution.',
    'commercial.services.crossborder.title': 'Cross Border Documentation',
    'commercial.services.crossborder.desc': 'Coordination with overseas counsel and localization of foreign contracts and judgments for enforcement or recognition in Israel.',
    'commercial.crossborder.title': 'Business Interests Across Borders',
    'commercial.crossborder.body': 'We serve as the local legal representative for clients who reside abroad but maintain active commercial or financial interests in Israel. This includes investors, business owners, and executives who require ongoing Israeli counsel or need to protect specific rights and obligations within the Israeli legal system.',
    'commercial.crossborder.body2': 'Whether enforcing a foreign contract in Israel, protecting shareholder rights while overseas, or managing a commercial dispute with an Israeli counterpart, we provide practical, on the ground representation. The practice coordinates Israeli legal requirements with foreign counsel and cross border strategy, ensuring that the client\'s position is consistent and enforceable across jurisdictions.',
    'commercial.clients.title': 'Who We Work With',
    'commercial.clients.body': 'The commercial practice serves business owners, investors, executives, and private clients who require disciplined legal counsel on contracts, asset protection, and complex disputes. Whether the engagement is a single transaction or an ongoing advisory relationship, we provide the same level of analytical depth and personal attention.',
    'commercial.cta.title': 'Protect Your Commercial Position',
    'commercial.cta.body': 'Begin with a contract review, a risk assessment, or a dispute strategy consultation. Confidential and documented. Inquiries welcome in English and Hebrew.',
    'commercial.cta.button': 'Schedule a Consultation',
  },
  he: {
    'nav.firm': 'אודות המשרד',
    'nav.about': 'אודות',
    'nav.expertise': 'מומחיות',
    'nav.realEstate': 'מקרקעין',
    'nav.taxation': 'מיסוי',
    'nav.estate': 'משפחה ומורשת',
    'nav.olim': 'עולים חדשים ותושבים חוזרים',
    'nav.commercial': 'מסחרי ואזרחי',
    'nav.insights': 'מאמרים',
    'nav.globalClients': 'לקוחות ברחבי העולם',
    'nav.contact': 'צור קשר',
    'nav.schedule': 'קבעו פגישת ייעוץ',
    'hero.tagline': 'בהירות בעולם המשתנה',
    'hero.title': 'עורך דין בישראל',
    'hero.subtitle1': 'ייעוץ משפטי מהשורה הראשונה חייב להיות ייחודי לא פחות מהלקוחות שהוא משרת. במשרד עורכי הדין מאיה זיו, כל תיק זוכה לתשומת הלב האישית המגיעה לו, כמו גם לעומק ולהיקף הנדרשים לעבודה מקצועית.',
    'hero.subtitle2': '',
    'guide.title': 'אודות משרד עורכי הדין מאיה זיו',
    'guide.bio': 'המשרד פועל כשותף מסור לכל לקוח, ומציע פתרונות מקוריים לבעיות המשפטיות המורכבות ביותר, הן ברמה המקומית והן ברמה הבינלאומית. המשרד ממוקם בישראל.',
    'guide.punchline': 'אנו חושבים קדימה למען לקוחותינו, ומשתמשים במאמרים ובשיקול דעת כדי לצפות את צרכיהם.',
    'guide.cta': 'מידע נוסף על המשרד',
    'parallax.quote': 'הפרטים שנראים טכניים הם לרוב אלה שקובעים את התוצאה.',
    'method.step1.title': 'הלקוחות שלנו',
    'method.step1.desc': 'אנשים פרטיים, משפחות ועסקים הפונים אלינו בעניינים החשובים ביותר שלהם, בידיעה שיזכו ליחס האישי שמצבו מצדיק. חלקם מתגוררים בישראל. אחרים מגיעים מכל רחבי העולם.',
    'method.step2.title': 'לא מתעלמים משום פרט',
    'method.step2.desc': 'אנו מביאים מאמרים ושיקול דעת לכל מצב. בין אם מדובר בניהול רכישת מקרקעין, בפיקוח על עמידה בדרישות רגולטוריות חוצות גבולות או בתכנון עזבון, כל עניין מטופל בתשומת הלב הראויה לו.',
    'method.step3.title': 'מעודכנים תמיד',
    'method.step3.desc': 'הלקוחות יודעים בדיוק מהו מצב העניינים בכל שלב. מה כבר הוסדר, מה נמצא בתהליך, ומה דורש את התערבותם.',
    'method.step4.title': 'כיסוי מלא, מערכת יחסים אחת',
    'method.step4.desc': 'היקף פעילות נרחב ועומק טכני של משרד מוביל, בשילוב עם היחס האישי הנדרש בכל מקרה ומקרה. זאת באמצעות רשת של יועצים מהימנים הפזורים ברחבי העולם, המתואמים באמצעות נקודת קשר אחת. הייעוץ ניתן בעברית ובאנגלית.',
    'method.step5.title': 'הבנה מעמיקה',
    'method.step5.desc': 'כל עניין מתחיל בהקשבה. אנו מקדישים זמן להבנת המטרה האמיתית שלקוחותינו שואפים להשיג, ולא רק את הסוגיה המשפטית המיידית.',
    'method.step6.title': 'תחומי עיסוק',
    'method.step6.desc': 'אנו מתמחים בעסקאות מקרקעין ובביצוע בדיקות נאותות. מיסוי רגולטורית חוצת גבולות. תכנון עזבונות, צוואות וירושה. הסכמים מסחריים וסכסוכים אזרחיים. הן ברמה המקומית והן ברמה הבינלאומית.',
    'practice.title': 'תחומי עיסוק',
    'practice.realEstate.title': 'מקרקעין והשקעות',
    'practice.realEstate.desc': 'רכישה בטוחה ותכנון מס.',
    'practice.taxation.title': 'מיסוי בינלאומי',
    'practice.taxation.desc': 'דיווח חוצה גבולות ורגולציה בנקאית.',
    'practice.estate.title': 'תכנון משפחתי ותכנון ירושה',
    'practice.estate.desc': 'צוואות, ירושה והעברת נכסים בין-דורית.',
    'practice.learnMore': 'למידע נוסף',
    'practice.olim.desc': 'ייעוץ משפטי לעולים חדשים ולתושבים שחזרו לארץ.',
    'practice.commercial.desc': 'חוזים, חלוקת סיכונים וייעוץ עסקי.',
    'practice.additional.olim': 'עולים חדשים ותושבים חוזרים',
    'practice.additional.commercial': 'מסחרי ואזרחי',
    'insights.title': 'מאמרים',
    'insights.readMore': 'המשך קריאה',
    'insights.viewAll': 'הצג את כל המאמרים',
    'insights.hero.title': '',
    'insights.hero.subtitle': 'הדרכה מעשית בנושאי מקרקעין בישראל, מיסוי חוצה גבולות, עמידה בדרישות הרגולטוריות ותכנון ירושה.',
    'insights.philosophy.title': 'בהירות בקבלת החלטות חוצות גבולות',
    'insights.philosophy.body': 'המאמרים שלנו נכתבות מתוך מחשבה על יישום מעשי. הסברים מובנים, שיקולים מרכזיים ומלכודות נפוצות שיש לזהות מבעוד מועד. המטרה היא לעזור לכם לשאול שאלות טובות יותר ולהבין את התוכנית המשפטית לפני שתתחייבו לעסקה.',
    'article.notFound': 'המאמר לא נמצא',
    'article.backToInsights': 'חזרה למאמרים',
    'article.readMore': 'רוצים לקרוא עוד?',
    'article.readMoreBody': 'חזרו לדף המאמרים שלנו כדי לקרוא מאמרים נוספים ותכנים מקצועיים.',
    'article.allArticles': 'כל המאמרים',
    'insights.article1.title': 'רכישת נכס בישראל כתושב זר יסודות משפטיים ומיסויים',
    'insights.article1.snippet': 'תושבים זרים נדרשים לעמוד בדרישות ייחודיות בתחום המשפטי, המיסוי והרישום בעת רכישת נכס בישראל. ביצוע בדיקת נאותות יסודית ותכנון מסודר מבטיחים עסקה תקינה ובטוחה.',
    'insights.article2.title': 'צוואות וירושה בישראל הבטחת תוקפן מעבר לגבולות',
    'insights.article2.snippet': 'משפחות חוצות גבולות נדרשות להתאים את הליכי הירושה הישראליים לצוואות זרות ולכללי אימות צוואות בחו"ל. תכנון מתואם מבטיח את אכיפת ההוראות ומונע סכסוכים משפטיים מיותרים.',
    'insights.article3.title': 'רכישת נכס בישראל בדיקות משפטיות חיוניות לרוכשים מקומיים',
    'insights.article3.snippet': 'רוכשים מקומיים חייבים לאמת את זכויות הבעלות, את מצב התכנון ואת ההגנות החוזיות לפני שהם מתחייבים לרכישת נכס. בדיקות משפטיות מסודרות מפחיתות את החשיפה ומסייעות בביצוע עסקה שקופה ותואמת לדרישות החוק.',
    'faq.title': 'שאלות נפוצות',
    'faq.q1': 'מתי כדאי להתחיל בתכנון מס?',
    'faq.a1': 'תכנון מס בעסקת מקרקעין בישראל חייב להתחיל עוד לפני חתימת המסמכים, ורצוי כבר בשלב המשא ומתן. שיעור מס הרכישה החל תלוי במעמד התושבות שלכם, בשאלה האם זו הנכס הראשון שלכם בישראל, ובמועד העסקה ביחס לעלייה או למעבר למקום מגורים חדש. טעות בעניין זה לאחר מעשה עשויה לעלות ביוקר, ובמקרים מסוימים היא בלתי הפיכה. אנו בוחנים את מצבכם הפיסקלי כבר בתחילת התהליך, כחלק ממבנה העסקה.',
    'faq.q2': 'כיצד מוגנים כספי הקונה במהלך העסקה?',
    'faq.a2': 'בעסקאות מקרקעין בישראל, הכספים של הקונה מועברים למוכר בשלבים, בהתאם לאבני דרך משפטיות ספציפיות, ולא בסכום חד-פעמי. בכל שלב נרשמת במרשם המקרקעין שעבוד לטובת הקונה, המכונה "הערות אזרח" או "הערות אזהרה". מנגנון זה מבטיח כי אם העסקה לא תושלם, החשיפה הכספית של הקונה תהיה מוגבלת. לוח התשלומים והקשר שלו לאבני הדרך הוא אחד המרכיבים החשובים ביותר בחוזה הרכישה, והוא מוסכם במשא ומתן לפני החתימה.',
    'faq.q3': 'האם אני יכול לרכוש נכס לפני העלייה?',
    'faq.a3': 'כן. תושבי חוץ יכולים לרכוש נכסים בישראל. השאלה החשובה יותר היא מועד הרכישה ביחס למועד העלייה, שכן הדבר משפיע על זכאותכם למס רכישה. במקרים מסוימים, רכישה לפני העלייה מאפשרת לשמור על הטבות מסוימות. במקרים אחרים, עדיף להמתין. ניתוח זה מותאם למצב הספציפי של כל לקוח, ויש לבצעו לפני קבלת כל התחייבות.',
    'faq.q4': 'האם ניתן לשלם את מס הרכישה הישראלי במטבע זר?',
    'faq.a4': 'לא. תשלומים בגין מס רכישה לרשות המסים הישראלית מתבצעים בשקלים חדשים. עבור לקוחות המעבירים כספים מחו"ל, הדבר מצריך תיאום המרת מטבע, תזמון ההעברה כדי לצמצם את החשיפה לשיעורי החליפין, והבטחת קבלת הכספים על ידי הבנק הישראלי המקבל. אנו מנהלים תהליך זה כחלק מהעסקה.',
    'faq.q5': 'האם הבנק הישראלי יקבל את ההעברה שלי באופן אוטומטי?',
    'faq.a5': 'לא. הבנקים בישראל פועלים תחת דרישות מחמירות בתחום איסור הלבנת הון. העברה בינלאומית שתתקבל ללא תיעוד מקדים המוכיח את מקור הכספים, מטרת ההעברה והעסקה שבבסיסה, צפויה להיעצר או להוחזר. הכנת תיק מקור הכספים מראש ותיאום עם הבנק לפני ביצוע ההעברה מהווים נוהל מקובל בכל עסקה חוצת גבולות. אנו מטפלים בכך במסגרת הייצוג שלנו.',
    'faq.q6': 'מתי אני נחשב לתושב לצורכי מס בישראל?',
    'faq.a6': 'תושבות מס בישראל נקבעת על פי "מבחן מרכז החיים" הערכה עובדתית הכוללת נוכחות פיזית של למעלה מ-183 ימים בשנה מס, או למעלה מ-425 ימים במשך שלוש שנים רצופות, וכן את מיקומם של קשריכם הכלכליים והאישיים. היא אינה נקבעת על סמך אזרחות או מעמד עלייה בלבד. ההשלכות של קבלת מעמד של תושב מס בישראל הן משמעותיות ומשפיעות על חובות הדיווח על הכנסות מכל העולם. אנו מספקים ייעוץ בנושא סיווג תושבות במסגרת תכנון לקראת הגעה לישראל.',
    'faq.q7': 'האם צוואה שנערכה בחו"ל תקפה בישראל?',
    'faq.a7': 'צוואה זרה יכולה להיות מוכרת בישראל, אך עליה לעבור הליך אימות צוואה הכולל חוות דעת מומחים בנוגע לדין הזר הרלוונטי. הליך זה כרוך בזמן, בעלות ובחוסר וודאות, במיוחד כאשר העיזבון כולל מקרקעין בישראל. הגישה האמינה יותר היא לערוך צוואה ישראלית נפרדת המתייחסת באופן ספציפי לנכסים בישראל, תוך תיאום עם הצוואה הזרה שלכם, כך ששני המסמכים לא יסתרו זה את זה. אנו מספקים ייעוץ הן בנוגע לניסוח הצוואה והן בנוגע לתיאום בין תחומי השיפוט השונים.',
    'faq.q8': 'האם אני יכול למנות מנהל עזבון המתגורר מחוץ לישראל?',
    'faq.a8': 'כן, אם כי בתי המשפט בישראל עשויים לדרוש צעדים פרוצדורליים נוספים, לרבות מתן ערבויות, בטרם ימנו מנהל נכסים שאינו תושב. ההשלכות המעשיות תלויות בהרכב העזבון ובמורכבות ההליכים. אנו מספקים ייעוץ בנוגע לבחירת מנהל עזבון כחלק מתהליך תכנון העזבון, תוך התייחסות לדרישות הריאליות של התפקיד ולמבנה המשפחתי והנכסי של הלקוח.',
    'faq.q9': 'מה ההבדל בין צו ירושה לצו אימות צוואה?',
    'faq.a9': 'צו קיום צוואה (קייום צוואה) ניתן על ידי רשם הירושה הישראלי כאשר המנוח הותיר אחריו צוואה תקפה. צו זה מאשר את תוקפה של הצוואה ומאשר את ביצועה. צו ירושה (צוו ירושה) ניתן כאשר אין צוואה תקפה, ואז חלוקת העזבון מתבצעת בהתאם להוראות חוק הירושה הישראלי. בעזבונות חוצי גבולות, תיאום ההליך הישראלי עם ההליכים הזרים הוא חיוני כדי למנוע סתירות בין תחומי השיפוט.',
    'cta.title': 'כאשר העניין מצריך שיקול דעת משפטי וכלכלי כאחד',
    'cta.subtitle': 'לקוחות בישראל ומחוצה לה פונים למשרד עורכי הדין מאיה זיו בעסקאות שבהן הדיוק הוא גורם מכריע. ניתן לפנות אלינו בעברית ובאנגלית.',
    'cta.button': 'קבעו פגישת ייעוץ',
    'cta.buttonSecondary': 'הערכת התאמה ראשונית',
    'footer.brand': 'עורך דין בישראל',
    'footer.services': 'שירותים',
    'footer.contact': 'צור קשר',
    'footer.legal': 'משפטי',
    'footer.disclaimer': 'הצהרת פטור מאחריות',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי השימוש',
    'footer.disclaimerText': 'אתר זה נועד למטרות מידע בלבד ואינו מהווה ייעוץ משפטי. השימוש באתר זה אינו יוצר יחסי עורך דין-לקוח.',
    'footer.copyright': '© 2026 משרד עורכי הדין מאיה זיו. כל הזכויות שמורות.',
    'contact.title': 'צרו איתנו קשר',
    'contact.subtitle': 'התחילו את המסע שלכם לעבר בהירות משפטית',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'כתובת דוא"ל',
    'contact.form.phone': 'מספר טלפון',
    'contact.form.inquiry': 'אופי המחקר',
    'contact.form.message': 'ההודעה שלך',
    'contact.form.submit': 'שלח הודעה',
    'contact.form.success': 'תודה על הודעתך. נשיב לך תוך 24 עד 48 שעות.',
    'contact.inquiry.realEstate': 'עסקת מקרקעין',
    'contact.inquiry.taxation': 'מיסוי בינלאומי',
    'contact.inquiry.estate': 'תכנון עזבון',
    'contact.inquiry.other': 'עניינים משפטיים אחרים',
    'about.hero.title': 'אודות משרד עורכי הדין מאיה זיו',
    'about.mainBody': 'הלקוחות שלנו פונים אלינו בעניינים הדורשים הן דיוק משפטי והן שיקול דעת. אנו מתייחסים לכל מקרה כאל מצב ייחודי, עם ההשלכות, המורכבות והתוצאה הנדרשת שלו.',
    'about.cta.title': 'ספר לנו על העניין שלך',
    'about.cta.body': 'מהשיחה הראשונה, הלקוחות יודעים בדיוק במה עוסקת העניינם ומה צפוי להם בהמשך.',
    'about.cta.button': 'צרו קשר',
    'service.faq': 'שאלות נפוצות',
    'estate.hero.title': 'הגנה על משפחתך מעבר לגבולות',
    'estate.hero.subtitle': 'תכנון משפטי מובנה להעברת נכסים בין-לאומית, צוואות דו-לשוניות וייפוי כוח מתמשך על פי החוק הישראלי.',
    'estate.challenge.title': 'ניהול הון משפחתי במדינות שונות',
    'estate.challenge.body': 'משפחות בעלות נכסים בישראל וקשרים למדינות אחרות ניצבות בפני אתגר ייחודי להבטיח שההון יעבור לדור הבא ביעילות, בהתאם לרצונכם, וללא אירועי מס מיותרים או עיכובים פרוצדורליים. דיני הירושה בישראל פועלים על פי כללים משלהם בכל הנוגע לפורמליות, סמכות שיפוט והליכים. כאשר מעורבים צוואות זרות, מוטבים זרים או נכסים במספר מדינות, המורכבות גדלה באופן משמעותי. אנו מפתחים תוכניות ירושה מובנות המשלבות את דיני הירושה הישראליים עם המסגרות המשפטיות הזרות הרלוונטיות. המטרה היא למנוע סכסוכים, לצמצם עיכובים בהליכי הירושה ולהפחית את החשיפה למיסוי כפול או לסדרי ירושה סותרים.',
    'estate.challenge.body2': '',
    'estate.wills.title': 'צוואות, ירושה ותיאום חוצה גבולות',
    'estate.wills.body': 'אנו מכינים צוואות המותאמות לישראל ותוכניות ירושה מקיפות עבור לקוחות המחזיקים בנכסים או מקיימים קשרי משפחה במדינות שונות. כל מסמך מנוסח כך שיעמוד בדרישות הפורמליות והראייתיות בישראל, תוך תיאום עם כל מסמכי הצוואה הזרים הקיימים.',
    'estate.wills.compliance.title': 'ניסוח לצורך עמידה בדרישות',
    'estate.wills.compliance.desc': 'ניסוח צוואות העומדות בדרישות הפורמליות של החוק הישראלי, לרבות הוראות בנוגע לעדים והיבטים לשוניים במסמכים דו-לשוניים.',
    'estate.wills.probate.title': 'צווי ירושה ועיזבון',
    'estate.wills.probate.desc': 'ייצוג יורשים בהשגת צו קיום צוואה (קייום צוואה) כאשר קיימת צוואה תקפה, או צו ירושה (צו ירושה) כאשר לא הותירה המנוחה צוואה, באמצעות רשם הירושות או בית המשפט לענייני משפחה.',
    'estate.wills.conflict.title': 'צמצום קונפליקטים',
    'estate.wills.conflict.desc': 'ניסוח ברור וחד-משמעי, המפחית את הסיכוי למחלוקות בנוגע לפרשנות בין המוטבים. במקרים שבהם יחסי המשפחה רגישים, אנו מנסחים את המסמכים באופן שמצמצם את העילות להגשת ערעור.',
    'estate.epa.title': 'ייפוי כוח מתמשך',
    'estate.epa.body': 'ייפוי כוח מתמשך (EPA) הוא מסמך משפטי המכוון לעתיד, המאפשר לכם למנות אנשים מהימנים שינהלו את ענייניכם האישיים, הרפואיים והפיננסיים בישראל, במקרה שלא תוכלו לעשות זאת בעצמכם. בניגוד לאפוטרופסות הממונה על ידי בית המשפט, ייפוי כוח מתמשך מאפשר לכם לקבוע את היקף הסמכויות, את זהות נציגיכם ואת התנאים שבהם המסמך ייכנס לתוקף.',
    'estate.epa.body2': 'אנו מכינים מסמכי EPA מקיפים העומדים בדרישות בית המשפט, השומרים על עצמאותכם, משקפים את כוונותיכם ומספקים למשפחתכם הנחיות ברורות למקרה שרוב האנשים מעדיפים לתכנן מראש, במקום להשאיר את ההחלטה לשיקול דעתו של בית המשפט.',
    'estate.process.title': 'איך אנחנו עובדים',
    'estate.process.step1.title': 'גילוי ומיפוי',
    'estate.process.step1.desc': 'אנו מזהים וממפים את נכסיכם, תחומי השיפוט הרלוונטיים, המוטבים והדינמיקה המשפחתית, כדי להבין את התמונה המשפטית והפיננסית במלואה.',
    'estate.process.step2.title': 'אסטרטגיה ומבנה',
    'estate.process.step2.desc': 'אנו מציעים מבנה הכולל מסמכים ושלבי תיאום המותאמים ליעדיכם ולדרישות של כל תחום שיפוט רלוונטי.',
    'estate.process.step3.title': 'ניסוח וביצוע',
    'estate.process.step3.desc': 'המסמכים מנוסחים בשתי שפות, ככל שנדרש, ונחתמים בהתאם לדרישות החוק הישראלי. עבור לקוחות מחו"ל, החתימה יכולה להתבצע בקונסוליה או בפני נוטריון עם אישור אפוסטיל.',
    'estate.process.step4.title': 'שמירה והדרכה',
    'estate.process.step4.desc': 'אנו מספקים הוראות לאחסון בטוח והנחיות מעשיות למנהלי העזבון בנוגע להפעלת התוכנית בעתיד, כדי שהתוכנית תפעל כשיידרש.',
    'estate.process.note': 'היקף ברור, צעדים מוגדרים להמשך ודרישות התיעוד נקבעים מראש.',
    'estate.tax.title': 'היבטים מיסויים בענייני ירושה חוצת גבולות',
    'estate.tax.body': 'הטיפול המס בישראל בירושות ובהעברות נכסים עוד בחייו של אדם שונה מזה הנהוג במדינות מערביות רבות. העברת נכסים, בין אם עוד בחייו של אדם ובין אם לאחר מותו, עשויה להוביל לאירועים מסים המשתנים בהתאם לאופי הנכס, למקום מגוריהם של הצדדים ולמועד ההעברה.',
    'estate.tax.body2': 'אנו מזהים מראש את החשיפה הפוטנציאלית למס ומתאמים את הפעולות עם יועצים רלוונטיים בתחומי שיפוט אחרים, במידת הצורך. המטרה היא לתכנן את העזבון באופן שיצמצם את החבות הניתנת למניעה ויגן על ערכו של הירושה המועברת לדור הבא.',
    'estate.financial.title': 'הסכמי ממון לפני הנישואין ואחרי הנישואין',
    'estate.financial.body': 'עבור זוגות מקומיים ובינלאומיים, אנו מכינים הסכמים דו-לשוניים באנגלית ובעברית, העוסקים בבעלות על נכסים, בהסדרים פיננסיים ובהגנה על נכסים חוצה גבולות. כל הסכם מנוסח בדייקנות, ובמידת הצורך מאושר על ידי בית משפט או נוטריון, כדי להבטיח את אכיפתו על פי החוק הישראלי.',
    'estate.faq.q1': 'האם צוואה שנערכה בחו"ל תקפה בישראל?',
    'estate.faq.a1': 'צוואה זרה יכולה להיות מוכרת בישראל, אך עליה לעבור הליך אימות צוואה הכולל חוות דעת מומחים בנוגע לדין הזר הרלוונטי. הליך זה כרוך בזמן, בעלות ובחוסר וודאות, במיוחד כאשר העיזבון כולל מקרקעין בישראל. הגישה האמינה יותר היא לערוך צוואה ישראלית נפרדת המתייחסת באופן ספציפי לנכסים בישראל, תוך תיאום עם הצוואה הזרה שלכם, כך ששני המסמכים לא יסתרו זה את זה. אנו מספקים ייעוץ הן בנוגע לניסוח הצוואה והן בנוגע לתיאום בין תחומי השיפוט השונים.',
    'estate.faq.q2': 'האם אני יכול למנות מנהל עזבון המתגורר מחוץ לישראל?',
    'estate.faq.a2': 'כן, אם כי בתי המשפט בישראל עשויים לדרוש צעדים פרוצדורליים נוספים, לרבות מתן ערבויות, בטרם ימנו מנהל נכסים שאינו תושב. ההשלכות המעשיות תלויות בהרכב העזבון ובמורכבות ההליכים. אנו מספקים ייעוץ בנוגע לבחירת מנהל עזבון כחלק מתהליך תכנון העזבון, תוך התייחסות לדרישות הריאליות של התפקיד ולמבנה המשפחתי והנכסי של הלקוח.',
    'estate.faq.q3': 'מה ההבדל בין צו ירושה לצו אימות צוואה?',
    'estate.faq.a3': 'צו קיום צוואה (Kiyum Tzava\'a) ניתן על ידי רשם הירושה הישראלי כאשר המנוח הותיר אחריו צוואה תקפה. צו זה מאשר את תוקפה של הצוואה ומאשר את ביצועה. צו ירושה, "צוו ירושה", ניתן כאשר אין צוואה תקפה, ואז חלוקת העזבון מתבצעת בהתאם להוראות חוק הירושה הישראלי. בעזבונות חוצי גבולות, תיאום ההליך הישראלי עם ההליכים הזרים הוא חיוני כדי למנוע סתירות בין שיטות המשפט.',
    'estate.faq.q4': 'האם ניתן לנהל הליכי ירושה מרחוק?',
    'estate.faq.a4': 'כן. אנו מטפלים בכל התהליך מול רשם הירושה או בית המשפט לענייני משפחה, וכן בתיאום מול הבנקים ומרשם המקרקעין, באמצעות ייפוי כוח. אינך נדרש להיות נוכח פיזית בישראל כדי לקבל את הצו או לנהל את העזבון.',
    'estate.cta.title': 'תכנון שמגן על מה שחשוב',
    'estate.cta.body': 'תכנון משפטי מובנה התומך באינטרסים שלכם כיום ומבטיח את עתיד משפחתכם לאורך זמן. ניתן לפנות אלינו באנגלית ובעברית.',
    'estate.cta.button': 'התחילו בתכנון העיזבון שלכם',
    'estate.cta.note': 'תשובה תינתן תוך יום עד יומיים עסקים.',
    'realestate.hero.title': 'מקרקעין',
    'realestate.hero.subtitle': 'ליווי לקוחות מקומיים ובינלאומיים בכל שלבי תהליך רכישת הנכס בישראל.',
    'realestate.approach.title': 'רכישת נכס בישראל',
    'realestate.approach.body': 'עבור לקוחות רבים, רכישת נכס בישראל היא יותר מסתם השקעה. זוהי אבן דרך אישית והחלטה אסטרטגית בעלת השלכות פיננסיות ארוכות טווח. דיני המקרקעין בישראל הם מורכבים מבחינה טכנית. אימות זכויות בעלות, עמידה בתכניות בנייה, סיווג מס ומבני תשלום מדורגים לכל אחד מהם השלכות במקרה של טיפול לא נכון. אנו מספקים ליווי משפטי רציף לאורך כל תהליך הרכישה, החל מבדיקת נאותות ראשונית, דרך משא ומתן על החוזה ועד לרישום הסופי במרשם המקרקעין (טאבו).',
    'realestate.approach.body2': 'כל שלב מטופל בבהירות, במשמעת עצמית ובתבונה, כדי להבטיח עסקה חלקה ובטוחה. בין אם אתם רוכשים את ביתכם הראשון, מרחיבים את תיק ההשקעות שלכם או עוברים מחו"ל, האסטרטגיה המשפטית מותאמת לנסיבותיכם כבר מהשלב הראשון.',
    'realestate.risk.title': 'זיהוי ונטרול סיכונים לפני ההתחייבות',
    'realestate.risk.intro': 'דיני המקרקעין בישראל מטילים את נטל הבדיקה על הקונה. תהליך הבדיקה המוקדמת שלנו נועד לאתר ולטפל בסיכונים לפני שנחתם כל הסכם מחייב',
    'realestate.risk.liabilities.title': 'בעלות ונטל',
    'realestate.risk.liabilities.desc': 'אימות הבעלות הרשומה וזיהוי שעבודים, משכנתאות, התנגדויות או זכויות של צד שלישי העלולים להשפיע על העסקה או להגביל את השימוש בה בעתיד.',
    'realestate.risk.planning.title': 'תכנון ועמידה בדרישות היתרים',
    'realestate.risk.planning.desc': 'וידוא שהנכס נבנה בהתאם להיתרים שאושרו, וכי אין הליכי אכיפה פתוחים, צווי חריגה או הפרות של תקנות הבנייה העלולים להוביל לקנסות או לירידת ערך.',
    'realestate.risk.tax.title': 'חשיפה מס',
    'realestate.risk.tax.desc': 'ניתוח מעמד התושבות של הלקוח, מועד הרכישה ומבנה העסקה, על מנת לקבוע את מדרגת מס הרכישה החלה ואת החשיפה לרווחי הון, וכדי להבטיח שלא ייווצר חוב שניתן היה למנוע.',
    'realestate.tax.title': 'היבטים מיסויים ורגולטוריים',
    'realestate.tax.body': 'מס רכישה בישראל מחושב על פי שיטת מדרגות המס, המשתנה בהתאם לסיווגו של הרוכש תושב ישראל, תושב זר, עולה חדש או תושב חוזר. שיעור המס החל עשוי להשתנות באופן משמעותי בין הקטגוריות השונות, וסיווג שגוי בין אם בשל השמטה ובין אם בשל תזמון לא נכון עלול לגרום לתשלום עודף ניכר.',
    'realestate.tax.body2': 'אנו בוחנים את מצבו הפיסקלי של כל לקוח בתחילת כל עסקה. הדיווחים לרשות המסים בישראל מנוסחים ומוגשים תוך הקפדה יתרה על מועדי הגשה, תיעוד וזכאות להקלות חוקיות. לקוחות הזכאים לשיעורי מס מופחתים מכוח הוראות הגירה או תושבות מקבלים ייעוץ מובנה בנוגע לתיעוד וללוח הזמנים הנדרשים כדי להבטיח את ההטבות הללו.',
    'realestate.diligence.title': 'בדיקת נאותות משפטית מקיפה',
    'realestate.diligence.body': 'רכישה בטוחה מתחילה בבדיקה. לפני כל התחייבות חוזית, אנו מבצעים בדיקה משפטית מקיפה של הנכס, הכוללת את רישום הבעלות, שעבודים, היסטוריית התכנון, היתרי בנייה וכל הליך מנהלי או משפטי תלוי ועומד שעלול להשפיע על הנכס.',
    'realestate.diligence.body2': 'ניתוח מובנה זה מבטיח שהנכס שתרכשו תואם למציאות המשפטית והפיזית שהוצגה בפניכם. הלקוחות מקבלים החלטות על סמך עובדות מתועדות, ולא על סמך הנחות.',
    'realestate.remote.title': 'ייצוג לקוחות מחוץ לישראל',
    'realestate.remote.body': 'לקוחות המתגוררים בחו"ל יכולים לבצע את כל תהליך הרכישה מרחוק. אנו פועלים מכוח ייפוי כוח בלתי חוזר, שנחתם בקונסוליה ישראלית או בפני נוטריון עם אישור אפוסטיל. מסמך זה מאפשר ייצוג משפטי מלא, החל משלב המשא ומתן ועד לרישום הסופי, מבלי שהלקוח יידרש להיות נוכח פיזית בישראל בשום שלב.',
    'realestate.remote.body2': 'אנו מטפלים בכל שלב בתהליך מטעם הלקוח. משא ומתן על חוזה, בדיקת נאותות, הגשת דוחות מס, תיאום עם יועץ המשפטי של המוכר ורישום במרשם המקרקעין. התקשורת מתנהלת לאורך כל הדרך באנגלית ובעברית.',
    'realestate.faq.q1': 'מתי כדאי להתחיל בתכנון מס?',
    'realestate.faq.a1': 'תכנון מס בעסקת מקרקעין בישראל חייב להתחיל עוד לפני חתימת המסמכים, ורצוי כבר בשלב המשא ומתן. שיעור מס הרכישה החל תלוי במעמד התושבות שלכם, בשאלה האם זו הנכס הראשון שלכם בישראל, ובמועד העסקה ביחס לעלייה או למעבר למקום מגורים חדש. טעות בעניין זה לאחר מעשה עשויה לעלות ביוקר, ובמקרים מסוימים היא בלתי הפיכה. אנו בוחנים את מצבכם הפיסקלי כבר בתחילת התהליך, כחלק ממבנה העסקה.',
    'realestate.faq.q2': 'כיצד מוגנים כספי הקונה במהלך העסקה?',
    'realestate.faq.a2': 'בעסקאות מקרקעין בישראל, הכספים של הקונה מועברים למוכר בשלבים, בהתאם לאבני דרך משפטיות ספציפיות, ולא בסכום חד-פעמי. בכל שלב נרשמת במרשם המקרקעין שעבוד לטובת הקונה, המכונה "הערות אזרח" או "הערות אזהרה". מנגנון זה מבטיח כי אם העסקה לא תושלם, החשיפה הכספית של הקונה תהיה מוגבלת. לוח התשלומים והקשר שלו לאבני הדרך הוא אחד המרכיבים החשובים ביותר בחוזה הרכישה, והוא מוסכם במשא ומתן לפני החתימה.',
    'realestate.faq.q3': 'האם אני יכול לרכוש נכס לפני העלייה?',
    'realestate.faq.a3': 'כן. תושבי חוץ יכולים לרכוש נכסים בישראל. השאלה החשובה יותר היא מועד הרכישה ביחס למועד העלייה, שכן הדבר משפיע על זכאותכם למס רכישה. במקרים מסוימים, רכישה לפני העלייה מאפשרת לשמור על הטבות מסוימות. במקרים אחרים, עדיף להמתין. ניתוח זה מותאם למצב הספציפי של כל לקוח, ויש לבצעו לפני קבלת כל התחייבות.',
    'realestate.cta.title': 'הנכס שלכם, בראש סדר העדיפויות שלנו',
    'realestate.cta.body': 'בין אם אתם רוכשים את דירתכם הראשונה בישראל ובין אם אתם מרחיבים את תיק הנכסים הקיים שלכם, אנו כאן כדי ללוות אתכם בכל שלב משפטי ופיננסי. ניתן לפנות אלינו באנגלית ובעברית.',
    'realestate.cta.button': 'דנו בתוכניות המקרקעין שלכם',
    'tax.hero.title': 'מיסוי',
    'tax.hero.subtitle': 'אנו מסייעים לכם להתמודד עם חובות המס בישראל, דרישות הציות הבנקאיות ותיאום חוצה גבולות, כדי שתוכלו להעביר הון, לסגור עסקאות ולשמור על לדרישות הרגולטוריות בכל תחומי השיפוט.',
    'tax.context.title': 'להגדיר נכון את מעמדכם מבחינת המס כבר מההתחלה',
    'tax.context.body': 'עמידה בדרישות המס והרגולציה קובעת אם עסקאות יאושרו, ימומנו ויושלמו. בין אם אתם רוכשים נכס, מעבירים הון או מבצעים ארגון מחדש של אחזקות, לכל עסקה יש השלכות בישראל, ובמקרים מסוימים גם בתחומי שיפוט אחרים. טעות בסיווג, בעיתוי או בתיעוד עלולה להוביל לקנסות, להקפאת כספים או לאובדן הטבות מכוח אמנות מס.',
    'tax.context.body2': 'אנו משלבים את תכנון המס בתהליך המשפטי כבר מהשלב הראשוני, תוך שאנו פועלים לצמצום חיכוכים רגולטוריים, תמיכה בעמידה מלאה בדרישות החוק והגנה על מעמדכם מול המוסדות הפיננסיים ורשויות המס בישראל. המטרה היא להגיע לעמדה ברורה ומתועדת בטרם תתקבל כל התחייבות.',
    'tax.realEstate.title': 'תכנון מס מקרקעין',
    'tax.realEstate.body': 'קביעת המס היא הצעד הראשון והחשוב ביותר בכל עסקה נדל"נית בישראל. מדרגות המס של מס רכישה ומס רווחי הון משתנות בהתאם לסיווג התושבות שלכם, לאופי הנכס, ולשאלה האם אתם מחזיקים בנכסים נוספים.',
    'tax.realEstate.assessment.title': 'הערכת טרום-חוזה',
    'tax.realEstate.assessment.desc': 'חישוב התחייבויות המס הצפויות, זיהוי סיווג התושבות הנכון ואימות הזכאות להקלות רלוונטיות כלשהן, בטרם מתקבלת התחייבות מחייבת.',
    'tax.realEstate.ownership.title': 'תכנון בעלות ומבנה',
    'tax.realEstate.ownership.desc': 'בחינת אפשרויות הרישום והבעלות המ למעמדכם, למבנה המשפחתי שלכם וליעדים הפיננסיים ארוכי הטווח שלכם.',
    'tax.realEstate.filing.title': 'הגשה ודיווח',
    'tax.realEstate.filing.desc': 'הכנה והגשה של כל הדוחות לרשות המסים בישראל, בצירוף תיעוד מדויק, בתוך המועדים הקבועים בחוק, כדי למנוע ריבית, קנסות ועיכובים מנהליים.',
    'tax.banking.title': 'רגולציה בנקאית ומקור הכספים',
    'tax.banking.body': 'העברת כספים אל ישראל או ממנה מחייבת עמידה קפדנית בתקנות למניעת הלבנת הון ובהנחיות הבנקאיות. הבנקים בישראל מבצעים בדיקות נאותות משלהם לגבי כספים הנכנסים, והעברות שאינן מגובות בתיעוד ברור של מקור הכספים ומטרתן עלולות להתעכב, להידחות או להיסמן לבדיקה נוספת.',
    'tax.banking.body2': 'אנו מכינים תיקי מקור כספים מפורטים ומתאמים ישירות עם הבנק המקבל כדי להבטיח קבלה חלקה. כמו כן, אנו מסייעים בהכנת דוחות מס שוטפים, תוך התאמת חובות הדיווח הישראליות לדרישות הבינלאומיות, לרבות חוק FATCA והוראות האמנות הרלוונטיות, כדי להפחית את הסיכון למיסוי כפול.',
    'tax.serve.title': 'האם השירות הזה מתאים לך?',
    'tax.serve.body': 'שירות זה מיועד ללקוחות המעדיפים תהליך מתועד ושקוף. אנו פועלים בשיתוף פעולה עם משקיעים בינלאומיים ולקוחות פרטיים המבינים כי עמידה בדרישות הרגולטוריות היא המפתח לשמירה על נכסים.',
    'tax.serve.compliance': 'קודמת לכל',
    'tax.serve.compliance.desc': 'כל פרויקט מתבסס על אימות מתועד, לוחות זמנים שקופים ותהליך מובנה המעדיף את הדיוק הרגולטורי על פני המהירות.',
    'tax.serve.firstStep': 'הצעד הראשון',
    'tax.serve.firstStep.desc': 'התהליך מתחיל בהערכה מסודרת של מצבכם הפיסקלי, מעמד התושבות שלכם וחובות הדיווח שלכם, במטרה לקבוע תוכנית פעולה ברורה לעמידה בדרישות הרגולטוריות.',
    'tax.crossBorder.title': 'תיאום עם חובות המס הבינלאומיות',
    'tax.crossBorder.body': 'רשת אמנות המס הדו-צדדיות של ישראל עשויה להשפיע על אופן הטיפול בהכנסות, ברווחים ובחובות הדיווח, בהתאם לתחום השיפוט שבו אתה מתגורר או לאזרחותך.',
    'tax.crossBorder.body2': 'אנו מזהים שיקולים פוטנציאליים הקשורים לאמנות מס ומתאמים עם יועצי המס הזרים שלכם כדי לשמור על עמדת מס עקבית בכל תחומי השיפוט. אף שאנו לא מגישים דוחות מס זרים, אנו דואגים שכל פעולה משפטית בישראל תתועד ותועבר בצורה ברורה לצוות הייעוץ הגלובלי שלכם.',
    'tax.olim.title': 'תכנון מס לעולים חדשים ולתושבים חוזרים',
    'tax.olim.body': 'עולים חדשים ותושבים חוזרים זכאים עשויים להיות זכאים להקלות משמעותיות בתחום המס והדיווח. אלה כוללות שיעורי מס רכישה מופחתים על דירת מגורים ראשונה בישראל, ובמקרה של מי שהפכו לתושבי ישראל לפני ה-1 בינואר 2026 פטור בן עשר שנים מחובת דיווח על הכנסות ממקור זר. למי שיגיע משנת 2026 ואילך, הפטור מדיווח כבר לא יחול, אך ייתכן שיהיו הטבות נוספות בגין הכנסות ממקור ישראלי, בהתאם לשנת ההגעה ולהתפתחויות בחקיקה. הטבות אלה כפופות לקריטריוני זכאות מחמירים, לכללי סיווג ולדרישות עיתוי. ההבחנה בין "עולה חדש" ל"תושב חוזר ותיק" נושאת בחובה זכויות שונות, ותאריך ההגעה, תאריך קביעת תושבות המס ומועד העסקאות הראשונות בישראל משפיעים כולם על ההקלות הזמינות. אנו מסייעים ללקוחות למפות את מעמדם, להבין את השלכותיה של כל סיווג, ולתכנן את העיתוי והתיעוד של המעבר שלהם, כדי לתמוך בכניסה תואמת ויעילה מבחינה מסית למערכת הישראלית.',
    'tax.faq.q1': 'האם ניתן לשלם את מס הרכישה הישראלי במטבע זר?',
    'tax.faq.a1': 'לא. תשלומים בגין מס רכישה לרשות המסים הישראלית מתבצעים בשקלים חדשים. עבור לקוחות המעבירים כספים מחו"ל, הדבר מצריך תיאום המרת מטבע, תזמון ההעברה כדי לצמצם את החשיפה לשינויי שער החליפין, והבטחת קבלת הכספים על ידי הבנק הישראלי המקבל. אנו מנהלים תהליך זה במסגרת העסקה.',
    'tax.faq.q2': 'האם הבנק הישראלי יקבל את ההעברה שלי באופן אוטומטי?',
    'tax.faq.a2': 'לא. הבנקים בישראל פועלים תחת דרישות מחמירות בתחום איסור הלבנת הון. העברה בינלאומית שתתקבל ללא תיעוד מקדים המוכיח את מקור הכספים, מטרת ההעברה והעסקה שבבסיסה, צפויה להיעצר או להוחזר. הכנת תיק מקור הכספים מראש ותיאום עם הבנק לפני ביצוע ההעברה מהווים נוהל מקובל בכל עסקה חוצת גבולות. אנו מטפלים בכך במסגרת הייצוג שלנו.',
    'tax.faq.q3': 'מתי אני נחשב לתושב לצורכי מס בישראל?',
    'tax.faq.a3': 'תושבות מס בישראל נקבעת על פי "מבחן מרכז החיים" הערכה עובדתית הכוללת נוכחות פיזית של למעלה מ-183 ימים בשנה מס, או למעלה מ-425 ימים במשך שלוש שנים רצופות, וכן את מיקומם של קשריכם הכלכליים והאישיים. היא אינה נקבעת על סמך אזרחות או מעמד עלייה בלבד. ההשלכות של קבלת מעמד של תושב מס בישראל הן משמעותיות ומשפיעות על חובות הדיווח על הכנסות מכל העולם. אנו מספקים ייעוץ בנושא סיווג תושבות במסגרת תכנון לקראת הגעה לישראל.',
    'tax.cta.title': 'בהירות לפני שאתם מתחייבים',
    'tax.cta.body': 'התחילו בבדיקת מס מסודרת, שתהפוך את חוסר הוודאות להחלטות מתועדות. ניתן לפנות אלינו באנגלית ובעברית.',
    'tax.cta.button': 'בקש ביקורת מס',
    'olim.hero.title': 'ייעוץ משפטי לעולים חדשים ולתושבים חוזרים',
    'olim.hero.subtitle': 'ייעוץ משפטי ברור ואישי לאחד מהמעברים המשמעותיים ביותר בחיים.',
    'olim.context.title': 'פרק חדש, המתוכנן מראש מהיום הראשון',
    'olim.context.body': 'פתיחת פרק חדש בישראל טומנת בחובה הזדמנויות, מורכבות ובחירות משפטיות חשובות. ההחלטות שתקבלו בחודשים הראשונים לאחר הגעתכם החל מאופן סיווג מעמד התושבות שלכם, דרך מועד רכישת הנכס ועד לאופן העברת ההון ישפיעו על מעמדכם הפיסקלי, על קשריכם הבנקאיים ועל המבנה הפיננסי שלכם לשנים הבאות.\\n\\nאנו מספקים ייעוץ משפטי סבלני, מותאם אישית ומובנה לעולים חדשים ולתושבים חוזרים. כל לקוח מקבל מפת דרכים ברורה המותאמת למצב הספציפי שלו, כך שלא יוחמץ אף צעד קריטי ולא יאבדו הטבות עקב תזמון לא נכון או תיעוד חלקי.',
    'olim.context.body2': '',
    'olim.framework.title': 'מסגרת הנחיתה הרכה',
    'olim.framework.planning.title': 'תכנון לקראת ההגעה',
    'olim.framework.planning.desc': 'בחינת מעמד התושבות של הלקוח, פרופיל נכסיו ומבנה משפחתו לפני הגעתו. זיהוי החלטות הדורשות תגובה מהירה ופעולה מתאימה כדי לשמור על זכאותו של הלקוח להטבות הקיימות.',
    'olim.framework.property.title': 'תיאום רכישת נכסים',
    'olim.framework.property.desc': 'ניהול ההיבטים המשפטיים של רכישת נכס ראשון בישראל, לרבות בדיקת נאותות, משא ומתן על חוזה, הגשת דוחות מס ורישום, תוך מתן תשומת לב מיוחדת לקשר שבין מועד הרכישה לבין מעמד של עולה או תושב חוזר.',
    'olim.framework.banking.title': 'בנקאות והעברות הון',
    'olim.framework.banking.desc': 'הכנת מסמכי מקור הכספים, תיאום עם הבנק הישראלי המקבל, והבטחת קבלת העברות בינלאומיות ללא עיכובים או סיבוכים מיותרים.',
    'olim.framework.peace.title': 'תמיכה דו-לשונית וחוצת גבולות',
    'olim.framework.peace.desc': 'אנו מתקשרים באנגלית ובעברית, ומתאמים עם היועצים הזרים של הלקוח במידת הצורך. המטרה היא לתרגם תהליכים משפטיים מורכבים בישראל לשלבים ברורים ומעשיים, ובכך להקנות ביטחון בתקופה שהיא אחת מהמעברים המשמעותיים ביותר בחיים.',
    'olim.tax.title': 'מיסוי לעולים חדשים ולתושבים חוזרים',
    'olim.tax.body': 'עולים חדשים ותושבים חוזרים העומדים בקריטריונים עשויים להיות זכאים להקלות ספציפיות, לרבות שיעורי מס רכישה מופחתים ופטור בן עשר שנים מחובת דיווח על הכנסות ממקורות זרים. הטבות אלה כפופות לקריטריוני זכאות מחמירים, ולכן תזמון נכון, סיווג נכון ותיעוד נכון הם חיוניים כדי להבטיח את קבלתן.',
    'olim.tax.body2': 'אנו מסייעים ללקוחות להבין כיצד הנסיבות הספציפיות שלהם משפיעות על סיווגם, אילו מסמכים נדרשים וכיצד יש לתכנן את מועד הגעתם ואת העסקאות הראשונות שלהם, כדי לאפשר מעבר תואם לדרישות החוק ויעיל מבחינה מיסויית למערכת הישראלית.',
    'olim.clients.title': 'למי מיועד השירות הזה',
    'olim.clients.body': 'תחום פעילות זה מיועד ליחידים ומשפחות העוברים לישראל, אשר מחזיקים בנכסים משמעותיים, בהכנסות מחו"ל או במבנים פיננסיים חוצי גבולות. בין אם אתם עוברים מארצות הברית, בריטניה, אירופה או מכל מקום אחר, אנו מקדישים את אותה רמת תשומת לב וטיפול לכל פרויקט. לקוחותינו מעריכים גישה מסודרת, המציבה את הציות לתקנות בראש סדר העדיפויות, ומבינים כי ההחלטות המשפטיות והפיננסיות שיינקטו בתקופת המעבר יעצבו את מעמדם בישראל לשנים הבאות.',
    'olim.expect.title': 'למה לצפות',
    'olim.expect.body': 'התהליך מתחיל בתהליך קליטה מובנה. רשימת בדיקה מותאמת אישית, הערכת מעמד תושבות ומצב מס, ותוכנית פעולה מתואמת הכוללת שלבים הבאים המוגדרים בבירור. כל לקוח יודע מה נדרש ממנו, מתי נדרש ממנו, ומדוע זה חשוב.',
    'olim.expect.item1': 'רשימת בדיקה לתיעוד המותאמת למצבכם',
    'olim.expect.item2': 'מיפוי מעמד תושבות ומעמד מס',
    'olim.expect.item3': 'תוכנית פעולה מתואמת הכוללת את הצעדים הבאים',
    'olim.cta.title': 'התחילו פרק חדש בחייכם בביטחון',
    'olim.cta.body': 'אנו מבינים שמעבר לישראל הוא יותר מתהליך משפטי. זוהי החלטה המשפיעה על כל תחומי החיים. תנו לנו לעזור לכם לקבל אותה בבהירות, בשיטתיות ובשלווה. ניתן לפנות אלינו באנגלית ובעברית.',
    'olim.cta.button': 'תכננו את הגעתכם',
    'commercial.hero.title': 'מסחרי ואזרחי',
    'commercial.hero.subtitle': 'הגנה על האינטרסים העסקיים באמצעות חוזים מפורטים, חלוקת סיכונים מובנית וייצוג בישראל בעניינים בינלאומיים.',
    'commercial.philosophy.title': 'דיוק לפני מחלוקות',
    'commercial.philosophy.body': 'בעסקאות מסחריות, עוצמת עמדתכם תלויה באיכות החוזים שלכם. בין אם מדובר בניסוח הסכם בעלי מניות, במשא ומתן על יציאה מהחברה או בבניית הסדר חוצה גבולות, אנו בוחנים כל עניין מבעד לשלוש נקודות מבט זכויות חוזיות, חשיפה פיננסית ואכיפות עתידית.',
    'commercial.philosophy.body2': 'גישה זו משקפת את תחומי ההתמחות המרכזיים שלנו. ניתוח משפטי המושתת על הבנה פיננסית. הלקוחות מקבלים ייעוץ מובנה התומך במשא ומתן, בפתרון סכסוכים או בהליכים משפטיים, בהתאם לדרישות העניין.',
    'commercial.services.title': 'שירותים עיקריים',
    'commercial.services.contracts.title': 'ניסוח ובדיקת חוזים',
    'commercial.services.contracts.desc': 'ניסוח הסכמי בעלי מניות, הסכמי שותפות, חוזי שכירות מסחריים, חוזי שירות ומסמכים מסחריים אחרים, הכוללים הגדרות מדויקות, חלוקת סיכונים ברורה וסעדים הניתנים לאכיפה.',
    'commercial.services.negotiation.title': 'משא ומתן וניהול סיכונים',
    'commercial.services.negotiation.desc': 'ייעוץ משפטי אסטרטגי לפני החתימה או במהלך הסלמה, במטרה לשפר את כוח המיקוח של הלקוח, לנהל את החשיפה ולהגדיר תוצאות מקובלות.',
    'commercial.services.dispute.title': 'אסטרטגיה ופתרון סכסוכים',
    'commercial.services.dispute.desc': 'ניתוח טרום-משפטי, מסגרות להסדר וניהול הליכים משפטיים במידת הצורך. הגישה שלנו מעניקה עדיפות לאינטרסים המסחריים של הלקוח, בין אם הדבר מצריך אכיפה נחושה ובין אם פתרון מוסכם.',
    'commercial.services.crossborder.title': 'תיעוד חוצה גבולות',
    'commercial.services.crossborder.desc': 'תיאום עם עורכי דין בחו"ל ותרגום חוזים ופסיקות זרים לצורך אכיפה או הכרה בישראל.',
    'commercial.crossborder.title': 'אינטרסים עסקיים חוצי גבולות',
    'commercial.crossborder.body': 'אנו משמשים כנציגים משפטיים מקומיים עבור לקוחות המתגוררים בחו"ל אך מחזיקים באינטרסים מסחריים או פיננסיים פעילים בישראל. מדובר, בין היתר, במשקיעים, בעלי עסקים ומנהלים הזקוקים לייעוץ משפטי שוטף בישראל או הנדרשים להגן על זכויות וחובות ספציפיות במסגרת מערכת המשפט הישראלית.',
    'commercial.crossborder.body2': 'בין אם מדובר באכיפת חוזה זר בישראל, בהגנה על זכויות בעלי מניות בחו"ל או בניהול סכסוך מסחרי עם צד ישראלי, אנו מספקים ייצוג מעשי בשטח. המחלקה מתאמת את הדרישות המשפטיות הישראליות עם יועצים משפטיים זרים ועם אסטרטגיה חוצת גבולות, ומבטיחה כי עמדת הלקוח תהיה עקבית וניתנת לאכיפה בכל תחומי השיפוט.',
    'commercial.clients.title': 'עם מי אנחנו עובדים',
    'commercial.clients.body': 'מחלקת המסחר משרתת בעלי עסקים, משקיעים, מנהלים ולקוחות פרטיים הזקוקים לייעוץ משפטי קפדני בנושאי חוזים, הגנה על נכסים וסכסוכים מורכבים. בין אם מדובר בעסקה חד-פעמית ובין אם בקשר ייעוצי מתמשך, אנו מספקים את אותה רמת עומק אנליטי ותשומת לב אישית.',
    'commercial.cta.title': 'הגן על מעמדך העסקי',
    'commercial.cta.body': 'התחילו בבדיקת חוזה, בהערכת סיכונים או בייעוץ בנושא אסטרטגיה לטיפול בסכסוכים. השירות ניתן בסודיות ומתועד. ניתן לפנות אלינו באנגלית ובעברית.',
    'commercial.cta.button': 'קבעו פגישת ייעוץ',
  }
};

// NOTE: Keep a stable Context instance across hot-reloads to avoid "must be used within a Provider" errors.
// This is especially important in development, since we frequently edit translations.
const _global = globalThis as unknown as {
  __mayaLanguageContext?: React.Context<LanguageContextType | undefined>;
};

const LanguageContext =
  _global.__mayaLanguageContext ?? createContext<LanguageContextType | undefined>(undefined);

_global.__mayaLanguageContext = LanguageContext;

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('maya-ziv-lang');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'he';

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('maya-ziv-lang', lang);
  }, []);

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t,
    isRTL
  }), [language, t, isRTL]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};